### ISSUE TITLE
[Bug]: Running image pipeline reports an error, reporting that git-lfs needs to be installed

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#1041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
Testing test_embedding_image_list:image-embedding
2022-04-08 15:24:55,831 - 4631555584 - git_utils.py-git_utils:101 - ERROR: You have not install git-lfs, please install it first https://git-lfs.github.com.
Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.9/site-packages/towhee/utils/git_utils.py", line 99, in clone
    subprocess.check_call(['git', 'lfs'], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'lfs']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_main.py", line 238, in <module>
    test_caller()
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_main.py", line 228, in test_caller
    image_class_pipeline_runner()
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_main.py", line 74, in image_class_pipeline_runner
    res = methodcaller(func, pipeline_name)(invalid_embedding_obj)
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_image_embedding.py", line 69, in test_embedding_image_list
    embedding_pipeline = pipeline(pipeline_name)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.9/site-packages/towhee/__init__.py", line 140, in pipeline
    yaml_path = fm.get_pipeline(p_repo, tag, install_reqs)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.9/site-packages/towhee/hub/file_manager.py", line 358, in get_pipeline
    git.clone(tag=tag, install_reqs=install_reqs, local_repo_path=repo_path)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.9/site-packages/towhee/utils/git_utils.py", line 102, in clone
    raise Exception('You have not install git-lfs, please install it first https://git-lfs.github.com.') from e
Exception: You have not install git-lfs, please install it first https://git-lfs.github.com.
```

  ```
  def test_embedding_image_list(self, pipeline_name):
        """
        target: test embedding with image list
        method:  embedding with image list
        expected: raise exception
        """
        N = 3
        img_list = []
        img = cf.create_image()
        for i in range(N):
            img_list.append(img)
        embedding_pipeline = pipeline(pipeline_name)
        try:
            embedding = embedding_pipeline(img_list)
        except Exception as e:
            print("Raise Exception: %s" % e)

        return True
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):towhee 0.5.1.dev164
- OS(Ubuntu or CentOS):macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jingkl** [comment]
After verification, an error will be reported
<img width="1440" alt="截屏2022-04-08 19 12 27" src="https://user-images.githubusercontent.com/34296482/162424837-adc979fc-9bf3-4d63-bab5-d862aed60073.png">

**Comment by jingkl** [comment]
It has been verified, no problem
<img width="1425" alt="截屏2022-04-08 19 57 49" src="https://user-images.githubusercontent.com/34296482/162431108-2b4f7461-868c-4d71-81d5-ea5a4caca335.png">

**Comment by jingkl** [comment]
No problem. Close the issue
