### ISSUE TITLE
[Bug]: Running the select case reports an error“TypeError: 'NoneType' object is not iterable”

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#1042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> from towhee import Entity
>>> from towhee import DataCollection
>>> dc = DataCollection([Entity(a=i, b=i, c=i) for i in range(2)])
>>> dc.select('a').to_list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.9/site-packages/towhee/hparam/hyperparameter.py", line 205, in __call__
    return self._callback(self._path, self._index, *args, **kwds)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.9/site-packages/towhee/functional/mixins/entity_mixin.py", line 31, in wrapper
    return self._factory(map(inner, self._iterable))
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 210, in wrapper
    return creator(*arg, **kws)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 165, in unstream
    iterable = list(iterable)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.9/site-packages/towhee/functional/mixins/entity_mixin.py", line 28, in inner
    data = {column: getattr(entity, column) for column in index}
TypeError: 'NoneType' object is not iterable
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):towhee 0.5.1.dev164
- OS(Ubuntu or CentOS):macOS
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment]
try to use `dc.select['a']().to_list()` at the last line

**Comment by reiase** [comment]
@shiyu22 please also take a look at this issue. We'd better not throw the NoneType exception on wrong arguments.

**Comment by binbinlv** [comment]
@jingkl 
please verify this issue, thanks.

**Comment by jingkl** [comment]
It has been verified, no problem
