### ISSUE TITLE
[Bug]: ModuleNotFoundError "No module named 'scipy'" when importing pipeline from towhee

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> from towhee import pipeline
2022-05-10 15:14:41,240 - 139965516519232 - sklearn.py-sklearn:23 - ERROR: scipy not found, you can install via `pip install scipy`.
Traceback (most recent call last):
  File "/home/lvbin/binbin/binbin-test/towhee-3.6/lib/python3.6/site-packages/towhee/hub/builtin/operators/sklearn.py", line 21, in <module>
    from scipy import sparse
ModuleNotFoundError: No module named 'scipy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lvbin/binbin/binbin-test/towhee-3.6/lib/python3.6/site-packages/towhee/__init__.py", line 16, in <module>
    from towhee.engine.factory import ops, pipeline, DEFAULT_PIPELINES, _PipelineBuilder as Build
  File "/home/lvbin/binbin/binbin-test/towhee-3.6/lib/python3.6/site-packages/towhee/engine/factory.py", line 26, in <module>
    from towhee.hub import preclude
  File "/home/lvbin/binbin/binbin-test/towhee-3.6/lib/python3.6/site-packages/towhee/hub/preclude/__init__.py", line 19, in <module>
    import towhee.hub.builtin.operators.sklearn
  File "/home/lvbin/binbin/binbin-test/towhee-3.6/lib/python3.6/site-packages/towhee/hub/builtin/operators/sklearn.py", line 24, in <module>
    raise ModuleNotFoundError('scipy not found, you can install via `pip install scipy`.') from e
ModuleNotFoundError: scipy not found, you can install via `pip install scipy`.
```

### Expected Behavior

No error

### Steps To Reproduce

1. Create a new virtual env of python3.6 (or python3.8, all the python versions)
2. install latest towhee from testpypi:

```
    pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple towhee==0.6.1.dev104
```

3. Run
```
from towhee import pipeline
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.6.1.dev104
- OS(Ubuntu or CentOS):ubuntu and mac
- CPU/Memory:
- GPU:
- Others:
```

**Comment by Chiiizzzy** [comment]
It is an expected result because we don't want to introduce scipy as towhee's dependency. Therefore we raise such Error and tell users to manually install scipy.

**Comment by binbinlv** [comment]
Here this error is reported just from the first step of using towhee "from towhee import pipeline".

Could we not depends on this module just from the beginning of import pipeline? just report this error wherever using this module?

**Comment by filip-halt** [comment]
Its because we are forcing import of sklearn.py in [preclude](https://github.com/towhee-io/towhee/blob/main/towhee/hub/preclude/__init__.py). This causes the scipy check. One way to get around it is to do nested imports of scipy within sklearn.py

**Comment by binbinlv** [comment]
Reopen for verification.

**Comment by binbinlv** [comment]
Verified in 0.6.1.dev117, it is fixed.
