### ISSUE TITLE
[Bug]: The previous pipeline "towhee/image-embedding-inception-resnet-v2" is not found now

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The previous pipeline "towhee/image-embedding-inception-resnet-v2" is not found now
```
>>> embedding_pipeline = pipeline('towhee/image-embedding-inception-resnet-v2')
2022-05-12 16:40:26,736 - 140016175531840 - git_utils.py-git_utils:101 - WARNING: 'git-lfs' not found, execute download instead of clone. If you want to download large file with git-lfs, please install 'git-lfs' and remove current local cache.
Downloading README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.18k/1.18k [00:00<00:00, 1.06MiB/s]
Traceback (most recent call last):
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/utils/git_utils.py", line 99, in clone
    subprocess.check_call(['git', 'lfs'], stdout=subprocess.DEVNULL, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'lfs']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/hub/file_manager.py", line 364, in get_pipeline
    git.clone(tag=tag, install_reqs=install_reqs, local_repo_path=repo_path)
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/utils/git_utils.py", line 105, in clone
    raise FileNotFoundError('\'git-lfs\' not found, execute download instead of clone. ' \
FileNotFoundError: 'git-lfs' not found, execute download instead of clone. If you want to download large file with git-lfs, please install 'git-lfs' and remove current local cache.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/engine/factory.py", line 231, in pipeline
    yaml_path = fm.get_pipeline(p_repo, tag, install_reqs, from_ops)
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/hub/file_manager.py", line 368, in get_pipeline
    pipeline_manager.download(local_repo_path=file_path.parent, tag=tag, install_reqs=install_reqs)
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/hub/repo_manager.py", line 270, in download
    self.download_files(tag=tag, file_list=file_list, lfs_files=lfs_files, local_repo_path=local_repo_path, install_reqs=install_reqs)
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/hub/repo_manager.py", line 243, in download_files
    raise e
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/hub/repo_manager.py", line 239, in download_files
    _ = [i.result() for i in futures]
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/hub/repo_manager.py", line 239, in <listcomp>
    _ = [i.result() for i in futures]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/hub/repo_manager.py", line 199, in download_executor
    raise e
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/hub/repo_manager.py", line 197, in download_executor
    res.raise_for_status()
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://towhee.io/api/v1/repos/towhee/image-embedding-inception-resnet-v2/raw/image_embedding_inception_resnet_v2.yaml?ref=main
```

### Expected Behavior

pipeline "towhee/image-embedding-inception-resnet-v2"  runs successfully

### Steps To Reproduce

```markdown
>>> from towhee import pipeline
>>> embedding_pipeline = pipeline('towhee/image-embedding-inception-resnet-v2')
```
```


### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.6.1.dev113
- OS(Ubuntu or CentOS): both
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@reiase @filip-halt 
could you please have a look? thank.

**Comment by shiyu22** [comment]
Update the request in towhee #1243.

**Comment by binbinlv** [comment]
Reopen for verification.

**Comment by binbinlv** [comment]
verified and fixed:
```
>>> from towhee import pipeline
>>> embedding_pipeline = pipeline('towhee/image-embedding-inception-resnet-v2')
2022-05-13 13:11:41,072 - 139781067478848 - git_utils.py-git_utils:101 - WARNING: 'git-lfs' not found, execute download instead of clone. If you want to download large file with git-lfs, please install 'git-lfs' and remove current local cache.
Downloading README.md: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.18k/1.18k [00:00<00:00, 815kiB/s]
Downloading image_embedding_inception_resnet_v2.yaml: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 1.21k/1.21k [00:00<00:00, 873kiB/s]
>>>
>>>
```
