### ISSUE TITLE
[Bug]: Call “DataCollection.stream” failed reporting "AttributeError: 'range' object has no attribute 'is_stream'"

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
from towhee import DataCollection
dc = DataCollection.stream(range(10000))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lvbin/binbin/binbin-test/towhee-3.8/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 121, in stream
    iterable = iter(self._iterable) if not self.is_stream else self._iterable
AttributeError: 'range' object has no attribute 'is_stream'
```

### Expected Behavior

No errors

### Steps To Reproduce

```markdown
1 install towhee:
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple towhee==0.6.1.dev113

2.

from towhee import DataCollection
dc = DataCollection.stream(range(10000))
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.6.1.dev113
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by filip-halt** [comment]
stream() is not longer a producing method. this line is now DataCollection(range(10000)).stream()

**Comment by binbinlv** [comment]
https://docs.towhee.io/User%20Guides/DataCollection/data-collection/

So the doc about stream() should be modified?

![image](https://user-images.githubusercontent.com/83755740/168194582-e1a680d2-ccb4-4406-b839-c94979efbe24.png)

**Comment by binbinlv** [comment]
fixed, and closed.
