### ISSUE TITLE
[Bug]: print the output of towhee.api raised a json error.

### ISSUE THREAD

**Issue by wxywb** [towhee-io/towhee#1500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when executing following snippet
```python
import towhee
with towhee.api['path']() as api:
    pipeline = api.image_decode['path','img']()\
    .image_embedding.timm['img','emb1'](model_name='resnet18') \
    .image_embedding.timm['img','emb2'](model_name='resnet34') \
    .ensemble.weighted_concat_ensemble[('emb1','emb2'),'emb'](weights=(1.0,1.0)) \
    .as_function()
    out = pipeline('test.jpeg')
    print(out)
```

An TypeError occured
```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    print(out)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/site-packages/towhee/functional/entity.py", line 69, in __str__
    return json.dumps({k: getattr(self, k) for k in self.__dict__})
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/zilliz/opt/anaconda3/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Image is not JSON serializable
```

### Expected Behavior

should not raise an Exception.

### Steps To Reproduce

```markdown
executing the snippet
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment]
the default behavior for converting an entity to string is not well defined, we need to rewrite the repo method of Entity
