### ISSUE TITLE
[Bug]: reverse_ image_ Search cannot run in an offline environment

### ISSUE THREAD

**Issue by 2132660698** [towhee-io/towhee#1523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I follow
https://github.com/milvus-io/bootcamp/tree/v2.0.2/solutions/reverse_image_search/quick_deploy 
Option 2: Deploy with source code
When I upload pictures for indexing, Python **src/main.py** has the following error:

_```
[root@localhost src]# python3 main.py
/usr/local/python3/lib/python3.8/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
2022-07-07 15:07:44,036 - 139808216160064 - milvus_helpers.py-milvus_helpers:19 - DEBUG: Successfully connect to Milvus with IP:127.0.0.1 and PORT:19530
2022-07-07 15:07:44,051 - 139808216160064 - selector_events.py-selector_events:59 - DEBUG: Using selector: EpollSelector
INFO:     Started server process [20602]
2022-07-07 15:07:44,066 - 139808216160064 - server.py-server:64 - INFO: Started server process [20602]
2022-07-07 15:07:44,066 ｜ INFO ｜ server.py ｜ serve ｜ 64 ｜ Started server process [20602]
INFO:     Waiting for application startup.
2022-07-07 15:07:44,066 - 139808216160064 - on.py-on:26 - INFO: Waiting for application startup.
2022-07-07 15:07:44,066 ｜ INFO ｜ on.py ｜ startup ｜ 26 ｜ Waiting for application startup.
INFO:     Application startup complete.
2022-07-07 15:07:44,067 - 139808216160064 - on.py-on:38 - INFO: Application startup complete.
2022-07-07 15:07:44,067 ｜ INFO ｜ on.py ｜ startup ｜ 38 ｜ Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
2022-07-07 15:07:44,067 - 139808216160064 - server.py-server:199 - INFO: Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
2022-07-07 15:07:44,067 ｜ INFO ｜ server.py ｜ _log_started_message ｜ 199 ｜ Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
2022-07-07 15:08:04,083 - 139808216160064 - milvus_helpers.py-milvus_helpers:121 - DEBUG: Successfully get the num:0 of the collection:milvus_img_search
2022-07-07 15:08:04,084 - 139808216160064 - main.py-main:125 - INFO: Successfully count the number of images!
2022-07-07 15:08:04,084 ｜ INFO ｜ main.py ｜ count_images ｜ 125 ｜ Successfully count the number of images!
INFO:     10.20.199.208:51662 - "POST /img/count HTTP/1.1" 200 OK
INFO:     10.20.199.208:51681 - "OPTIONS /img/load HTTP/1.1" 200 OK
--------------------resnet50_extract_feat 111-----------------------------
2022-07-07 15:12:06,351 - 139808216160064 - connectionpool.py-connectionpool:1001 - DEBUG: Starting new HTTPS connection (1): towhee.io:443
2022-07-07 15:12:06,353 - 139808216160064 - load.py-load:37 - ERROR: Error with extracting feature from image HTTPSConnectionPool(host='towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image-decode (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f273c1a5fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-07-07 15:12:06,353 ｜ ERROR ｜ load.py ｜ extract_features ｜ 37 ｜ Error with extracting feature from image HTTPSConnectionPool(host='towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image-decode (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f273c1a5fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
--------------------resnet50_extract_feat 111-----------------------------
2022-07-07 15:12:06,357 - 139808216160064 - connectionpool.py-connectionpool:1001 - DEBUG: Starting new HTTPS connection (1): towhee.io:443
2022-07-07 15:12:06,358 - 139808216160064 - load.py-load:37 - ERROR: Error with extracting feature from image HTTPSConnectionPool(host='towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image-decode (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f273c1d6af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-07-07 15:12:06,358 ｜ ERROR ｜ load.py ｜ extract_features ｜ 37 ｜ Error with extracting feature from image HTTPSConnectionPool(host='towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image-decode (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f273c1d6af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
--------------------resnet50_extract_feat 111-----------------------------
2022-07-07 15:12:06,362 - 139808216160064 - connectionpool.py-connectionpool:1001 - DEBUG: Starting new HTTPS connection (1): towhee.io:443
2022-07-07 15:12:06,363 - 139808216160064 - load.py-load:37 - ERROR: Error with extracting feature from image HTTPSConnectionPool(host='towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image-decode (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f273c1d6700>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-07-07 15:12:06,363 ｜ ERROR ｜ load.py ｜ extract_features ｜ 37 ｜ Error with extracting feature from image HTTPSConnectionPool(host='towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image-decode (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f273c1d6700>: Failed to establish a new connection: [Errno 111] Connection refused'))
2022-07-07 15:12:06,382 - 139808216160064 - milvus_helpers.py-milvus_helpers:72 - ERROR: Failed to load data to Milvus: list index out of range
2022-07-07 15:12:06,382 ｜ ERROR ｜ milvus_helpers.py ｜ insert ｜ 72 ｜ Failed to load data to Milvus: list index out of range
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/milvus/bootcamp/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 65, in insert
    mr = self.collection.insert(data)
  File "/usr/local/python3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 528, in insert
    if not self._check_insert_data_schema(data):
  File "/usr/local/python3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 179, in _check_insert_data_schema
    infer_fields = parse_fields_from_data(data)
  File "/usr/local/python3/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 296, in parse_fields_from_data
    d_type = infer_dtype_bydata(d[0])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/python3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/python3/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/python3/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "main.py", line 70, in load_images
    total_num = do_load(item.Table, item.File, MODEL, MILVUS_CLI, MYSQL_CLI)
  File "/data/milvus/bootcamp/solutions/reverse_image_search/quick_deploy/server/src/operations/load.py", line 59, in do_load
    ids = milvus_client.insert(table_name, vectors)
  File "/data/milvus/bootcamp/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 73, in insert
    sys.exit(1)
SystemExit: 1
2022-07-07 15:12:06,382 - 139808216160064 - h11_impl.py-h11_impl:399 - ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/data/milvus/bootcamp/solutions/reverse_image_search/quick_deploy/server/src/milvus_helpers.py", line 65, in insert
    mr = self.collection.insert(data)
  File "/usr/local/python3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 528, in insert
    if not self._check_insert_data_schema(data):
  File "/usr/local/python3/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 179, in _check_insert_data_schema
    infer_fields = parse_fields_from_data(data)
  File "/usr/local/python3/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 296, in parse_fields_from_data
    d_type = infer_dtype_bydata(d[0])
IndexError: list index out of range

```_

**Comment by binbinlv** [comment]
@shiyu22 Could you please have a look? Thanks.

**Comment by shiyu22** [comment]
Hi @2132660698 I think this is caused by the failure to download the operator in [hub](https://towhee.io/tasks/operator). If you are in offline environment , can you download the towhee operator and python dependencies of reverse image search first?


For example in the [encode](https://github.com/milvus-io/bootcamp/blob/v2.0.2/solutions/reverse_image_search/quick_deploy/server/src/encode.py) process, it will use this pipeline to deal with the image data:
```python
feat = towhee.glob(img_path) \
                .image_decode() \
                .image_embedding.timm(model_name='resnet50') \
                .to_list()
```
So you need to download the image_decode and image_embedding.timm op to `~/.towhee`, and install the requirements.txt om the repo. I think you can run the above code on another machine and copy the whole `~/.towhee` folder.


Another suggestion is that you can run this solution with docker method, then you can use `docker cp <container id>:~/.towhee .` to get the file, of course you can get the python environment too.

**Comment by 2132660698** [comment]
It's OK,Thanks!
