### ISSUE TITLE
Pipeline crashed with exception when there is no image

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#154]
Steps/Code to reproduce:
1 setup env and install towhee:
```python3
python3 -m venv towhee-test-env
pip install -U pip
pip install towhee
```
2 into python env: phthon3:
```python3
from towhee import pipeline
p = pipeline('image-embedding')
embedding = p()
```
Expected result:
Return error

Actual results:
pipeline crashed with eexception:
```
>>> embedding = p()
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/binbin/Towee/towhee-test-env/lib/python3.8/site-packages/towhee/engine/engine.py", line 85, in run
    self._task_sched.schedule_forever(self._config.sched_interval_ms)
  File "/Users/binbin/Towee/towhee-test-env/lib/python3.8/site-packages/towhee/engine/task_scheduler.py", line 78, in schedule_forever
    self.schedule_step()
  File "/Users/binbin/Towee/towhee-test-env/lib/python3.8/site-packages/towhee/engine/task_scheduler.py", line 139, in schedule_step
    tasks = op_ctx.pop_ready_tasks(n_tasks=1)
  File "/Users/binbin/Towee/towhee-test-env/lib/python3.8/site-packages/towhee/engine/operator_context.py", line 99, in pop_ready_tasks
    op_input_params = self._reader.read()
  File "/Users/binbin/Towee/towhee-test-env/lib/python3.8/site-packages/towhee/engine/_operator_io.py", line 87, in read
    return self._to_op_inputs(data[0])
  File "/Users/binbin/Towee/towhee-test-env/lib/python3.8/site-packages/towhee/engine/_operator_io.py", line 63, in _to_op_inputs
    ret[key] = cols[index].value
IndexError: tuple index out of range
```

Environment:
Mac OS

**Comment by fzliu** [comment]
Leaving this issue open for now (will be fixed in v0.2).
