### ISSUE TITLE
[Bug]: Error “The 'detectron2' distribution was not found” occurs when running object detection embedding 

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error “operator object-detection/detectron2 not found!” occurs when running object detection embedding 

### Expected Behavior

No error

### Steps To Reproduce

```
>>> import towhee
>>>
>>>
>>> towhee.glob('/Users/binbin/Towhee_projects/image.png') \
...       .image_decode() \
...       .object_detection.detectron2(model_name='retinanet_resnet50') \
...       .show()
Cloning the repo: object-detection/detectron2... Be patient and waiting printing 'Successfully'.
正克隆到 '/Users/binbin/.towhee/operators/object-detection/detectron2/main'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 24 (delta 7), reused 0 (delta 0), pack-reused 0
接收对象中: 100% (24/24), 1.46 MiB | 2.60 MiB/s, 完成.
处理 delta 中: 100% (7/7), 完成.
Successfully clone the repo: object-detection/detectron2.
Traceback (most recent call last):
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 1143, in parse_string
    raise exc.with_traceback(None)
pkg_resources._vendor.pyparsing.exceptions.ParseException: Expected string_end, found ':'  (at char 5), (line:1, col:6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 134, in load_operator_from_cache
    path = fm.get_operator(operator=function, tag=tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/hub/file_manager.py", line 451, in get_operator
    git.clone(tag=tag, install_reqs=install_reqs, local_repo_path=repo_path)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/utils/git_utils.py", line 134, in clone
    pkg_resources.require(req)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 751, in resolve
    requirements = list(requirements)[::-1]
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3102, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'://githu'": Expected string_end

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 198, in __call__
    return self._func(*args, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 156, in wrapper
    return self.map(op)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/mixins/dag.py", line 11, in wrapper
    children = f(self, *arg, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 315, in map
    if hasattr(unary_op, 'is_stateful') and unary_op.is_stateful:
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/execution/stateful_execution.py", line 30, in is_stateful
    self.__check_init__()
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 93, in __check_init__
    self._op = op(self._name,
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 61, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 162, in load_operator
    op = factory(function, arg, kws, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 136, in load_operator_from_cache
    raise ValueError('operator {} not found!'.format(function)) from e
ValueError: operator object-detection/detectron2 not found!
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): towhee 0.7.3.dev32 (models latest)
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@filip-halt 
Hi, filip, could you help to fix this issue? Thanks.

**Comment by binbinlv** [comment]
After the fix of @jaelgu, now the module not found error is fixed, but has the following error:
```
>>> towhee.glob('/Users/binbin/Towhee_projects/image.png') \
... .image_decode() \
... .object_detection.detectron2(model_name='retinanet_resnet50') \
... .show()
Traceback (most recent call last):
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 101, in load_operator_from_path
    pkg_resources.require(req)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'detectron2' distribution was not found and is required by the application
```

**Comment by binbinlv** [comment]
@jaelgu 
It seems "detectron2" was not downloaded automatically, then how to install "detectron2"?

**Comment by binbinlv** [comment]
1. The first issue is here "detectron2" could not be installed successfully through "pip install detectron2"

2. And when installed detectron2 manually, it reports error:
'Image' object has no attribute 'to_ndarray'.

@fzliu  hello, frank, could you please help to fix this? Thanks.

**Comment by filip-halt** [comment]
pip is having trouble with the link. The requirements link needs to be `detectron2 @ git+https://github.com/facebookresearch/detectron2.git@v0.6#egg=detectron2` for detectron2.

**Comment by filip-halt** [comment]
to_ndarray removed as Images are now subclasses of ndarray, so calling directly on the image works.

**Comment by binbinlv** [comment]
@filip-halt The following error still exists.  And I see your code in the "requirements" has been commented:
detectron2
# https://github.com/facebookresearch/detectron2/archive/refs/tags/v0.6.tar.gz
https://towhee.io/object-detection/detectron2/src/branch/main/requirements.txt

```
>>> towhee.glob('/Users/binbin/Towhee_projects/2021825-19039.jpg') \
... .image_decode() \
... .object_detection.detectron2(model_name='retinanet_resnet50') \
... .show()
...
pkg_resources.DistributionNotFound: The 'detectron2' distribution was not found and is required by the application
```

**Comment by binbinlv** [comment]
Fixed, so close it.
```
>>> import towhee
>>>
>>> towhee.glob('/Users/binbin/Towhee_projects/image.png') \
... .image_decode() \
... .object_detection.detectron2(model_name='retinanet_resnet50') \
... .show()
...
<IPython.core.display.HTML object>
```
