### ISSUE TITLE
[Bug]: deepface() missing 1 required positional argument: 'model_name'

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

deepface() missing 1 required positional argument: 'model_name'
```
>>> towhee.glob['path']('/Users/binbin/Towhee_projects/image.png') \
...   .image_decode.cv2['path', 'img']() \
...   .face_embedding.deepface['img', 'vec']() \
...   .select['img','vec']() \
...   .show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 198, in __call__
    return self._func(*args, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 156, in wrapper
    return self.map(op)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 514, in map
    arg[0].__check_init__()
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 93, in __check_init__
    self._op = op(self._name,
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 61, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 162, in load_operator
    op = factory(function, arg, kws, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 141, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 127, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 172, in instance_operator
    return op(*arg, **kws) if kws is not None else op()
TypeError: deepface() missing 1 required positional argument: 'model_name'
```

### Expected Behavior

NO error

### Steps To Reproduce

```markdown
https://towhee.io/face-embedding/deepface:

import towhee

towhee.glob['path']('./test_face.jpgg') \
  .image_decode.cv2['path', 'img']() \
  .face_embedding.deepface['img', 'vec']() \
  .select['img','vec']() \
  .show()
```
```


### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): towhee 0.7.3.dev32 (models latest)
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by wxywb** [comment]
readme has been updated, please give a check.
