### ISSUE TITLE
[Bug]: Code is wrong reporting "operator towhee/select not found!" in face-landmark-detection for mobilefacenet

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> towhee.glob('/Users/binbin/Towhee_projects/image.png') \
...   .image_decode.cv2() \
...   .face_landmark_detection.mobilefacenet() \
...   .select('img','landmark') \
...   .to_list()
2022-07-20 12:08:07,482 - 4628667904 - git_utils.py-git_utils:96 - ERROR: towhee/select repo does not exist.
Traceback (most recent call last):
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 134, in load_operator_from_cache
    path = fm.get_operator(operator=function, tag=tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/hub/file_manager.py", line 451, in get_operator
    git.clone(tag=tag, install_reqs=install_reqs, local_repo_path=repo_path)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/utils/git_utils.py", line 97, in clone
    raise ValueError(f'{self._author}/{self._repo} repo does not exist.')
ValueError: towhee/select repo does not exist.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 198, in __call__
    return self._func(*args, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 156, in wrapper
    return self.map(op)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/mixins/dag.py", line 11, in wrapper
    children = f(self, *arg, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 315, in map
    if hasattr(unary_op, 'is_stateful') and unary_op.is_stateful:
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/execution/stateful_execution.py", line 30, in is_stateful
    self.__check_init__()
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 93, in __check_init__
    self._op = op(self._name,
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 61, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 162, in load_operator
    op = factory(function, arg, kws, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 136, in load_operator_from_cache
    raise ValueError('operator {} not found!'.format(function)) from e
ValueError: operator towhee/select not found!
```

### Expected Behavior

I think here ".select('img','landmark') \" is wrong?

The following is correct with ".select['img','landmark']() \"
```
>>> towhee.glob['path']('/Users/binbin/Towhee_projects/image.png') \
...   .image_decode.cv2['path', 'img']() \
...   .face_landmark_detection.mobilefacenet['img', 'landmark']() \
...   .select['img','landmark']() \
...   .show()
<IPython.core.display.HTML object>
```

### Steps To Reproduce

```markdown
https://towhee.io/face-landmark-detection/mobilefacenet
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):towhee 0.7.3.dev32 (models latest)
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by wxywb** [comment]
It has been fixed，please check the latest doc.
