### ISSUE TITLE
[Bug]: "AttributeError: module 'torchvision.transforms' has no attribute 'Scale'" when running image embdding with DOLG

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1595]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> towhee.glob('/Users/binbin/Towhee_projects/image.png') \
...       .image_decode.cv2() \
...       .image_embedding.dolg(img_size=512, input_dim=3, hidden_dim=1024, output_dim=2048) \
...       .show()
Cloning the repo: image-embedding/dolg... Be patient and waiting printing 'Successfully'.
正克隆到 '/Users/binbin/.towhee/operators/image-embedding/dolg/main'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 21 (delta 5), reused 0 (delta 0), pack-reused 0
接收对象中: 100% (21/21), 169.81 KiB | 191.00 KiB/s, 完成.
处理 delta 中: 100% (5/5), 完成.
Successfully clone the repo: image-embedding/dolg.
Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to /Users/binbin/.cache/torch/hub/checkpoints/resnet101-5d3b4d8f.pth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 198, in __call__
    return self._func(*args, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 156, in wrapper
    return self.map(op)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/mixins/dag.py", line 11, in wrapper
    children = f(self, *arg, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 336, in map
    return self._factory(result)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 268, in _factory
    iterable = list(iterable)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 333, in inner
    return unary_op(x)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/execution/base_execution.py", line 30, in __call__
    self.__check_init__()
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 93, in __check_init__
    self._op = op(self._name,
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 61, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 162, in load_operator
    op = factory(function, arg, kws, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 141, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 127, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 172, in instance_operator
    return op(*arg, **kws) if kws is not None else op()
  File "/Users/binbin/.towhee/operators/image-embedding/dolg/main/dolg.py", line 41, in __init__
    transforms.Scale([img_size, img_size]),
AttributeError: module 'torchvision.transforms' has no attribute 'Scale'
```

### Expected Behavior

NO error

### Steps To Reproduce

```markdown
https://towhee.io/image-embedding/dolg

import towhee

towhee.glob('./towhee.jpg') \
      .image_decode.cv2() \
      .image_embedding.dolg(img_size=512, input_dim=3, hidden_dim=1024, output_dim=2048) \
      .show()
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): towhee 0.7.3.dev32 (models latest)
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@wxywb 
so the readme in the following should be modified.
https://towhee.io/image-embedding/dolg

**Comment by binbinlv** [comment]
Fixed，so close it.
