### ISSUE TITLE
[Bug]: "TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType" when running operator text embedding with dpr

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> from towhee import ops
>>> text_encoder = ops.text_embedding.dpr(model_name="allenai/longformer-base-4096")
>>> text_embedding = text_encoder("Hello, world.")
2022-07-20 18:21:16,551 - 4816031232 - dpr.py-dpr:34 - ERROR: Fail to load tokenizer by name: allenai/longformer-base-4096
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/execution/base_execution.py", line 30, in __call__
    self.__check_init__()
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 93, in __check_init__
    self._op = op(self._name,
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 61, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 162, in load_operator
    op = factory(function, arg, kws, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 141, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 127, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 172, in instance_operator
    return op(*arg, **kws) if kws is not None else op()
  File "/Users/binbin/.towhee/operators/text-embedding/dpr/main/dpr.py", line 35, in __init__
    raise e
  File "/Users/binbin/.towhee/operators/text-embedding/dpr/main/dpr.py", line 32, in __init__
    self.tokenizer = DPRContextEncoderTokenizer.from_pretrained(model_name)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1783, in from_pretrained
    return cls._from_pretrained(
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1928, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/transformers/models/bert/tokenization_bert.py", line 213, in __init__
    if not os.path.isfile(vocab_file):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
https://towhee.io/towhee/nlp-dpr

from towhee import ops

text_encoder = ops.text_embedding.dpr(model_name="allenai/longformer-base-4096")
text_embedding = text_encoder("Hello, world.")
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): towhee 0.7.3.dev32 (models latest)
- OS(Ubuntu or CentOS): 
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
https://towhee.io/towhee/nlp-dpr 
The above operator has been deactivated, so cancel it.
