### ISSUE TITLE
[Bug]: Code is wrong for text_embedding with dpr

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Code is wrong for "nlp-dpr" in readme for this operator
```python
import towhee.DataCollection as dc

dc.glob("Hello, world.")
  .text_embedding.dpr('longformer-base-4096')
  .show()
```
```python
from towhee import DataCollection as dc

dc.glob['text']('Hello, world.')
  .text_embedding.dpr['text', 'vec']('longformer-base-4096')
  .select('vec')
  .show()
```

Now error 1:
```
>>> import towhee.DataCollection as dc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'towhee.DataCollection'
```
error 2:
dc.glob("Hello, world.") should like:
```
dc.glob("Hello, world.") \
```

error 3: (if I modify the code, then)
```
 >>> dc.glob("Hello, world.") \
... .text_embedding.dpr('longformer-base-4096') \
... .show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'DataCollection' has no attribute 'glob'
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
https://towhee.io/towhee/nlp-dpr
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):towhee 0.7.3.dev32 (models latest)
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
This operator page has been deactivated, so cancel it.
