### ISSUE TITLE
[Bug]: TypeError: __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> import towhee
>>>
>>>
>>> towhee.dc(["Hello, world."]) \
...       .text_embedding.data2vec() \
...       .show()

Cloning the repo: text-embedding/data2vec... Be patient and waiting printing 'Successfully'.
正克隆到 '/Users/binbin/.towhee/operators/text-embedding/data2vec/main'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 21 (delta 7), reused 0 (delta 0), pack-reused 0
接收对象中: 100% (21/21), 完成.
处理 delta 中: 100% (7/7), 完成.
Successfully clone the repo: text-embedding/data2vec.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 198, in __call__
    return self._func(*args, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 156, in wrapper
    return self.map(op)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/mixins/dag.py", line 11, in wrapper
    children = f(self, *arg, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 315, in map
    if hasattr(unary_op, 'is_stateful') and unary_op.is_stateful:
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/execution/stateful_execution.py", line 30, in is_stateful
    self.__check_init__()
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 93, in __check_init__
    self._op = op(self._name,
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/factory.py", line 61, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 162, in load_operator
    op = factory(function, arg, kws, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 141, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 127, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 172, in instance_operator
    return op(*arg, **kws) if kws is not None else op()
  File "/Users/binbin/.towhee/operators/text-embedding/data2vec/main/__init__.py", line 19, in data2vec
    return Data2VecText(model_name)
TypeError: __init__() takes 1 positional argument but 2 were given
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
https://towhee.io/text-embedding/data2vec
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): towhee 0.7.3.dev32 (models latest)
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@wxywb 
And for this operator, duplicate "transformer" exists too.

numpy
--
  | transformers>4.19.0
  | torch
  | transformers
  | towhee

Please have a look too.

Thanks.

**Comment by wxywb** [comment]
model_name argument has been added.

**Comment by binbinlv** [comment]
Fixed, so close it.
