### ISSUE TITLE
[Bug]: TypeError: forward() got an unexpected keyword argument 'labels'

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> towhee.dc(["Hello, world."]) \
...       .text_embedding.longformer(model_name="allenai/longformer-base-4096") \
...       .to_list()
Cloning the repo: text-embedding/longformer... Be patient and waiting printing 'Successfully'.
正克隆到 '/Users/binbin/.towhee/operators/text-embedding/longformer/main'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 55 (delta 26), reused 0 (delta 0), pack-reused 0
接收对象中: 100% (55/55), 8.00 KiB | 8.00 MiB/s, 完成.
处理 delta 中: 100% (26/26), 完成.
Successfully clone the repo: text-embedding/longformer.
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 694/694 [00:00<00:00, 253kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 570M/570M [03:14<00:00, 3.07MB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 878k/878k [00:01<00:00, 869kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 446k/446k [00:02<00:00, 194kB/s]
2022-07-21 20:36:09,833 - 4536303104 - longformer.py-longformer:53 - ERROR: Invalid input for the model: allenai/longformer-base-4096
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 198, in __call__
    return self._func(*args, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 156, in wrapper
    return self.map(op)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/mixins/dag.py", line 11, in wrapper
    children = f(self, *arg, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 336, in map
    return self._factory(result)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 268, in _factory
    iterable = list(iterable)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 333, in inner
    return unary_op(x)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/execution/base_execution.py", line 49, in __call__
    res = self._op(*arg, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/towhee/engine/operator_registry.py", line 200, in wrapper_call
    return old_call(self, *args, **kws)
  File "/Users/binbin/.towhee/operators/text-embedding/longformer/main/longformer.py", line 54, in __call__
    raise e
  File "/Users/binbin/.towhee/operators/text-embedding/longformer/main/longformer.py", line 51, in __call__
    outs = self.model(input_ids, attention_mask=attention_mask, labels=input_ids, output_hidden_states=True)
  File "/Users/binbin/towhee-test-env-3.8-0.7.3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'labels'
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
https://towhee.io/text-embedding/longformer

import towhee

towhee.dc(["Hello, world."]) \
      .text_embedding.longformer(model_name="allenai/longformer-base-4096") \
      .to_list()
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):towhee 0.7.3.dev32 (models latest)
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
@binbinlv Fixed by https://towhee.io/text-embedding/longformer.

**Comment by binbinlv** [comment]
Fixed, so close it.
```
>>> towhee.dc(["Hello, world."]) \
... .text_embedding.longformer(model_name="allenai/longformer-base-4096") \
... .to_list()
...
[array([[-9.2652783e-02,  1.0691583e-01,  2.1393728e-02, ...,
        -1.1902457e-01, -4.4368930e-02, -3.0839384e-02],
       [-2.2063413e-01,  1.5912297e-01, -3.9969780e-02, ...,
        -2.2453693e-01, -1.1905949e-01,  1.6556796e-01],
       [ 2.5020942e-02,  1.4908037e-01,  5.6840863e-02, ...,
        -2.3201987e-01, -1.3440126e-01,  1.2628004e-01],
       [ 4.9619213e-02,  1.0309624e-01,  1.7239302e-03, ...,
        -3.7346509e-01, -3.3070385e-02,  3.0279720e-01],
       [-1.0380307e-01,  1.0987856e-01, -3.2838434e-04, ...,
        -1.4799094e-01, -5.1974356e-02, -3.8651615e-02],
       [-7.7555940e-02, -3.5129488e-02,  2.2200590e-01, ...,
        -7.6010704e-02, -1.8499736e-01,  2.1959600e-01]], dtype=float32)]
```
