### ISSUE TITLE
[Bug]: Error "No module named 'torch" when importing towhee

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error "No module named 'torch" when import pipeline from towhee
```
>>> from towhee import pipeline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee0.8.0/towhee/__init__.py", line 20, in <module>
    from towhee.connectors import Connectors as connectors
  File "/Users/binbin/towhee0.8.0/towhee/connectors/__init__.py", line 15, in <module>
    from .ann_index import MilvusDB
  File "/Users/binbin/towhee0.8.0/towhee/connectors/ann_index/__init__.py", line 16, in <module>
    from .milvus import MilvusDB
  File "/Users/binbin/towhee0.8.0/towhee/connectors/ann_index/milvus.py", line 18, in <module>
    from towhee.functional.entity import Entity
  File "/Users/binbin/towhee0.8.0/towhee/functional/__init__.py", line 15, in <module>
    from .data_collection import DataCollection, DataFrame
  File "/Users/binbin/towhee0.8.0/towhee/functional/data_collection.py", line 17, in <module>
    from towhee.functional.mixins.dag import register_dag
  File "/Users/binbin/towhee0.8.0/towhee/functional/mixins/__init__.py", line 17, in <module>
    from .parallel import ParallelMixin
  File "/Users/binbin/towhee0.8.0/towhee/functional/mixins/parallel.py", line 20, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
1. install towhee and towhee.models (0.8.0) from testpypi:
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple towhee==0.8.0
pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple towhee.models==0.8.0

2. run:

from towhee import pipeline
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.8.0 from testpypi
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
Verified and fixed.
