### ISSUE TITLE
[Bug]: TypeError: 'torch._C.Node' object is not subscriptable

### ISSUE THREAD

**Issue by shifentencent** [towhee-io/towhee#2093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

do this example:
import towhee

towhee.glob('./teddy.jpg') \
      .image_decode() \
      .image_text_embedding.clip(model_name='clip_vit_b32', modality='image') \
      .show()

towhee.dc(["A teddybear on a skateboard in Times Square."]) \
      .image_text_embedding.clip(model_name='clip_vit_b32', modality='text') \
      .show()

### Expected Behavior

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 198, in __call__
    return self._func(*args, **kws)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 126, in wrapper
    return self.map(op)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 566, in map
    arg[0].__check_init__()
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/engine/factory.py", line 93, in __check_init__
    self._op = op(self._name,
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/engine/factory.py", line 61, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 162, in load_operator
    op = factory(function, arg, kws, tag)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 141, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 127, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 172, in instance_operator
    return op(*arg, **kws) if kws is not None else op()
  File "/Users/alphabeta/.towhee/operators/image-text-embedding/clip/main/clip.py", line 35, in __init__
    self.model = clip.create_model(model_name=model_name, pretrained=True, jit=True)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/models/clip/clip.py", line 658, in create_model
    patch_device(model, device)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/models/clip/clip_utils.py", line 208, in patch_device
    model.apply(patch_dev)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 668, in apply
    module.apply(fn)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 668, in apply
    module.apply(fn)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 669, in apply
    fn(self)
  File "/Users/alphabeta/anaconda3/lib/python3.8/site-packages/towhee/models/clip/clip_utils.py", line 205, in patch_dev
    if "value" in node.attributeNames() and str(node["value"]).startswith("cuda"):
TypeError: 'torch._C.Node' object is not subscriptable

### Steps To Reproduce

```markdown
see error
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):CentOS
- CPU/Memory:
- GPU:cpu
- Others:
```

**Comment by binbinlv** [comment]
@shifentencent Thanks for the issue.

May I know what the version of towhee and towhee.models you are using?

**Comment by binbinlv** [comment]
@wxywb 

Could you help to have a look at his issue?  Thanks.

/assign @wxywb 
/unassign

**Comment by wxywb** [comment]
Can I have your pytorch vision?
