### ISSUE TITLE
[Bug]: Value error when running operator "image_captioning.blip"

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#2131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Value error when running operator "image_captioning.blip"

ValueError: The following `model_kwargs` are not used by the model: ['encoder_hidden_states', 'encoder_attention_mask'] (note: typos in the generate arguments will also show up in this list)

### Expected Behavior

No error

### Steps To Reproduce

```markdown
https://towhee.io/image-captioning/blip


>>> import towhee
>>> towhee.glob('/home/zong/binbin/data/2021825-19039.jpg') \
...       .image_decode() \
...       .image_captioning.blip(model_name='blip_base') \
...       .show()
Cloning the repo: image-captioning/blip... Be patient and waiting printing 'Successfully'.
Cloning into '/home/zong/.towhee/operators/image-captioning/blip/main'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 36 (delta 8), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (36/36), done.
Successfully clone the repo: image-captioning/blip.
Collecting transformers>=4.15.0
  Downloading transformers-4.22.1-py3-none-any.whl (4.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 4.2 MB/s eta 0:00:00
Collecting pyyaml>=5.1
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Requirement already satisfied: requests in ./embed-milvus-3.8/lib/python3.8/site-packages (from transformers>=4.15.0) (2.28.1)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Requirement already satisfied: numpy>=1.17 in ./embed-milvus-3.8/lib/python3.8/site-packages (from transformers>=4.15.0) (1.23.3)
Collecting filelock
  Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
Collecting regex!=2019.12.17
  Downloading regex-2022.9.13-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (772 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.3/772.3 kB 24.5 MB/s eta 0:00:00
Collecting huggingface-hub<1.0,>=0.9.0
  Downloading huggingface_hub-0.9.1-py3-none-any.whl (120 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 120.7/120.7 kB 10.0 MB/s eta 0:00:00
Collecting tokenizers!=0.11.3,<0.13,>=0.11.1
  Downloading tokenizers-0.12.1-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 18.3 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in ./embed-milvus-3.8/lib/python3.8/site-packages (from transformers>=4.15.0) (4.64.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./embed-milvus-3.8/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.9.0->transformers>=4.15.0) (4.3.0)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./embed-milvus-3.8/lib/python3.8/site-packages (from requests->transformers>=4.15.0) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in ./embed-milvus-3.8/lib/python3.8/site-packages (from requests->transformers>=4.15.0) (2022.9.14)
Requirement already satisfied: charset-normalizer<3,>=2 in ./embed-milvus-3.8/lib/python3.8/site-packages (from requests->transformers>=4.15.0) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in ./embed-milvus-3.8/lib/python3.8/site-packages (from requests->transformers>=4.15.0) (3.4)
Installing collected packages: tokenizers, regex, pyyaml, pyparsing, filelock, packaging, huggingface-hub, transformers
Successfully installed filelock-3.8.0 huggingface-hub-0.9.1 packaging-21.3 pyparsing-3.0.9 pyyaml-6.0 regex-2022.9.13 tokenizers-0.12.1 transformers-4.22.1
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
Moving 0 files to the new cache system
0it [00:00, ?it/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 273kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28.0/28.0 [00:00<00:00, 12.8kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 570/570 [00:00<00:00, 273kB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.97G/1.97G [01:26<00:00, 24.5MB/s]
reshape position embedding from 196 to 576
load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 200, in __call__
    return self._func(*args, **kws)
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 142, in wrapper
    return self.map(op)
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/towhee/functional/mixins/dag.py", line 35, in wrapper
    children = f(self, *arg, **kws)
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 390, in map
    return self._factory(result)
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 295, in _factory
    iterable = list(iterable)
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 387, in inner
    return unary_op(x)
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/towhee/engine/execution/base_execution.py", line 50, in __call__
    res = self._op(*arg, **kws)
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/towhee/engine/operator_registry.py", line 201, in wrapper_call
    return old_call(self, *args, **kws)
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/towhee/types/arg.py", line 33, in wrapper
    return func(*new_args, **kwargs)
  File "/home/zong/.towhee/operators/image-captioning/blip/main/blip.py", line 53, in __call__
    vec = self._inference_from_image(img)
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/towhee/types/arg.py", line 33, in wrapper
    return func(*new_args, **kwargs)
  File "/home/zong/.towhee/operators/image-captioning/blip/main/blip.py", line 59, in _inference_from_image
    caption = self.model.generate(img, sample=False, num_beams=3, max_length=20, min_length=5)
  File "/home/zong/.towhee/operators/image-captioning/blip/main/models/blip.py", line 160, in generate
    outputs = self.text_decoder.generate(input_ids=input_ids,
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/transformers/generation_utils.py", line 1146, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/home/zong/binbin/embed-milvus-3.8/lib/python3.8/site-packages/transformers/generation_utils.py", line 861, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['encoder_hidden_states', 'encoder_attention_mask'] (note: typos in the generate arguments will also show up in this list)
```
```


### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): Towhee/models latest
- OS(Ubuntu or CentOS):Ubuntu
- CPU/Memory:
- GPU:
- Others:
```

**Comment by wxywb** [comment]
Its' due to transformers 4.22.1 add more strict parameters validation compared to 4.15.0. All **model_kwargs** in blip renamed to **kwargs** solved the problem.

**Comment by binbinlv** [comment]
OK，verified and fixed.
```
>>> import towhee
>>> towhee.glob['path']('/home/zong/binbin/data/2021825-19039.jpg') \
...       .image_decode['path', 'img']() \
...       .image_captioning.blip['img', 'text'](model_name='blip_base') \
...       .select['img', 'text']() \
...       .show()
reshape position embedding from 196 to 576
load checkpoint from https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_capfilt_large.pth
<IPython.core.display.HTML object>
```
