### ISSUE TITLE
[Bug]: TypeError: unsupported operand type(s) for *: 'NoneType' and 'float' for operator "video-decoder"

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#2234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float' for operator "video-decoder"

```
/github/home/.towhee/operators/video-decode/ffmpeg/main/video_decoder.py:42: AVDeprecationWarning: VideoStream.rate is deprecated as it is not always set; please use VideoStream.average_rate.
  nums = int(stream.rate * (end_time - start_time))
Traceback (most recent call last):
  File "/workspace/towhee_CI/hub_operator/testcases/test_video-text-embedding-clip4clip.py", line 3, in <module>
    towhee.dc(['/workspace/towhee_CI/hub_operator/dataset/test.mp4']) \
  File "/opt/conda/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 200, in __call__
    return self._func(*args, **kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 142, in wrapper
    return self.map(op)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/mixins/dag.py", line 35, in wrapper
    children = f(self, *arg, **kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 390, in map
    return self._factory(result)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 295, in _factory
    iterable = list(iterable)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 387, in inner
    return unary_op(x)
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/execution/base_execution.py", line 50, in __call__
    res = self._op(*arg, **kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/operator_registry.py", line 201, in wrapper_call
    return old_call(self, *args, **kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/hub/builtin/operators/runas_op.py", line 44, in __call__
    return self._func(*args, **kws)
  File "/workspace/towhee_CI/hub_operator/testcases/test_video-text-embedding-clip4clip.py", line 5, in <lambda>
    .runas_op(func=lambda x: [y for y in x]) \
  File "/workspace/towhee_CI/hub_operator/testcases/test_video-text-embedding-clip4clip.py", line 5, in <listcomp>
    .runas_op(func=lambda x: [y for y in x]) \
  File "/github/home/.towhee/operators/video-decode/ffmpeg/main/video_decoder.py", line 128, in __call__
    sample_function = self.get_sample(stream, duration)
  File "/github/home/.towhee/operators/video-decode/ffmpeg/main/video_decoder.py", line 42, in get_sample
    nums = int(stream.rate * (end_time - start_time))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
https://github.com/towhee-io/towhee/actions/runs/3328010266/jobs/5503498268
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.8.2.dev31 
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
AVDeprecationWarning: VideoStream.rate is deprecated as it is not always set; please use VideoStream.average_rate.
pyav lib change the `VideoStream.rate`   to the ` VideoStream.average_rate.`

**Comment by binbinlv** [comment]
From the latest test, this issue has not appeared and fixed. So close it.
