### ISSUE TITLE
[Bug]: Op "image-text-embedding/lightningdot" runs failed reporting "urllib.error.HTTPError: HTTP Error 409: Public access is not permitted on this storage account"

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#2262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Op "image-text-embedding/lightningdot" runs failed reporting "urllib.error.HTTPError: HTTP Error 409: Public access is not permitted on this storage account"
```
022-11-06 01:12:39.473582: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/workspace/towhee_CI/hub_operator/testcases/test_image-text-embedding-lightningdot.py", line 3, in <module>
    towhee.glob('/workspace/towhee_CI/hub_operator/dataset/test.jpg') \
  File "/opt/conda/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 200, in __call__
    return self._func(*args, **kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 142, in wrapper
    return self.map(op)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/mixins/dag.py", line 35, in wrapper
    children = f(self, *arg, **kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 368, in map
    if hasattr(unary_op, 'is_stateful') and unary_op.is_stateful:
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/execution/stateful_execution.py", line 30, in is_stateful
    self.__check_init__()
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/factory.py", line 97, in __check_init__
    self._op = op(self._name,
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/factory.py", line 64, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 166, in load_operator
    op = factory(function, arg, kws, tag)
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 144, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 130, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 176, in instance_operator
    return op(*arg, **kws) if kws is not None else op()
  File "/github/home/.towhee/operators/image-text-embedding/lightningdot/main/__init__.py", line 18, in lightningdot
    return LightningDOT(model_name, modality)
  File "/github/home/.towhee/operators/image-text-embedding/lightningdot/main/lightningdot.py", line 56, in __init__
    download_file(model_url, os.path.dirname(__file__) + '/data/model/')
  File "/github/home/.towhee/operators/image-text-embedding/lightningdot/main/utils.py", line 48, in download_file
    download_url(url, save_path, filename)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 146, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 94, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
  File "/opt/conda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/conda/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 409: Public access is not permitted on this storage account.
```

### Expected Behavior

No error

### Steps To Reproduce

```markdown
weekly:
https://github.com/towhee-io/towhee/actions/runs/3402235419/jobs/5657863504
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): Towhee latest
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
this error still exists in latest weekly:
https://github.com/towhee-io/towhee/actions/runs/3448758130/jobs/5756049941

```
Traceback (most recent call last):
  File "/workspace/towhee_CI/hub_operator/testcases/test_image-text-embedding-lightningdot.py", line 3, in <module>
    towhee.glob('/workspace/towhee_CI/hub_operator/dataset/test.jpg') \
  File "/opt/conda/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 200, in __call__
    return self._func(*args, **kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 142, in wrapper
    return self.map(op)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/mixins/dag.py", line 35, in wrapper
    children = f(self, *arg, **kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 368, in map
    if hasattr(unary_op, 'is_stateful') and unary_op.is_stateful:
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/execution/stateful_execution.py", line 30, in is_stateful
    self.__check_init__()
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/factory.py", line 97, in __check_init__
    self._op = op(self._name,
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/factory.py", line 64, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 166, in load_operator
    op = factory(function, arg, kws, tag)
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 144, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 130, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 176, in instance_operator
    return op(*arg, **kws) if kws is not None else op()
  File "/github/home/.towhee/operators/image-text-embedding/lightningdot/main/__init__.py", line 18, in lightningdot
    return LightningDOT(model_name, modality)
  File "/github/home/.towhee/operators/image-text-embedding/lightningdot/main/lightningdot.py", line 56, in __init__
    download_file(model_url, os.path.dirname(__file__) + '/data/model/')
  File "/github/home/.towhee/operators/image-text-embedding/lightningdot/main/utils.py", line 48, in download_file
    download_url(url, save_path, filename)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 146, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 94, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
  File "/opt/conda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/opt/conda/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 409: Public access is not permitted on this storage account.
```

**Comment by wxywb** [comment]
original pretrained weights links are no longer available. I will trace the problem and update the link when authors update their links.

**Comment by binbinlv** [comment]
Fixed and closed.
