### ISSUE TITLE
[Bug]: Error message of invalid output is not user friendly

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error message of invalid output is not user friendly.
for example, when executing
```
from towhee.dc2 import pipe
p = pipe.input('a').map('a', 'b', lambda x: x+1).output({1})
```
We will get error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/runtime/pipeline.py", line 112, in output
    run_pipe = RuntimePipeline(dag_dict)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 94, in __init__
    self._dag_repr = DAGRepr.from_dict(dag_dict)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/runtime/dag_repr.py", line 299, in from_dict
    DAGRepr.check_nodes(nodes)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/runtime/dag_repr.py", line 64, in check_nodes
    check_set(nodes[name].inputs, set(all_inputs[name]))
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/runtime/check_utils.py", line 46, in check_set
    inputs = set(inputs)
TypeError: unhashable type: 'set'
```

### Expected Behavior

More details to help user understand.
for example, output_scheme must be string or tuple, set is invalid.

### Steps To Reproduce

```markdown
from towhee.dc2 import pipe
p = pipe.input('a').map('a', 'b', lambda x: x+1).output({1})
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.8.2.dev78
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
@shiyu22
