### ISSUE TITLE
[Bug]: The use of concat in some scenarios raised no exception

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Scenario1: concat empty
```
import towhee
from towhee.dc2 import pipe, ops
pipe4 = towhee.pipe.input('a').map('a', 'b', lambda x: x + 1)
pipe5 = pipe4.concat().output('b')
pipe5(10).get()
```
It can run successfully just as the concat() doesn't exist. 
But if use concat() twice as follows: 
```
pipe4 = towhee.pipe.input('a').map('a', 'b', lambda x: x + 1)
pipe5 = pipe4.concat().concat().output('b')
```
An error will occur:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/runtime/pipeline.py", line 112, in output
    run_pipe = RuntimePipeline(dag_dict)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 94, in __init__
    self._dag_repr = DAGRepr.from_dict(dag_dict)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/runtime/dag_repr.py", line 299, in from_dict
    DAGRepr.check_nodes(nodes)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/runtime/dag_repr.py", line 62, in check_nodes
    all_inputs = DAGRepr.get_all_inputs(nodes, top_sort)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/runtime/dag_repr.py", line 109, in get_all_inputs
    pre_name = all_nodes.pop()
IndexError: pop from empty list
```

### Expected Behavior

All cause errors or permit the existence if concat().

### Steps To Reproduce

```markdown
#right:
import towhee
from towhee.dc2 import pipe, ops
pipe4 = towhee.pipe.input('a').map('a', 'b', lambda x: x + 1)
pipe5 = pipe4.concat().output('b')
pipe5(10).get()

#wrong:
pipe5 = pipe4.concat().concat().output('b')
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.8.2.dev78
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
Scenario2: 
When concatenating more than 1 same pipelines, the result is same with that executed as one pipeline.
for example,
```
import towhee
from towhee.dc2 import pipe, ops
pipe6 = towhee.pipe.input('a')
pipe7 = pipe6.map('a', 'b', lambda x: x + 1)
pipe8 = towhee.pipe.concat(pipe7, pipe7, pipe7).output('b')
pipe8(10).get()
```
Is it in design?

**Comment by junjiejiangjjj** [comment]
Can not call `concat` in this way : `towhee.pipe.concat`,  concat is not a classmethod.
in this way is right:
```python
pipe9 = pipe7.concat(pipe8).output('b', 'c')
