### ISSUE TITLE
[Bug]: Op 'image_captioning.expansionnet-v2' runs failed reporting 'ModuleNotFoundError: No module named 'transformers''

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ModuleNotFoundError: No module named 'transformers'.
details:
```
>>> import towhee
>>> 
>>> towhee.glob('/Users/zilliz/towhee_test/image.jpg') \
...       .image_decode() \
...       .image_captioning.expansionnet_v2(model_name='expansionnet_rf') \
...       .show()

Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 114, in load_operator_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/zilliz/.towhee/operators/image-captioning/expansionnet_v2/main/expansionnet_v2.py", line 24, in <module>
    from transformers import GPT2Tokenizer
ModuleNotFoundError: No module named 'transformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/hparam/hyperparameter.py", line 200, in __call__
    return self._func(*args, **kws)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 142, in wrapper
    return self.map(op)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/functional/mixins/dag.py", line 35, in wrapper
    children = f(self, *arg, **kws)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 368, in map
    if hasattr(unary_op, 'is_stateful') and unary_op.is_stateful:
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/engine/execution/stateful_execution.py", line 30, in is_stateful
    self.__check_init__()
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/engine/factory.py", line 97, in __check_init__
    self._op = op(self._name,
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/engine/factory.py", line 64, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 166, in load_operator
    op = factory(function, arg, kws, tag)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 144, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 127, in load_operator_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/zilliz/.towhee/operators/image-captioning/expansionnet_v2/main/__init__.py", line 15, in <module>
    from .expansionnet_v2 import ExpansionNetV2 
  File "/Users/zilliz/.towhee/operators/image-captioning/expansionnet_v2/main/expansionnet_v2.py", line 24, in <module>
    from transformers import GPT2Tokenizer
ModuleNotFoundError: No module named 'transformers'
```

### Expected Behavior

succeed

### Steps To Reproduce

Run readme in https://towhee.io/image-captioning/expansionnet-v2

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.8.2.dev83
- Towhee.models: 0.8.2.dev76
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
This op also failed in the latest weekly tests. 
https://github.com/towhee-io/towhee/actions/runs/3459855033/jobs/5775721499
![016aeb1b-8817-4e7d-a3b5-0c42f2f14618](https://user-images.githubusercontent.com/109071306/202652637-9b6c2b22-3380-46fd-b74f-5c6f5d26e99c.jpeg)

**Comment by NicoYuan1986** [comment]
Still wrong:
https://github.com/towhee-io/towhee/actions/runs/3501137896/jobs/5864473142

**Comment by binbinlv** [comment]
Retry this op, it reports the following error:
```
Requirement already satisfied: wcwidth>=0.2.5 in /Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages (from ftfy) (0.2.5)
Installing collected packages: ftfy
Successfully installed ftfy-6.1.1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/hparam/hyperparameter.py", line 200, in __call__
    return self._func(*args, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 142, in wrapper
    return self.map(op)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/functional/mixins/dag.py", line 35, in wrapper
    children = f(self, *arg, **kws)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 390, in map
    return self._factory(result)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 295, in _factory
    iterable = list(iterable)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 387, in inner
    return unary_op(x)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/engine/execution/base_execution.py", line 30, in __call__
    self.__check_init__()
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/engine/factory.py", line 97, in __check_init__
    self._op = op(self._name,
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/engine/factory.py", line 64, in op
    return loader.load_operator(operator_src, arg, kwargs, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 166, in load_operator
    op = factory(function, arg, kws, tag)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 144, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 130, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 176, in instance_operator
    return op(*arg, **kws) if kws is not None else op()
  File "/Users/binbin/.towhee/operators/image-captioning/expansionnet_v2/main/__init__.py", line 18, in expansionnet_v2
    return ExpansionNetV2(model_name)
  File "/Users/binbin/.towhee/operators/image-captioning/expansionnet_v2/main/expansionnet_v2.py", line 85, in __init__
    cfg = self.model._configs()[model_name]
  File "/Users/binbin/towhee-test-env-3.8-0.9.0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1265, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'End_ExpansionNet_v2' object has no attribute '_configs'
```

**Comment by wxywb** [comment]
Hi, I have fixed it, please try it again.

**Comment by NicoYuan1986** [comment]
LInk: #2311 
And the error has been fixed.
![image](https://user-images.githubusercontent.com/109071306/204725563-0d98fc45-230e-4ce9-95af-423285da0476.png)
