### ISSUE TITLE
[Bug]: The error message of downloadS3 with nonexistent S3-path is not user friendly

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2296]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When downloadS3 with nonexistent S3-path, error message is not user friendly.
For example,
```
% towhee downloadS3 -pl ./ -pb abc/lpl

Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee3.9/bin/towhee", line 8, in <module>
    sys.exit(main())
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/command/cmdline.py", line 54, in main
    main_body(sys.argv[1:])
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/command/cmdline.py", line 50, in main_body
    actions[parsed.action](parsed)()
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/command/execute.py", line 203, in __call__
    if not s3.download_files(self._args.pathbucket, self._args.pathlocal):
  File "/Users/zilliz/virtual-environment/towhee3.9/lib/python3.9/site-packages/towhee/command/s3.py", line 159, in download_files
    list_content = self.s3.list_objects_v2(Bucket=self.bucket_name, Prefix=path_prefix)['Contents']
KeyError: 'Contents'
```

### Expected Behavior

When lsS3 with nonexistent path, it will return
```
path abc/lpl is not exist
[]
```
I suggest the 2 command should be consistent.

### Steps To Reproduce

```markdown
towhee downloadS3 -pl ./ -pb abc/lpl
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.8.2.dev83
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by zhujiming** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/18031320/202955556-e2c3c50f-23bb-4bfb-9f50-64ac05dd1c01.png">
it was fixed #2297
