### ISSUE TITLE
[Bug]:  ERROR: module 'towhee.operator.image_decoder' has no attribute 'image_decoder'

### ISSUE THREAD

**Issue by holmofy** [towhee-io/towhee#2335]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

my app depenency: 
```requirements.txt
towhee==0.8.1
towhee.models==0.8.1
uvicorn==0.18.3
fastapi==0.80.0
numpy==1.21.6
python-multipart==0.0.5
sentence_transformers==2.2.2
ruamel.yaml==0.17.21
opencv-python==4.6.0.66
```

resnet50 model
```python
class Resnet50:
    def __init__(self):
        self.embedding_pipeline = pipeline('towhee/image-embedding-resnet50')

    def resnet50_extract_feat(self, img_path):
        feat = self.embedding_pipeline(img_path)
        return feat.tolist()
```

It is normal on the Mac, but it does not work on Linux. my linux :
```bash
Linux ai 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

output log
```bash
apollo-ai_1  | INFO:     172.21.0.1:46782 - "POST /text/upload?text=hello%20world HTTP/1.1" 200 OK
apollo-ai_1  | huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
apollo-ai_1  | To disable this warning, you can either:
apollo-ai_1  | 	- Avoid using `tokenizers` before the fork if possible
apollo-ai_1  | 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
apollo-ai_1  | huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
apollo-ai_1  | To disable this warning, you can either:
apollo-ai_1  | 	- Avoid using `tokenizers` before the fork if possible
apollo-ai_1  | 	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
apollo-ai_1  | 2022-12-10 17:05:52,708 - 140003384489728 - thread_pool_task_executor.py-thread_pool_task_executor:75 - ERROR: Traceback (most recent call last):
apollo-ai_1  |   File "/usr/local/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 114, in load_operator_from_path
apollo-ai_1  |     spec.loader.exec_module(module)
apollo-ai_1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
apollo-ai_1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
apollo-ai_1  |   File "/root/.towhee/operators/towhee/image_decoder/main/image_decoder.py", line 5, in <module>
apollo-ai_1  |     import cv2
apollo-ai_1  |   File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 181, in <module>
apollo-ai_1  |     bootstrap()
apollo-ai_1  |   File "/usr/local/lib/python3.9/site-packages/cv2/__init__.py", line 153, in bootstrap
apollo-ai_1  |     native_module = importlib.import_module("cv2")
apollo-ai_1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
apollo-ai_1  |     return _bootstrap._gcd_import(name[level:], package, level)
apollo-ai_1  | ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
apollo-ai_1  | 
apollo-ai_1  | During handling of the above exception, another exception occurred:
apollo-ai_1  | 
apollo-ai_1  | Traceback (most recent call last):
apollo-ai_1  |   File "/usr/local/lib/python3.9/site-packages/towhee/engine/thread_pool_task_executor.py", line 68, in execute
apollo-ai_1  |     op = self._op_pool.acquire_op(runner.hub_op_id, runner.op_args, runner.tag)
apollo-ai_1  |   File "/usr/local/lib/python3.9/site-packages/towhee/engine/operator_pool.py", line 102, in acquire_op
apollo-ai_1  |     op = self._op_loader.load_operator(hub_op_id, [], op_args, tag)
apollo-ai_1  |   File "/usr/local/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 166, in load_operator
apollo-ai_1  |     op = factory(function, arg, kws, tag)
apollo-ai_1  |   File "/usr/local/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 144, in load_operator_from_cache
apollo-ai_1  |     return self.load_operator_from_path(path, arg, kws)
apollo-ai_1  |   File "/usr/local/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 128, in load_operator_from_path
apollo-ai_1  |     op = getattr(module, fname)
apollo-ai_1  | AttributeError: module 'towhee.operator.image_decoder' has no attribute 'image_decoder'
apollo-ai_1  | 
apollo-ai_1  | 2022-12-10 17:05:52,708 - 140003384489728 - thread_pool_task_executor.py-thread_pool_task_executor:76 - ERROR: module 'towhee.operator.image_decoder' has no attribute 'image_decoder'
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.8.1
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 1 Core 2G memory
- GPU: none
- Others:
```

**Comment by junjiejiangjjj** [comment]
It seems import cv2 failed, try this: https://stackoverflow.com/questions/62786028/importerror-libgthread-2-0-so-0-cannot-open-shared-object-file-no-such-file-o
