### ISSUE TITLE
[Bug]: AttributeError: 'TimmImage' object has no attribute 'input_schema'

### ISSUE THREAD

**Issue by lvmnn** [towhee-io/towhee#2355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There was an error building the image using the triton script

![image](https://user-images.githubusercontent.com/92595690/209535054-6b809c04-33da-4434-8d78-12ed0a102ba5.png)
Successfully clone the repo: image-embedding/timm.
Traceback (most recent call last):
  File "/usr/local/bin/triton_builder", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/towhee/serve/triton/builder.py", line 208, in main
    if not Builder(dag, model_root).build():
  File "/usr/local/lib/python3.8/dist-packages/towhee/serve/triton/builder.py", line 194, in build
    if not self.load():
  File "/usr/local/lib/python3.8/dist-packages/towhee/serve/triton/builder.py", line 179, in load
    config = self._create_node_config(node_id, node)
  File "/usr/local/lib/python3.8/dist-packages/towhee/serve/triton/builder.py", line 149, in _create_node_config
    return self._pyop_config(op, node_id, node)
  File "/usr/local/lib/python3.8/dist-packages/towhee/serve/triton/builder.py", line 117, in _pyop_config
    converter = PyOpToTriton(op, self._model_root, model_name,
  File "/usr/local/lib/python3.8/dist-packages/towhee/serve/triton/to_triton_models.py", line 146, in __init__
    super().__init__(op, model_root, model_name, op_config)
  File "/usr/local/lib/python3.8/dist-packages/towhee/serve/triton/to_triton_models.py", line 91, in __init__
    self._inputs = TritonModelConfigBuilder.get_input_schema(self._obj.input_schema())
AttributeError: 'TimmImage' object has no attribute 'input_schema'

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.9.0
- OS(Ubuntu or CentOS):Ubuntu
- CPU/Memory:
- GPU:
- Others:
```

**Comment by shiyu22** [comment]
@lvmnn Are you running `image_embedding.timm` operator with triton? Can you show the code?

**Comment by lvmnn** [comment]
> @lvmnn Are you running `image_embedding.timm` operator with triton? Can you show the code?

I did it according to this. serve/triton/readme.md

**Comment by jaelgu** [comment]
@lvmnn Can you share exact code & towhee version?

**Comment by shiyu22** [comment]
I think the issue is that the latest `timm` operator does not work according to serve/triton/readme.md, we will update the documentation for the latest dc2, please stay tuned with 0.9.1.

**Comment by lvmnn** [comment]
> I think the issue is that the latest `timm` operator does not work according to serve/triton/readme.md, we will update the documentation for the latest dc2, please stay tuned with 0.9.1.

ok, Are there any examples or other documentation available about triton?
