### ISSUE TITLE
[Bug]: [Weekly]The readme file of some operators need modified

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The readme file of some operators need modified.
```
2023-02-08T15:32:14.4513770Z 2023-02-08 15:32:14.450 | DEBUG    | __main__:execute_ops:163 - Running extracted readme for /workspace/towhee_CI/hub_operator/text-embedding-transformers
2023-02-08T15:32:14.4845393Z   File "/workspace/towhee_CI/hub_operator/testcases/test_text-embedding-transformers.py", line 21
2023-02-08T15:32:14.4846881Z     ! python -m pip install datasets evaluate scikit-learn
2023-02-08T15:32:14.4847825Z     ^
2023-02-08T15:32:14.4848628Z SyntaxError: invalid syntax
2023-02-08T15:32:14.4882759Z 2023-02-08 15:32:14.487 | ERROR    | __main__:execute_ops:167 - Fail to run readme for 9: operator https://towhee.io/text-embedding/transformers
```

### Expected Behavior

pass

### Steps To Reproduce

```markdown
https://github.com/towhee-io/towhee/actions/runs/4088900552/jobs/7126498094
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
In our test script, we get the codes and write it into a python file by finding ‘```Python’
![image](https://user-images.githubusercontent.com/109071306/217749760-454a8973-3824-4a8e-9d86-6c117f638e67.png)

So some changes should be made to cooperate with our tests. for example, delete the 'python' tag when it's not a python sentence.
https://towhee.io/text-embedding/transformers
![image](https://user-images.githubusercontent.com/109071306/217750336-bed78545-3df3-412c-9d87-9c6761450b2d.png)
Need your help. @jaelgu

**Comment by NicoYuan1986** [comment]
Same situation: https://towhee.io/image-embedding/isc

**Comment by NicoYuan1986** [comment]
Another: https://towhee.io/action-classification/timesformer/src/branch/main/requirements.txt
```
2023-02-08T16:10:23.9961383Z 2023-02-08 16:10:23.994 | DEBUG    | __main__:execute_ops:163 - Running extracted readme for /workspace/towhee_CI/hub_operator/action-classification-timesformer
2023-02-08T16:10:26.7976785Z Cloning into '/github/home/.towhee/operators/action-classification/timesformer/main'...
2023-02-08T16:10:29.9418849Z ERROR: Invalid requirement: '# towhee.models>=0.7.0'
2023-02-08T16:10:30.0263236Z Traceback (most recent call last):
2023-02-08T16:10:30.0266526Z   File "/workspace/towhee_CI/hub_operator/testcases/test_action-classification-timesformer.py", line 4, in <module>
2023-02-08T16:10:30.0267853Z     pipe.input('path')
2023-02-08T16:10:30.0269146Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/pipeline.py", line 113, in output
2023-02-08T16:10:30.0270082Z     run_pipe.preload()
2023-02-08T16:10:30.0271426Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 102, in preload
2023-02-08T16:10:30.0272683Z     _ = Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
2023-02-08T16:10:30.0274217Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 46, in __init__
2023-02-08T16:10:30.0275184Z     self.initialize()
2023-02-08T16:10:30.0276473Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 56, in initialize
2023-02-08T16:10:30.0277457Z     raise RuntimeError(node.err_msg)
2023-02-08T16:10:30.0282115Z RuntimeError: Node-action-classification/timesformer runs failed, error msg: Create action-classification/timesformer operator action-classification/timesformer:main with args None and kws {'model_name': 'timesformer_k400_8x224'} failed, err: Command '['/opt/conda/bin/python3', '-m', 'pip', 'install', '# towhee.models>=0.7.0']' returned non-zero exit status 1., Traceback (most recent call last):
2023-02-08T16:10:30.0285199Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 81, in initialize
2023-02-08T16:10:30.0286200Z     self._op = self._op_pool.acquire_op(
2023-02-08T16:10:30.0287652Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
2023-02-08T16:10:30.0288844Z     op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
2023-02-08T16:10:30.0290445Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 153, in load_operator
2023-02-08T16:10:30.0291585Z     op = factory(function, arg, kws, tag)
2023-02-08T16:10:30.0293137Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 132, in load_operator_from_cache
2023-02-08T16:10:30.0294322Z     return self.load_operator_from_path(path, arg, kws)
2023-02-08T16:10:30.0295896Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 95, in load_operator_from_path
2023-02-08T16:10:30.0297420Z     subprocess.check_call([sys.executable, '-m', 'pip', 'install', req])
2023-02-08T16:10:30.0298476Z   File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
2023-02-08T16:10:30.0299378Z     raise CalledProcessError(retcode, cmd)
2023-02-08T16:10:30.0301078Z subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-m', 'pip', 'install', '# towhee.models>=0.7.0']' returned non-zero exit status 1.
2023-02-08T16:10:30.0301954Z 
2023-02-08T16:10:30.3475037Z 2023-02-08 16:10:30.345 | ERROR    | __main__:execute_ops:167 - Fail to run readme for 29: operator https://towhee.io/action-classification/timesformer
```
I think we can delete the '# ' for the convenience of automated weekly testing.
![image](https://user-images.githubusercontent.com/109071306/217757928-e817c0d2-5c01-4d5f-b01d-59ed12ac5b06.png)
The requirements will be directly installed according to the script.
![image](https://user-images.githubusercontent.com/109071306/217758479-905c756e-db47-4d6b-8702-afc36abce749.png)

**Comment by jaelgu** [comment]
> https://towhee.io/text-embedding/transformers

This needs to be changed. We added some code blocks in op README for purpose rather than example usage of op (eg. fine-tune). I suggest to just check and run the first python block in README (make sure it uses `pipe.input` instead of `dc`).

**Comment by NicoYuan1986** [comment]
> > https://towhee.io/text-embedding/transformers
> 
> This needs to be changed. We added some code blocks in op README for purpose rather than example usage of op (eg. fine-tune). I suggest to just check and run the first python block in README (make sure it uses `pipe.input` instead of `dc`).

OK. I'll modify the test script.

**Comment by NicoYuan1986** [comment]
Fixed.
