### ISSUE TITLE
[Bug]: [Weekly]The model timm's running failed with an ImportError

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The model timm's running failed with an ImportError.
1. link: https://github.com/towhee-io/towhee/actions/runs/4088900552/jobs/7126498094#step:5:8610
2. operator https://towhee.io/image-embedding/timm
3. error message:
```
2023-02-08T16:08:06.3311719Z 2023-02-08 16:08:06.329 | DEBUG    | __main__:execute_ops:163 - Running extracted readme for /workspace/towhee_CI/hub_operator/image-embedding-timm
2023-02-08T16:08:08.8386021Z Cloning into '/github/home/.towhee/operators/image-embedding/timm/main'...
2023-02-08T16:08:12.9530068Z Traceback (most recent call last):
2023-02-08T16:08:12.9531964Z   File "/workspace/towhee_CI/hub_operator/testcases/test_image-embedding-timm.py", line 4, in <module>
2023-02-08T16:08:12.9533142Z     pipe.input('path')
2023-02-08T16:08:12.9534441Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/pipeline.py", line 113, in output
2023-02-08T16:08:12.9535378Z     run_pipe.preload()
2023-02-08T16:08:12.9536647Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 102, in preload
2023-02-08T16:08:12.9537918Z     _ = Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
2023-02-08T16:08:12.9539461Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 46, in __init__
2023-02-08T16:08:12.9540386Z     self.initialize()
2023-02-08T16:08:12.9541684Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 56, in initialize
2023-02-08T16:08:12.9542730Z     raise RuntimeError(node.err_msg)
2023-02-08T16:08:12.9545781Z RuntimeError: Node-image-embedding/timm runs failed, error msg: Create image-embedding/timm operator image-embedding/timm:main with args None and kws {'model_name': 'resnet50'} failed, err: cannot import name 'get_pretrained_cfg' from 'timm.models' (/opt/conda/lib/python3.8/site-packages/timm/models/__init__.py), Traceback (most recent call last):
2023-02-08T16:08:12.9548465Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 102, in load_operator_from_path
2023-02-08T16:08:12.9549564Z     spec.loader.exec_module(module)
2023-02-08T16:08:12.9550475Z   File "<frozen importlib._bootstrap_external>", line 839, in exec_module
2023-02-08T16:08:12.9551493Z   File "<frozen importlib._bootstrap_external>", line 975, in get_code
2023-02-08T16:08:12.9552453Z   File "<frozen importlib._bootstrap_external>", line 1032, in get_data
2023-02-08T16:08:12.9554017Z FileNotFoundError: [Errno 2] No such file or directory: '/github/home/.towhee/operators/image-embedding/timm/main/timm.py'
2023-02-08T16:08:12.9555557Z 
2023-02-08T16:08:12.9556037Z During handling of the above exception, another exception occurred:
2023-02-08T16:08:12.9556886Z 
2023-02-08T16:08:12.9557216Z Traceback (most recent call last):
2023-02-08T16:08:12.9558535Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 81, in initialize
2023-02-08T16:08:12.9559527Z     self._op = self._op_pool.acquire_op(
2023-02-08T16:08:12.9560960Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
2023-02-08T16:08:12.9562146Z     op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
2023-02-08T16:08:12.9563737Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 153, in load_operator
2023-02-08T16:08:12.9564803Z     op = factory(function, arg, kws, tag)
2023-02-08T16:08:12.9566333Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 132, in load_operator_from_cache
2023-02-08T16:08:12.9567505Z     return self.load_operator_from_path(path, arg, kws)
2023-02-08T16:08:12.9569086Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 115, in load_operator_from_path
2023-02-08T16:08:12.9570181Z     spec.loader.exec_module(module)
2023-02-08T16:08:12.9571047Z   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2023-02-08T16:08:12.9572075Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2023-02-08T16:08:12.9573493Z   File "/github/home/.towhee/operators/image-embedding/timm/main/__init__.py", line 15, in <module>
2023-02-08T16:08:12.9574453Z     from .timm_image import TimmImage
2023-02-08T16:08:12.9575740Z   File "/github/home/.towhee/operators/image-embedding/timm/main/timm_image.py", line 35, in <module>
2023-02-08T16:08:12.9576817Z     from timm.models import create_model, get_pretrained_cfg
2023-02-08T16:08:12.9578449Z ImportError: cannot import name 'get_pretrained_cfg' from 'timm.models' (/opt/conda/lib/python3.8/site-packages/timm/models/__init__.py)
2023-02-08T16:08:12.9579276Z 
2023-02-08T16:08:13.1555976Z 2023-02-08 16:08:13.154 | ERROR    | __main__:execute_ops:167 - Fail to run readme for 25: operator https://towhee.io/image-embedding/timm
```

### Expected Behavior

pass

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
Can you help look at the error? @jaelgu  @filip-halt

**Comment by jaelgu** [comment]
@NicoYuan1986 Updated timm version in op requirement. Please re-check.

**Comment by NicoYuan1986** [comment]
Fixed.
