### ISSUE TITLE
[Bug]: [Weekly]Some operators failed reporting 'Torch not compiled with CUDA enabled'

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Some operators failed reporting 'Torch not compiled with CUDA enabled'.
1. link: https://github.com/towhee-io/towhee/actions/runs/4088900552/jobs/7126498094#step:5:8610
2.  operator https://towhee.io/video-text-embedding/clip4clip
3. error message:
```
2023-02-08T16:20:40.8695357Z 2023-02-08 16:20:40.868 | DEBUG    | __main__:execute_ops:163 - Running extracted readme for /workspace/towhee_CI/hub_operator/video-text-embedding-clip4clip
2023-02-08T16:20:43.7598247Z Cloning into '/github/home/.towhee/operators/video-text-embedding/clip4clip/main'...
2023-02-08T16:22:23.0863297Z Traceback (most recent call last):
2023-02-08T16:22:23.0869729Z   File "/workspace/towhee_CI/hub_operator/testcases/test_video-text-embedding-clip4clip.py", line 4, in <module>
2023-02-08T16:22:23.0871021Z     pipe.input('text') \
2023-02-08T16:22:23.0872314Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/pipeline.py", line 113, in output
2023-02-08T16:22:23.0873233Z     run_pipe.preload()
2023-02-08T16:22:23.0874562Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 102, in preload
2023-02-08T16:22:23.0875866Z     _ = Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
2023-02-08T16:22:23.0877415Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 46, in __init__
2023-02-08T16:22:23.0878348Z     self.initialize()
2023-02-08T16:22:23.0879621Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 56, in initialize
2023-02-08T16:22:23.0880599Z     raise RuntimeError(node.err_msg)
2023-02-08T16:22:23.0883353Z RuntimeError: Node-video-text-embedding/clip4clip runs failed, error msg: Create video-text-embedding/clip4clip operator video-text-embedding/clip4clip:main with args None and kws {'model_name': 'clip_vit_b32', 'modality': 'text', 'device': 'cuda:1'} failed, err: Torch not compiled with CUDA enabled, Traceback (most recent call last):
2023-02-08T16:22:23.0885794Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 81, in initialize
2023-02-08T16:22:23.0886782Z     self._op = self._op_pool.acquire_op(
2023-02-08T16:22:23.0888211Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
2023-02-08T16:22:23.0889423Z     op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
2023-02-08T16:22:23.0890987Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 153, in load_operator
2023-02-08T16:22:23.0892048Z     op = factory(function, arg, kws, tag)
2023-02-08T16:22:23.0893597Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 132, in load_operator_from_cache
2023-02-08T16:22:23.0894793Z     return self.load_operator_from_path(path, arg, kws)
2023-02-08T16:22:23.0896367Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 118, in load_operator_from_path
2023-02-08T16:22:23.0898439Z     return self.instance_operator(op, arg, kws) if op is not None else None
2023-02-08T16:22:23.0900074Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 161, in instance_operator
2023-02-08T16:22:23.0901222Z     return op(*arg, **kws) if kws is not None else op(*arg)
2023-02-08T16:22:23.0902676Z   File "/github/home/.towhee/operators/video-text-embedding/clip4clip/main/__init__.py", line 19, in clip4clip
2023-02-08T16:22:23.0903914Z     return CLIP4Clip(model_name, modality, **kwargs)
2023-02-08T16:22:23.0905372Z   File "/github/home/.towhee/operators/video-text-embedding/clip4clip/main/clip4clip.py", line 45, in __init__
2023-02-08T16:22:23.0906562Z     self.model = clip4clip.create_model(model_name=model_name,
2023-02-08T16:22:23.0908049Z   File "/opt/conda/lib/python3.8/site-packages/towhee/models/clip4clip/clip4clip.py", line 210, in create_model
2023-02-08T16:22:23.0908983Z     model.to(device)
2023-02-08T16:22:23.0910170Z   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 987, in to
2023-02-08T16:22:23.0911088Z     return self._apply(convert)
2023-02-08T16:22:23.0912321Z   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
2023-02-08T16:22:23.0913204Z     module._apply(fn)
2023-02-08T16:22:23.0914397Z   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
2023-02-08T16:22:23.0915238Z     module._apply(fn)
2023-02-08T16:22:23.0916404Z   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 639, in _apply
2023-02-08T16:22:23.0917231Z     module._apply(fn)
2023-02-08T16:22:23.0918397Z   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 662, in _apply
2023-02-08T16:22:23.0919284Z     param_applied = fn(param)
2023-02-08T16:22:23.0920535Z   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 985, in convert
2023-02-08T16:22:23.0921746Z     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
2023-02-08T16:22:23.0923183Z   File "/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py", line 221, in _lazy_init
2023-02-08T16:22:23.0924246Z     raise AssertionError("Torch not compiled with CUDA enabled")
2023-02-08T16:22:23.0925186Z AssertionError: Torch not compiled with CUDA enabled
2023-02-08T16:22:23.0925713Z 
2023-02-08T16:22:23.3111063Z 2023-02-08 16:22:23.309 | ERROR    | __main__:execute_ops:167 - Fail to run readme for 37: operator https://towhee.io/video-text-embedding/clip4clip
```

### Expected Behavior

pass

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
Can you look at the error? @zc277584121 
Or do we need to add any configuration to the script?

**Comment by NicoYuan1986** [comment]
Same error: https://towhee.io/video-text-embedding/drl

**Comment by NicoYuan1986** [comment]
I have reinstall torch(1.13.1 fit for CUDA 11.7)

**Comment by binbinlv** [comment]
@NicoYuan1986 
any update here?
