### ISSUE TITLE
[Bug]: [Weekly]The operator 'image-text-embedding/blip' failed reporting 'name 'logging' is not defined'

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The operator 'image-text-embedding/blip' failed reporting 'name 'logging' is not defined'.

1. weekly link: https://github.com/towhee-io/towhee/actions/runs/4088900552/jobs/7126498094#step:5:8610
2. failed operator: https://towhee.io/image-text-embedding/blip
3. error message:
```
2023-02-08T16:43:05.6035132Z 2023-02-08 16:43:05.602 | DEBUG    | __main__:execute_ops:163 - Running extracted readme for /workspace/towhee_CI/hub_operator/image-text-embedding-blip
2023-02-08T16:43:08.3920607Z Cloning into '/github/home/.towhee/operators/image-text-embedding/blip/main'...
2023-02-08T16:43:11.8904955Z 2023-02-08 16:43:11.889776: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
2023-02-08T16:43:11.8906844Z To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-08T16:43:12.0086421Z 2023-02-08 16:43:12.007728: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-08T16:43:12.0113023Z 2023-02-08 16:43:12.010948: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-08T16:43:12.0115573Z 2023-02-08 16:43:12.010963: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-08T16:43:12.6074435Z 2023-02-08 16:43:12.606479: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-08T16:43:12.6077874Z 2023-02-08 16:43:12.606524: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-08T16:43:12.6080967Z 2023-02-08 16:43:12.606530: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-02-08T16:43:13.6575142Z Traceback (most recent call last):
2023-02-08T16:43:13.6577064Z   File "/workspace/towhee_CI/hub_operator/testcases/test_image-text-embedding-blip.py", line 4, in <module>
2023-02-08T16:43:13.6578235Z     pipe.input('url')
2023-02-08T16:43:13.6579501Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/pipeline.py", line 113, in output
2023-02-08T16:43:13.6580433Z     run_pipe.preload()
2023-02-08T16:43:13.6581713Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 102, in preload
2023-02-08T16:43:13.6582963Z     _ = Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
2023-02-08T16:43:13.6584763Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 46, in __init__
2023-02-08T16:43:13.6585674Z     self.initialize()
2023-02-08T16:43:13.6587608Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 56, in initialize
2023-02-08T16:43:13.6588884Z     raise RuntimeError(node.err_msg)
2023-02-08T16:43:13.6591381Z RuntimeError: Node-image-text-embedding/blip runs failed, error msg: Create image-text-embedding/blip operator image-text-embedding/blip:main with args None and kws {'model_name': 'blip_itm_base', 'modality': 'image'} failed, err: name 'logging' is not defined, Traceback (most recent call last):
2023-02-08T16:43:13.6593893Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 102, in load_operator_from_path
2023-02-08T16:43:13.6595004Z     spec.loader.exec_module(module)
2023-02-08T16:43:13.6595907Z   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2023-02-08T16:43:13.6596924Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2023-02-08T16:43:13.6598363Z   File "/github/home/.towhee/operators/image-text-embedding/blip/main/blip.py", line 27, in <module>
2023-02-08T16:43:13.6599528Z     log = logging.getLogger('run_op')
2023-02-08T16:43:13.6600460Z NameError: name 'logging' is not defined
2023-02-08T16:43:13.6600922Z 
2023-02-08T16:43:13.6601404Z During handling of the above exception, another exception occurred:
2023-02-08T16:43:13.6601983Z 
2023-02-08T16:43:13.6602282Z Traceback (most recent call last):
2023-02-08T16:43:13.6603573Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 81, in initialize
2023-02-08T16:43:13.6604548Z     self._op = self._op_pool.acquire_op(
2023-02-08T16:43:13.6605959Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
2023-02-08T16:43:13.6607167Z     op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
2023-02-08T16:43:13.6608731Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 153, in load_operator
2023-02-08T16:43:13.6609807Z     op = factory(function, arg, kws, tag)
2023-02-08T16:43:13.6611299Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 132, in load_operator_from_cache
2023-02-08T16:43:13.6612498Z     return self.load_operator_from_path(path, arg, kws)
2023-02-08T16:43:13.6614073Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 115, in load_operator_from_path
2023-02-08T16:43:13.6615145Z     spec.loader.exec_module(module)
2023-02-08T16:43:13.6615996Z   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2023-02-08T16:43:13.6617002Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2023-02-08T16:43:13.6618460Z   File "/github/home/.towhee/operators/image-text-embedding/blip/main/__init__.py", line 15, in <module>
2023-02-08T16:43:13.6619381Z     from .blip import Blip
2023-02-08T16:43:13.6620649Z   File "/github/home/.towhee/operators/image-text-embedding/blip/main/blip.py", line 27, in <module>
2023-02-08T16:43:13.6621761Z     log = logging.getLogger('run_op')
2023-02-08T16:43:13.6622678Z NameError: name 'logging' is not defined
2023-02-08T16:43:13.6623127Z 
2023-02-08T16:43:14.1008655Z 2023-02-08 16:43:14.099 | ERROR    | __main__:execute_ops:167 - Fail to run readme for 54: operator https://towhee.io/image-text-embedding/blip
```

### Expected Behavior

pass

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
Can you help look at the error? @wxywb  Thanks a lot!

**Comment by NicoYuan1986** [comment]
Fixed.
