### ISSUE TITLE
[Bug]: [Weekly]The requirements text of transformers need modification

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/towhee-io/towhee/actions/runs/4088900552/jobs/7126498094
The requirements text of transformers need modification.
```
2023-02-08T16:10:23.9961383Z 2023-02-08 16:10:23.994 | DEBUG    | __main__:execute_ops:163 - Running extracted readme for /workspace/towhee_CI/hub_operator/action-classification-timesformer
2023-02-08T16:10:26.7976785Z Cloning into '/github/home/.towhee/operators/action-classification/timesformer/main'...
2023-02-08T16:10:29.9418849Z ERROR: Invalid requirement: '# towhee.models>=0.7.0'
2023-02-08T16:10:30.0263236Z Traceback (most recent call last):
2023-02-08T16:10:30.0266526Z   File "/workspace/towhee_CI/hub_operator/testcases/test_action-classification-timesformer.py", line 4, in <module>
2023-02-08T16:10:30.0267853Z     pipe.input('path')
2023-02-08T16:10:30.0269146Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/pipeline.py", line 113, in output
2023-02-08T16:10:30.0270082Z     run_pipe.preload()
2023-02-08T16:10:30.0271426Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 102, in preload
2023-02-08T16:10:30.0272683Z     _ = Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
2023-02-08T16:10:30.0274217Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 46, in __init__
2023-02-08T16:10:30.0275184Z     self.initialize()
2023-02-08T16:10:30.0276473Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 56, in initialize
2023-02-08T16:10:30.0277457Z     raise RuntimeError(node.err_msg)
2023-02-08T16:10:30.0282115Z RuntimeError: Node-action-classification/timesformer runs failed, error msg: Create action-classification/timesformer operator action-classification/timesformer:main with args None and kws {'model_name': 'timesformer_k400_8x224'} failed, err: Command '['/opt/conda/bin/python3', '-m', 'pip', 'install', '# towhee.models>=0.7.0']' returned non-zero exit status 1., Traceback (most recent call last):
2023-02-08T16:10:30.0285199Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 81, in initialize
2023-02-08T16:10:30.0286200Z     self._op = self._op_pool.acquire_op(
2023-02-08T16:10:30.0287652Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
2023-02-08T16:10:30.0288844Z     op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
2023-02-08T16:10:30.0290445Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 153, in load_operator
2023-02-08T16:10:30.0291585Z     op = factory(function, arg, kws, tag)
2023-02-08T16:10:30.0293137Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 132, in load_operator_from_cache
2023-02-08T16:10:30.0294322Z     return self.load_operator_from_path(path, arg, kws)
2023-02-08T16:10:30.0295896Z   File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 95, in load_operator_from_path
2023-02-08T16:10:30.0297420Z     subprocess.check_call([sys.executable, '-m', 'pip', 'install', req])
2023-02-08T16:10:30.0298476Z   File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
2023-02-08T16:10:30.0299378Z     raise CalledProcessError(retcode, cmd)
2023-02-08T16:10:30.0301078Z subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-m', 'pip', 'install', '# towhee.models>=0.7.0']' returned non-zero exit status 1.
2023-02-08T16:10:30.0301954Z 
2023-02-08T16:10:30.3475037Z 2023-02-08 16:10:30.345 | ERROR    | __main__:execute_ops:167 - Fail to run readme for 29: operator https://towhee.io/action-classification/timesformer
```
I think we can delete the '# ' for the convenience of automated weekly testing.
![image](https://user-images.githubusercontent.com/109071306/217768334-4045f3f9-6d56-48ee-a32f-1279ccf332dd.png)

The requirements will be directly installed according to the script.
![image](https://user-images.githubusercontent.com/109071306/217768360-5af78ca9-55ee-4738-8693-d75635e05a79.png)

### Expected Behavior

pass

### Steps To Reproduce

https://towhee.io/action-classification/timesformer/src/branch/main/requirements.txt

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
@junjiejiangjjj Have we changed the method to check op requirements and install op dependencies?

**Comment by jaelgu** [comment]
@NicoYuan1986 Fixed. Please re-check.

**Comment by NicoYuan1986** [comment]
Fixed.
