### ISSUE TITLE
[Bug]: [Weekly]The operator audio-classification/panns failed reporting a NotImplementedError

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The operator audio-classification/panns failed reporting a NotImplementedError.
1. operator: https://towhee.io/audio-classification/panns
2. log link: https://github.com/towhee-io/towhee/actions/runs/4133410103/jobs/7143277072
3. error message:
```
2023-02-09 12:23:06.288 | DEBUG    | __main__:execute_ops:176 - Running extracted readme for /workspace/towhee_CI/hub_operator/audio-classification-panns
Cloning into '/github/home/.towhee/operators/audio-classification/panns/main'...
Traceback (most recent call last):
  File "/workspace/towhee_CI/hub_operator/testcases/test_audio-classification-panns.py", line 10, in <module>
    DataCollection(p('/workspace/towhee_CI/hub_operator/dataset/test.wav')).show()
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 109, in __call__
    outputs = graph(inputs)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 78, in __call__
    return self.result()
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 66, in result
    raise RuntimeError(errs)
RuntimeError: Node-audio-classification/panns runs failed, error msg: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now, Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 148, in _call
    return True, self._op(*inputs), None
  File "/opt/conda/lib/python3.8/site-packages/towhee/engine/operator_registry.py", line 201, in wrapper_call
    return old_call(self, *args, **kws)
  File "/github/home/.towhee/operators/audio-classification/panns/main/panns.py", line 78, in __call__
    clipwise_output, embedding = self.tagger.inference(audio)
  File "/opt/conda/lib/python3.8/site-packages/panns_inference/inference.py", line 71, in inference
    output_dict = self.model(audio, None)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/panns_inference/models.py", line 133, in forward
    x = self.spectrogram_extractor(input)   # (batch_size, 1, time_steps, freq_bins)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torchlibrosa/stft.py", line 658, in forward
    (real, imag) = self.stft.forward(input)
  File "/opt/conda/lib/python3.8/site-packages/torchlibrosa/stft.py", line 235, in forward
    x = F.pad(x, pad=(self.n_fft // 2, self.n_fft // 2), mode=self.pad_mode)
NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now


2023-02-09 12:23:15.908 | ERROR    | __main__:execute_ops:180 - Fail to run readme for 47: operator https://towhee.io/audio-classification/panns
```

### Expected Behavior

pass

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

### Anything else?

Used wav: /towhee_CI/hub_operator/dataset/test.wav

**Comment by NicoYuan1986** [comment]
@jaelgu  Could you please help look at the error?

**Comment by jaelgu** [comment]
@NicoYuan1986 Fixed. Please re-check with updated op https://towhee.io/audio-classification/panns

**Comment by NicoYuan1986** [comment]
Fixed.
