### ISSUE TITLE
[Bug]: [Weekly]Operator image-embedding/isc run failed because export a node failed

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Operator image-embedding/isc run failed because export a node failed.
```
2023-02-10 11:21:26.095 | DEBUG    | __main__:execute_ops:178 - Running extracted readme for /workspace/towhee_CI/hub_operator/image-embedding-isc
Cloning into '/github/home/.towhee/operators/image-embedding/isc/main'...
2023-02-10 11:23:17,387 - 139949212107584 - isc.py-isc:168 - ERROR: Fail to save as onnx: Failed to export a node '%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
' (in list node %2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
) because it is not constant. Please try to make things (e.g. kernel sizes) static if possible.  [Caused by the value '2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
)' (type 'List[int]') in the TorchScript graph. The containing node has kind 'prim::ListConstruct'.] 

    Inputs:
        #0: 2488 defined in (%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
        #1: 2497 defined in (%2497 : Long(device=cpu) = onnx::Squeeze(%2495, %2496), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
    Outputs:
        #0: 2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
    )  (type 'List[int]').
Traceback (most recent call last):
  File "/github/home/.towhee/operators/image-embedding/isc/main/isc.py", line 155, in save_model
    torch.onnx.export(self._model.to('cpu'),
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1867, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 380, in wrapper
    return fn(g, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 286, in wrapper
    args = [
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 287, in <listcomp>
    _parse_arg(arg, arg_desc, arg_name, fn_name)  # type: ignore[assignment]
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 104, in _parse_arg
    raise errors.SymbolicValueError(
torch.onnx.errors.SymbolicValueError: Failed to export a node '%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
' (in list node %2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
) because it is not constant. Please try to make things (e.g. kernel sizes) static if possible.  [Caused by the value '2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
)' (type 'List[int]') in the TorchScript graph. The containing node has kind 'prim::ListConstruct'.] 

    Inputs:
        #0: 2488 defined in (%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
        #1: 2497 defined in (%2497 : Long(device=cpu) = onnx::Squeeze(%2495, %2496), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
    Outputs:
        #0: 2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
    )  (type 'List[int]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/towhee_CI/hub_operator/testcases/test_image-embedding-isc.py", line 14, in <module>
    op.save_model('onnx', 'test.onnx')
  File "/github/home/.towhee/operators/image-embedding/isc/main/isc.py", line 169, in save_model
    raise RuntimeError(f'Fail to save as onnx: {e}.')
RuntimeError: Fail to save as onnx: Failed to export a node '%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
' (in list node %2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
) because it is not constant. Please try to make things (e.g. kernel sizes) static if possible.  [Caused by the value '2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
)' (type 'List[int]') in the TorchScript graph. The containing node has kind 'prim::ListConstruct'.] 

    Inputs:
        #0: 2488 defined in (%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
        #1: 2497 defined in (%2497 : Long(device=cpu) = onnx::Squeeze(%2495, %2496), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
    Outputs:
        #0: 2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
    )  (type 'List[int]').
2023-02-10 11:23:17.802 | ERROR    | __main__:execute_ops:182 - Fail to run readme for 21: operator https://towhee.io/image-embedding/isc
```

### Expected Behavior

pass

### Steps To Reproduce

1. weekly: https://github.com/towhee-io/towhee/actions/runs/4143024277/jobs/7164388482
2. operator: https://towhee.io/image-embedding/isc

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
@jaelgu  Could you help look at the error?

**Comment by jaelgu** [comment]
@NicoYuan1986 It works at my local. Can you check your torch & towhee.models versions?

**Comment by NicoYuan1986** [comment]
> @NicoYuan1986 It works at my local. Can you check your torch & towhee.models versions?

towhee.models: 0.9.1.dev44
torch: 1.13.1

**Comment by jaelgu** [comment]
@NicoYuan1986 Fixed. Please check with updated op.

**Comment by NicoYuan1986** [comment]
https://github.com/towhee-io/towhee/actions/runs/4202567665/jobs/7290876509 
still failing. need help @jaelgu 
```
2023-02-17 11:05:29.493 | DEBUG    | __main__:execute_ops:180 - Running extracted readme for /workspace/towhee_CI/hub_operator/image-embedding-isc
Cloning into '/github/home/.towhee/operators/image-embedding/isc/main'...
2023-02-17 11:07:42,073 - 139997210690368 - isc.py-isc:168 - ERROR: Fail to save as onnx: Failed to export a node '%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
' (in list node %2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
) because it is not constant. Please try to make things (e.g. kernel sizes) static if possible.  [Caused by the value '2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
)' (type 'List[int]') in the TorchScript graph. The containing node has kind 'prim::ListConstruct'.] 

    Inputs:
        #0: 2488 defined in (%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
        #1: 2497 defined in (%2497 : Long(device=cpu) = onnx::Squeeze(%2495, %2496), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
    Outputs:
        #0: 2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
    )  (type 'List[int]').
Traceback (most recent call last):
  File "/github/home/.towhee/operators/image-embedding/isc/main/isc.py", line 155, in save_model
    torch.onnx.export(self._model.to('cpu'),
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1115, in _model_to_graph
    graph = _optimize_graph(
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 663, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/utils.py", line 1867, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 380, in wrapper
    return fn(g, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 286, in wrapper
    args = [
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 287, in <listcomp>
    _parse_arg(arg, arg_desc, arg_name, fn_name)  # type: ignore[assignment]
  File "/opt/conda/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 104, in _parse_arg
    raise errors.SymbolicValueError(
torch.onnx.errors.SymbolicValueError: Failed to export a node '%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
' (in list node %2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
) because it is not constant. Please try to make things (e.g. kernel sizes) static if possible.  [Caused by the value '2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
)' (type 'List[int]') in the TorchScript graph. The containing node has kind 'prim::ListConstruct'.] 

    Inputs:
        #0: 2488 defined in (%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
        #1: 2497 defined in (%2497 : Long(device=cpu) = onnx::Squeeze(%2495, %2496), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
    Outputs:
        #0: 2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
    )  (type 'List[int]')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/towhee_CI/hub_operator/testcases/test_image-embedding-isc.py", line 14, in <module>
    op.save_model('onnx', 'test.onnx')
  File "/github/home/.towhee/operators/image-embedding/isc/main/isc.py", line 169, in save_model
    raise RuntimeError(f'Fail to save as onnx: {e}.')
RuntimeError: Fail to save as onnx: Failed to export a node '%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
' (in list node %2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
) because it is not constant. Please try to make things (e.g. kernel sizes) static if possible.  [Caused by the value '2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
)' (type 'List[int]') in the TorchScript graph. The containing node has kind 'prim::ListConstruct'.] 

    Inputs:
        #0: 2488 defined in (%2488 : Long(device=cpu) = onnx::Squeeze(%2486, %2487), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
        #1: 2497 defined in (%2497 : Long(device=cpu) = onnx::Squeeze(%2495, %2496), scope: towhee.models.isc.isc.ISCNet:: # /opt/conda/lib/python3.8/site-packages/towhee/models/isc/isc.py:61:0
    )  (type 'Tensor')
    Outputs:
        #0: 2498 defined in (%2498 : int[] = prim::ListConstruct(%2488, %2497), scope: towhee.models.isc.isc.ISCNet::
    )  (type 'List[int]').
2023-02-17 11:07:42.491 | ERROR    | __main__:execute_ops:184 - Fail to run readme for 20: operator https://towhee.io/image-embedding/isc
```

**Comment by binbinlv** [comment]
@NicoYuan1986 
Is it fixed now?

**Comment by jaelgu** [comment]
> > @NicoYuan1986 It works at my local. Can you check your torch & towhee.models versions?
> 
> towhee.models: 0.9.1.dev44 torch: 1.13.1

It seems your towhee.models is not the latest version.

**Comment by NicoYuan1986** [comment]
succeed locally
