### ISSUE TITLE
[Bug]: [Weekly]The operator image-text-embedding/blip run failed with load error

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The operator image-text-embedding/blip run failed with load error.
```
2023-02-10 12:00:20.808 | DEBUG    | __main__:execute_ops:178 - Running extracted readme for /workspace/towhee_CI/hub_operator/image-text-embedding-blip
Cloning into '/github/home/.towhee/operators/image-text-embedding/blip/main'...
2023-02-10 12:00:26.711800: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-10 12:00:26.829858: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-10 12:00:26.833192: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-10 12:00:26.833209: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-10 12:00:27.421924: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-10 12:00:27.421971: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-10 12:00:27.421977: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-02-10 12:00:28,469 - 140509463348032 - blip.py-blip:73 - ERROR: Fail to load model by name: blip_itm_base
Traceback (most recent call last):
  File "/workspace/towhee_CI/hub_operator/testcases/test_image-text-embedding-blip.py", line 4, in <module>
    pipe.input('url')
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/pipeline.py", line 113, in output
    run_pipe.preload()
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 102, in preload
    _ = Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 46, in __init__
    self.initialize()
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 56, in initialize
    raise RuntimeError(node.err_msg)
RuntimeError: Node-image-text-embedding/blip runs failed, error msg: Create image-text-embedding/blip operator image-text-embedding/blip:main with args None and kws {'model_name': 'blip_itm_base', 'modality': 'image'} failed, err: Can't load the configuration of '{'weights': 'Salesforce/blip-itm-base-coco', 'image_size': 224}'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '{'weights': 'Salesforce/blip-itm-base-coco', 'image_size': 224}' is the correct path to a directory containing a config.json file, Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 620, in _get_config_dict
    resolved_config_file = cached_file(
  File "/opt/conda/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 172, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '{'weights': 'Salesforce/blip-itm-base-coco', 'image_size': 224}'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 81, in initialize
    self._op = self._op_pool.acquire_op(
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 153, in load_operator
    op = factory(function, arg, kws, tag)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 132, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 118, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 161, in instance_operator
    return op(*arg, **kws) if kws is not None else op(*arg)
  File "/github/home/.towhee/operators/image-text-embedding/blip/main/blip.py", line 74, in __init__
    raise e
  File "/github/home/.towhee/operators/image-text-embedding/blip/main/blip.py", line 71, in __init__
    blip_model = BlipForImageTextRetrieval.from_pretrained(cfg)
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2079, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 538, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 565, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/configuration_utils.py", line 641, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of '{'weights': 'Salesforce/blip-itm-base-coco', 'image_size': 224}'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure '{'weights': 'Salesforce/blip-itm-base-coco', 'image_size': 224}' is the correct path to a directory containing a config.json file

2023-02-10 12:00:28.911 | ERROR    | __main__:execute_ops:182 - Fail to run readme for 54: operator https://towhee.io/image-text-embedding/blip
```

### Expected Behavior

pass

### Steps To Reproduce

1. weekly: https://github.com/towhee-io/towhee/actions/runs/4148665107/jobs/7176876253
2. operator: https://towhee.io/image-text-embedding/blip

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
@wxywb  Could you help look at the error?

**Comment by NicoYuan1986** [comment]
Update: still failing 
https://github.com/towhee-io/towhee/actions/runs/4162888555/jobs/7202603844
```
2023-02-13 14:26:17.853 | DEBUG    | __main__:execute_ops:178 - Running extracted readme for /workspace/towhee_CI/hub_operator/image-text-embedding-blip
Cloning into '/github/home/.towhee/operators/image-text-embedding/blip/main'...
2023-02-13 14:26:24.400661: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-13 14:26:24.533830: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-13 14:26:24.537214: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-13 14:26:24.537234: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-13 14:26:25.133569: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-13 14:26:25.133614: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/conda/lib/python3.8/site-packages/cv2/../../lib64:
2023-02-13 14:26:25.133620: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/workspace/towhee_CI/hub_operator/testcases/test_image-text-embedding-blip.py", line 4, in <module>
    pipe.input('url')
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/pipeline.py", line 113, in output
    run_pipe.preload()
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 102, in preload
    _ = Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 46, in __init__
    self.initialize()
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 56, in initialize
    raise RuntimeError(node.err_msg)
RuntimeError: Node-image-text-embedding/blip runs failed, error msg: Create image-text-embedding/blip operator image-text-embedding/blip:main with args None and kws {'model_name': 'blip_itm_base_coco', 'modality': 'image'} failed, err: cannot import name 'accelerate' from 'towhee.dc2' (/opt/conda/lib/python3.8/site-packages/towhee/dc2.py), Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 102, in load_operator_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/github/home/.towhee/operators/image-text-embedding/blip/main/blip.py", line 29, in <module>
    from towhee.dc2 import accelerate
ImportError: cannot import name 'accelerate' from 'towhee.dc2' (/opt/conda/lib/python3.8/site-packages/towhee/dc2.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 81, in initialize
    self._op = self._op_pool.acquire_op(
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 153, in load_operator
    op = factory(function, arg, kws, tag)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 132, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 115, in load_operator_from_path
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/github/home/.towhee/operators/image-text-embedding/blip/main/__init__.py", line 15, in <module>
    from .blip import Blip
  File "/github/home/.towhee/operators/image-text-embedding/blip/main/blip.py", line 29, in <module>
    from towhee.dc2 import accelerate
ImportError: cannot import name 'accelerate' from 'towhee.dc2' (/opt/conda/lib/python3.8/site-packages/towhee/dc2.py)

2023-02-13 14:26:26.922 | ERROR    | __main__:execute_ops:182 - Fail to run readme for 54: operator https://towhee.io/image-text-embedding/blip
```

**Comment by binbinlv** [comment]
@NicoYuan1986 
is it fixed now?

**Comment by NicoYuan1986** [comment]
Fixed

**Comment by jawhster** [comment]
I'm getting a similar error but for a model that has the config.json file in a subdirectory. Can I comment here or should I create a new issue? Thank you

`ops.sentence_embedding.transformers(model_name='sentence-transformers/clip-ViT-B-32/0_CLIPModel')`

**Comment by jaelgu** [comment]
> I'm getting a similar error but for a model that has the config.json file in a subdirectory. Can I comment here or should I create a new issue? Thank you
> 
> `ops.sentence_embedding.transformers(model_name='sentence-transformers/clip-ViT-B-32/0_CLIPModel')`
> 
> ... RuntimeError: Node-sentence-embedding/transformers-1 runs failed, error msg: Create sentence-embedding/transformers-1 operator sentence-embedding/transformers:main with args None and kws {'model_name': 'sentence-transformers/clip-ViT-B-32/0_CLIPModel'} failed, err: Can't load the configuration of 'sentence-transformers/clip-ViT-B-32/0_CLIPModel'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'sentence-transformers/clip-ViT-B-32/0_CLIPModel' is the correct path to a directory containing a config.json file, Traceback (most recent call last): ... OSError: Can't load the configuration of 'sentence-transformers/clip-ViT-B-32/0_CLIPModel'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'sentence-transformers/clip-ViT-B-32/0_CLIPModel' is the correct path to a directory containing a config.json file

Are you trying to load "sentence-transformers/clip-ViT-B-32" from Huggingface hub? In this case, you should just use the model_name='sentence-transformers/clip-ViT-B-32' without '0_CLIPModel' at the end.

**Comment by jawhster** [comment]
Hi Jael Gu! Thanks very much for reply. Unfortunately, that does not work either. If I enter `.map('img', 'vec', ops.sentence_embedding.transformers(model_name='sentence-transformers/clip-ViT-B-32'))`, then I receive error below. So I tried adding the 0_CLIPModel directory where the config.json is located. Apologies if I am making a silly mistake or something I am missing. Thanks again for your help.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [12], line 2
      1 p = (
----> 2     pipe.input('path')
      3     .map('path', 'img', ops.image_decode.cv2('rgb'))
      4     #.map('img', 'vec', ops.image_text_embedding.clip(model_name='clip_vit_base_patch32', modality='image'))
      5     .map('img', 'vec', ops.sentence_embedding.transformers(model_name='sentence-transformers/clip-ViT-B-32'))
      6     .map('vec', 'vec', lambda x: x / np.linalg.norm(x))
      7     .output('img', 'vec')
      8 )

File /opt/conda/lib/python3.9/site-packages/towhee/runtime/pipeline.py:116, in Pipeline.output(self, *output_schema, **config_kws)
    113 dag_dict[self._clo_node]['next_nodes'].append(uid)
    115 run_pipe = RuntimePipeline(dag_dict, config=config_kws)
--> 116 run_pipe.preload()
    117 return run_pipe

File /opt/conda/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py:109, in RuntimePipeline.preload(self)
    105 def preload(self):
    106     """
    107     Preload the operators.
    108     """
--> 109     _ = Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)

File /opt/conda/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py:52, in Graph.__init__(self, nodes, edges, operator_pool, thread_pool, time_profiler)
     50 self._node_runners = None
     51 self._data_queues = None
---> 52 self.initialize()

File /opt/conda/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py:62, in Graph.initialize(self)
     60 node = create_node(self._nodes[name], self._operator_pool, in_queues, out_queues, self._time_profiler)
     61 if not node.initialize():
---> 62     raise RuntimeError(node.err_msg)
     63 self._node_runners.append(node)

RuntimeError: Node-sentence-embedding/transformers-1 runs failed, error msg: Create sentence-embedding/transformers-1 operator sentence-embedding/transformers:main with args None and kws {'model_name': 'sentence-transformers/clip-ViT-B-32'} failed, err: sentence-transformers/clip-ViT-B-32 does not appear to have a file named config.json. Checkout 'https://huggingface.co/sentence-transformers/clip-ViT-B-32/main' for available files., Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/opt/conda/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/sentence-transformers/clip-ViT-B-32/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1166, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1507, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/opt/conda/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 269, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: Root=1-64449dfc-04c1ded25505aa4f70055356)

Entry Not Found for url: https://huggingface.co/sentence-transformers/clip-ViT-B-32/resolve/main/config.json.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
    self._op = self._op_pool.acquire_op(
  File "/opt/conda/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
  File "/opt/conda/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 154, in load_operator
    op = factory(function, arg, kws, tag)
  File "/opt/conda/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 133, in load_operator_from_cache
    return self.load_operator_from_path(path, arg, kws)
  File "/opt/conda/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 119, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/opt/conda/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 162, in instance_operator
    return op(*arg, **kws) if kws is not None else op(*arg)
  File "/home/ubuntu/.towhee/operators/sentence-embedding/transformers/main/__init__.py", line 19, in transformers
    return AutoTransformers(*args, **kwargs)
  File "/home/ubuntu/.towhee/operators/sentence-embedding/transformers/main/auto_transformers.py", line 113, in __init__
    self.model = Model(model_name=self.model_name, checkpoint_path=self.checkpoint_path, device=self.device)
  File "/home/ubuntu/.towhee/operators/sentence-embedding/transformers/main/auto_transformers.py", line 67, in __init__
    self.model = create_model(model_name, checkpoint_path, device)
  File "/home/ubuntu/.towhee/operators/sentence-embedding/transformers/main/auto_transformers.py", line 50, in create_model
    model = AutoModel.from_pretrained(model_name).to(device)
  File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 916, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers/configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "/opt/conda/lib/python3.9/site-packages/transformers/utils/hub.py", line 454, in cached_file
    raise EnvironmentError(
OSError: sentence-transformers/clip-ViT-B-32 does not appear to have a file named config.json. Checkout 'https://huggingface.co/sentence-transformers/clip-ViT-B-32/main' for available files.

**Comment by jaelgu** [comment]
@jawhster Sorry I just investigated the model files at huggingface hub. It looks like it cannot be loaded by huggingface method. According to its README, you can use it with sentence_transformers. So you can try with this op: https://towhee.io/sentence-embedding/sbert

**Comment by jawhster** [comment]
Thank you but unfortunately that doesn’t seem to work for getting an embedding from an image, only a sentence as input. I need to use sentence-transformers/clip-ViT-B-32 to get the embedding for an image. Thanks so much

**Comment by junjiejiangjjj** [comment]
https://towhee.io/image-text-embedding/clip    This operator can convert images and text into embeddings."

**Comment by jawhster** [comment]
First, thanks for all of your help. Correct but model and dimensions for what I need (https://huggingface.co/sentence-transformers/clip-ViT-B-32) are different than the supported keys, e.g. clip_vit_base_patch32 (https://huggingface.co/openai/clip-vit-base-patch32). I receive KeyError: 'sentence-transformers/clip-ViT-B-32' when trying to use `.map('img', 'vec', ops.image_text_embedding.clip(model_name='sentence-transformers/clip-ViT-B-32', modality='image'))`. So looks like it is not supported to use https://huggingface.co/sentence-transformers/clip-ViT-B-32 to get an embedding for an image?

**Comment by junjiejiangjjj** [comment]
I tried it (https://huggingface.co/sentence-transformers/clip-ViT-B-32) and found that the model also returns a 512-dimensional vector.  You can also specify the model through the `checkpoint_path` parameter. 
```python
ops.image_text_embedding.clip(model_name='clip_vit_base_patch32', 
                                                        modality='image',  
                                                        checkpoint_path=''))
