### ISSUE TITLE
[Bug]:  create pipeline failed

### ISSUE THREAD

**Issue by junjiejiangjjj** [towhee-io/towhee#2413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```python
from towhee.dc2 import pipe, ops

p = (
    pipe.input('a')
    .map('a', ('b', 'c'), lambda x: (x, x))
    .flat_map('c', 'c', lambda x: [x] * 3)
)

p2 = p.map('b', 'e', lambda x: x)
p3 = p.flat_map('a', 'f', lambda x: [x] * 3)

p4 = p3.concat(p2).output('f', 'e')

print(p4(1).to_list())
```

Traceback (most recent call last):
  File "test.py", line 70, in <module>
    p4 = p3.concat(p2).output('f', 'e')
  File "/home/junjie.jiangjjj/WorkSpace/dev/junjie/towhee/towhee/runtime/pipeline.py", line 115, in output
    run_pipe = RuntimePipeline(dag_dict, config=config_kws)
  File "/home/junjie.jiangjjj/WorkSpace/dev/junjie/towhee/towhee/runtime/runtime_pipeline.py", line 127, in __init__
    self._dag_repr = DAGRepr.from_dict(dag)
  File "/home/junjie.jiangjjj/WorkSpace/dev/junjie/towhee/towhee/runtime/dag_repr.py", line 310, in from_dict
    dag_nodes, schema_edges = DAGRepr.set_edges(nodes)
  File "/home/junjie.jiangjjj/WorkSpace/dev/junjie/towhee/towhee/runtime/dag_repr.py", line 230, in set_edges
    edges[out_id] = DAGRepr.get_edge_from_schema(tuple(out_schema), nodes[name].inputs, nodes[name].outputs,
  File "/home/junjie.jiangjjj/WorkSpace/dev/junjie/towhee/towhee/runtime/dag_repr.py", line 197, in get_edge_from_schema
    inputs_type = [ahead_schemas[inp].type for inp in inputs]
  File "/home/junjie.jiangjjj/WorkSpace/dev/junjie/towhee/towhee/runtime/dag_repr.py", line 197, in <listcomp>
    inputs_type = [ahead_schemas[inp].type for inp in inputs]
KeyError: 'b'

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by shiyu22** [comment]
It's a bug with `dfs_used_schema` function, will fix it. And the correct results is `[[1, 1], [1, Empty()], [1, Empty()]]`, right?

**Comment by Chiiizzzy** [comment]
Also `concat` changes the ColumnType to QUEUE for those columns supposed to be SCALAR

**Comment by shiyu22** [comment]
will check it.
