### ISSUE TITLE
[Bug]: [Notebook]A specific numpy version is needed for text_video_retrieval

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A specific numpy version is needed for text_video_retrieval.
https://github.com/towhee-io/examples/blob/main/video/text_video_retrieval/1_text_video_retrieval_engine.ipynb
At first, i meet an error when running this sentence.
![image](https://user-images.githubusercontent.com/109071306/220288587-76656002-d1b8-412d-ada0-866a22a99e28.png)
And this is the error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/test/miniconda3/envs/nico/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 149, in __call__
    return graph(inputs)
  File "/test/miniconda3/envs/nico/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 104, in __call__
    return f.result()
  File "/test/miniconda3/envs/nico/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 34, in result
    ret = self._graph.result()
  File "/test/miniconda3/envs/nico/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 87, in result
    raise RuntimeError(errs)
RuntimeError: Node-video-text-embedding/clip4clip-1 runs failed, error msg: module 'numpy' has no attribute 'long', Traceback (most recent call last):
  File "/test/miniconda3/envs/nico/lib/python3.9/site-packages/towhee/runtime/nodes/node.py", line 156, in _call
    return True, self._op(*inputs), None
  File "/test/miniconda3/envs/nico/lib/python3.9/site-packages/towhee/engine/operator_registry.py", line 201, in wrapper_call
    return old_call(self, *args, **kws)
  File "/home/super/.towhee/operators/video-text-embedding/clip4clip/main/clip4clip.py", line 65, in __call__
    vec = self._inference_from_text(data)
  File "/home/super/.towhee/operators/video-text-embedding/clip4clip/main/clip4clip.py", line 72, in _inference_from_text
    text_ids = convert_tokens_to_id(self.tokenize, text)
  File "/test/miniconda3/envs/nico/lib/python3.9/site-packages/towhee/models/clip4clip/utils.py", line 43, in convert_tokens_to_id
    pairs_text = np.zeros((1, max_words), dtype=np.long)
  File "/test/miniconda3/envs/nico/lib/python3.9/site-packages/numpy/__init__.py", line 320, in __getattr__
    del PytestTester
AttributeError: module 'numpy' has no attribute 'long'
```

Then i found a solution: https://blog.csdn.net/qq_51955445/article/details/128699557
After i modify the numpy version from 1.24.2 to 1.23.0, the error disappeared.
So i think we can add the specific numpy version to avoid some mistakes.
![image](https://user-images.githubusercontent.com/109071306/220289198-6206c443-1c20-4a36-b200-6a9e7ea0db8c.png)

### Expected Behavior

succeed

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev55
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
@junjiejiangjjj  Can you help take a look?

**Comment by junjiejiangjjj** [comment]
@zc277584121
