### ISSUE TITLE
[Bug]: An unexpected error occurred when using Video Copy Detection with model 'convit_small'

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/109071306/221504729-06de8256-bfbc-4025-a980-a1606d54826f.png)

### Expected Behavior

pass

### Steps To Reproduce

```markdown
import towhee
from towhee.dc2 import AutoPipes, AutoConfig

insert_conf = AutoConfig.load_config('video_embedding')
# insert_conf.milvus_host='172.16.70.7'
insert_conf.collection='video_copy_detection'
insert_conf.device = -1
insert_conf.model='convit_small'

# use hbase
# insert_conf.hbase_host = '172.16.70.7'
insert_conf.hbase_table = 'video_copy_detection' # path in the docker image
insert_pipe = AutoPipes.pipeline('video_embedding', insert_conf)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev55
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
same error with model convit_tiny:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[91], line 13
     10 # use hbase
     11 # insert_conf.hbase_host = '172.16.70.7'
     12 insert_conf.hbase_table = 'video_copy_detection' # path in the docker image
---> 13 insert_pipe = AutoPipes.pipeline('video_embedding', insert_conf)

File /test/miniconda3/lib/python3.9/site-packages/towhee/runtime/auto_pipes.py:69, in AutoPipes.pipeline(name, *args, **kwargs)
     67 with AutoPipes._lock:
     68     if name in AutoPipes._PIPES_DEF:
---> 69         return AutoPipes._PIPES_DEF[name](*args, **kwargs)
     71     with set_pipe_name(name):
     72         pipe_loader.PipelineLoader.load_pipeline(name)

File /test/miniconda3/lib/python3.9/site-packages/towhee/runtime/auto_pipes.py:59, in AutoPipes.register.<locals>.wrapper(*args, **kwargs)
     57 @wraps(pipe_def)
     58 def wrapper(*args, **kwargs):
---> 59     return pipe_def(*args, **kwargs)

File /test/miniconda3/lib/python3.9/site-packages/towhee/pipelines/video_embedding.py:158, in video_embedding(config)
    155     kv_op = ops.kvstorage.insert_leveldb(path=config.leveldb_path)
    156 norm_op = None if config.model == 'isc' else ops.towhee.np_normalize()
--> 158 return _video_embedding(decode_op, emb_op, milvus_op, kv_op, norm_op, config.tracer, allow_triton, config.device)

File /test/miniconda3/lib/python3.9/site-packages/towhee/pipelines/video_embedding.py:91, in _video_embedding(decode_op, emb_op, milvus_op, kv_op, norm_op, tracer, allow_triton, device)
     79     return (
     80         pipe.input('url')
     81             .map('url', 'id', lambda x: x)
   (...)
     87             .output(tracer=tracer)
     88     )
     90 if norm_op:
---> 91     return _norm()
     92 return _unnorm()

File /test/miniconda3/lib/python3.9/site-packages/towhee/pipelines/video_embedding.py:67, in _video_embedding.<locals>._norm()
     65 def _norm():
     66     return (
---> 67         pipe.input('url')
     68             .map('url', 'id', lambda x: x)
     69             .flat_map('url', 'frames', decode_op)
     70             .map('frames', 'emb', emb_op, config=op_config)
     71             .map('emb', 'emb', norm_op)
     72             .map(('id', 'emb'), 'milvus_res', milvus_op)
     73             .window_all('emb', 'video_emb', merge_ndarray)
     74             .map(('id', 'video_emb'), ('insert_status'), kv_op)
     75             .output(tracer=tracer)
     76     )

File /test/miniconda3/lib/python3.9/site-packages/towhee/runtime/pipeline.py:116, in Pipeline.output(self, *output_schema, **config_kws)
    113 dag_dict[self._clo_node]['next_nodes'].append(uid)
    115 run_pipe = RuntimePipeline(dag_dict, config=config_kws)
--> 116 run_pipe.preload()
    117 return run_pipe

File /test/miniconda3/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py:140, in RuntimePipeline.preload(self)
    136 def preload(self):
    137     """
    138     Preload the operators.
    139     """
--> 140     return _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)

File /test/miniconda3/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py:64, in _Graph.__init__(self, nodes, edges, operator_pool, thread_pool, enable_trance)
     62 self.features = None
     63 self.time_profiler.record(Event.pipe_name, Event.pipe_in)
---> 64 self.initialize()
     65 self._input_queue = self._data_queues[0]

File /test/miniconda3/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py:75, in _Graph.initialize(self)
     73 node = create_node(self._nodes[name], self._operator_pool, in_queues, out_queues, self._time_profiler)
     74 if not node.initialize():
---> 75     raise RuntimeError(node.err_msg)
     76 self._node_runners.append(node)

RuntimeError: Node-image-embedding/timm-2 runs failed, error msg: Create image-embedding/timm-2 operator image-embedding/timm:main with args None and kws {'model_name': 'convit_tiny', 'device': 'cpu'} failed, err: 'interpolation', Traceback (most recent call last):
  File "/test/miniconda3/lib/python3.9/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
    self._op = self._op_pool.acquire_op(
  File "/test/miniconda3/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
  File "/test/miniconda3/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 169, in load_operator
    op = factory(function, arg, kws, tag)
  File "/test/miniconda3/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 148, in load_operator_from_cache
    return self.load_operator_from_path(path, function, arg, kws)
  File "/test/miniconda3/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 134, in load_operator_from_path
    return self.instance_operator(op, arg, kws) if op is not None else None
  File "/test/miniconda3/lib/python3.9/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 177, in instance_operator
    return op(*arg, **kws) if kws is not None else op(*arg)
  File "/home/super/.towhee/operators/image-embedding/timm/main/__init__.py", line 19, in timm
    return TimmImage(**kwargs)
  File "/home/super/.towhee/operators/image-embedding/timm/main/timm_image.py", line 95, in __init__
    interpolation=self.config['interpolation'],
KeyError: 'interpolation'
```

**Comment by zc277584121** [comment]
fixed by : https://towhee.io/image-embedding/timm/commit/dbf64995d0eb4141998ce3b5bf0c6a96f1a8770e

**Comment by NicoYuan1986** [comment]
Fixed.
