### ISSUE TITLE
[Bug]: [Weekly]Operator Image Captioning with ExpansionNet v2 run failed 

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Operator Image Captioning with ExpansionNet v2 run failed.
https://github.com/towhee-io/towhee/actions/runs/4452602043/jobs/7847015860
https://towhee.io/image-captioning/expansionnet-v2
```
Traceback (most recent call last):
  File "/workspace/towhee_CI/hub_operator/testcases/test_image-captioning-expansionnet-v2.py", line 5, in <module>
    pipe.input('url')
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/pipeline.py", line 101, in output
    run_pipe.preload()
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 136, in preload
    return _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 62, in __init__
    self.initialize()
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/runtime_pipeline.py", line 73, in initialize
    raise RuntimeError(node.err_msg)
RuntimeError: Node-image-captioning/expansionnet-v2-1 runs failed, error msg: Create image-captioning/expansionnet-v2-1 operator image-captioning/expansionnet-v2:main with args None and kws {'model_name': 'expansionnet_rf'} failed, err: No module named 'towhee.command.s3', Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
    self._op = self._op_pool.acquire_op(
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 147, in load_operator
    op = factory(function, arg, kws, tag)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 130, in _load_operator_from_hub
    return self._load_operator_from_path(path, function, arg, kws)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 113, in _load_operator_from_path
    op = self._load_op(modname, path, fname)
  File "/opt/conda/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 77, in _load_op
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/github/home/.towhee/operators/image-captioning/expansionnet-v2/versions/main/__init__.py", line 15, in <module>
    from .expansionnet_v2 import ExpansionNetV2
  File "/github/home/.towhee/operators/image-captioning/expansionnet-v2/versions/main/expansionnet_v2.py", line 31, in <module>
    from towhee.command.s3 import S3Bucket
ModuleNotFoundError: No module named 'towhee.command.s3'
```

### Expected Behavior

pass

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by wxywb** [comment]
s3 utility in expansionnet_v2 is removed, how is it now?

**Comment by NicoYuan1986** [comment]
> s3 utility in expansionnet_v2 is removed, how is it now?

From the latest weekly test, the error still exists like 'RuntimeError: The size of tensor a (3) must match the size of tensor b (9) at non-singleton dimension 0'.

**Comment by NicoYuan1986** [comment]
The operator works well locally.

**Comment by wxywb** [comment]
okay I will check the detail tomorrow.

**Comment by wxywb** [comment]
blip works normally when transformers version below 4.22. I have updated the requirement in the operators' repo.

**Comment by NicoYuan1986** [comment]
Verify fixed.
