### ISSUE TITLE
[Bug]: text to vec example is not work

### ISSUE THREAD

**Issue by weicheng113** [towhee-io/towhee#2498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```python
Traceback (most recent call last):
  File "/home/user1/git/test/main.py", line 33, in <module>
    test2()
  File "/home/user1/git/test/main.py", line 15, in test2
    pipe.input('text')
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/site-packages/towhee/runtime/pipeline.py", line 103, in output
    dag_dict = deepcopy(self._dag)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user1/anaconda3/envs/test_project/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.lock' object
```

### Expected Behavior

Should print out vector.

### Steps To Reproduce

```markdown
from towhee import pipe, ops, DataCollection
p = (
        pipe.input('text')
        .map('text', 'vec',
             ops.sentence_embedding.transformers(model_name='sentence-transformers/paraphrase-albert-small-v2'))
        .output('text', 'vec')
    )

DataCollection(p('Hello, world.')).show()
```

### Environment

```markdown
- Towhee version(0.9.0:
- OS(Ubuntu):
- Python(3.9.16)

torch==1.13.1
transformers[torch]==4.27.4
jupyterlab==3.6.2
sentence-transformers==2.2.2
towhee==0.9.0
```

Thanks for the library. I am a new user, I copy the example code from the document and try out in my local. But I got the above exception. Is there anything I did wrong? Appreciate your help, thanks.

**Comment by junjiejiangjjj** [comment]
`from towhee.dc2 import pipe, ops, DataCollection` if towhee version <= 0.9.0

**Comment by weicheng113** [comment]
Great! Thanks for sharing the library.
