### ISSUE TITLE
[Bug]: TypeError: cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by winter-lau** [towhee-io/towhee#2522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i test demo described in Readme.md , got the follow error:

```
% python3 demo.py
Traceback (most recent call last):
  File "/Users/javayou/Projects/towhee-demo/demo.py", line 9, in <module>
    .map('img', 'vec', ops.image_text_embedding.clip(model_name='clip_vit_base_patch32', modality='image'))
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/pipeline.py", line 143, in map
    dag_dict = deepcopy(self._dag)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_thread.lock' object
```

### Steps To Reproduce

```markdown
1. pip3 install towhee towhee.models
2. demo.py with sample code in Readme
3. python3 demo.py
```

### Environment

```markdown
- Towhee version(0.9.0):
- OS(MacOS M1 Pro):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
The examples on the README require towhee 1.0.0rc1, which can be installed with `pip install towhee==1.0.0rc1`

**Comment by winter-lau** [comment]
pip install towhee==1.0.0rc1  works!

**Comment by winter-lau** [comment]
when upgrade to 1.0.0rc1 , new error occured:

```
Traceback (most recent call last):
  File "/Users/javayou/Projects/towhee-demo/demo.py", line 12, in <module>
    .output()
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/pipeline.py", line 116, in output
    run_pipe.preload()
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 140, in preload
    return _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 64, in __init__
    self.initialize()
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 75, in initialize
    raise RuntimeError(node.err_msg)
RuntimeError: Node-ann-insert/faiss-index-3 runs failed, error msg: Create ann-insert/faiss-index-3 operator ann-insert/faiss-index:main with args ('./faiss', 512) and kws None failed, err: No module named 'faiss', Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
    self._op = self._op_pool.acquire_op(
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 147, in load_operator
    op = factory(function, arg, kws, tag)
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 130, in _load_operator_from_hub
    return self._load_operator_from_path(path, function, arg, kws)
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 113, in _load_operator_from_path
    op = self._load_op(modname, path, fname)
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 77, in _load_op
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/javayou/.towhee/operators/ann-insert/faiss-index/versions/main/__init__.py", line 1, in <module>
    from .to_faiss import ToFaiss
  File "/Users/javayou/.towhee/operators/ann-insert/faiss-index/versions/main/to_faiss.py", line 6, in <module>
    import faiss
ModuleNotFoundError: No module named 'faiss'
```

**Comment by junjiejiangjjj** [comment]
pip install faiss-cpu

**Comment by winter-lau** [comment]
```
% pip3 install faiss-cpu
Collecting faiss-cpu
  Downloading faiss_cpu-1.7.4-cp310-cp310-macosx_11_0_arm64.whl (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 4.5 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.7.4
```
re-run demo: 
```
% python3 demo.py
Downloading https://towhee.io/ann-search/faiss-index/resolve/branch/main/requirements.txt to /Users/javayou/.towhee/operators/ann-sea
Downloading https://towhee.io/ann-search/faiss-index/resolve/branch/main/__init__.py to /Users/javayou/.towhee/operators/ann-search/f
Downloading https://towhee.io/ann-search/faiss-index/resolve/branch/main/README.md to /Users/javayou/.towhee/operators/ann-search/fai
Downloading https://towhee.io/ann-search/faiss-index/resolve/branch/main/.gitattributes to /Users/javayou/.towhee/operators/ann-searc
Downloading https://towhee.io/ann-search/faiss-index/resolve/branch/main/faiss_search.py to /Users/javayou/.towhee/operators/ann-sear
Downloading https://towhee.io/ann-search/faiss-index/resolve/branch/main/result.png to /Users/javayou/.towhee/operators/ann-search/fa
Requirement already satisfied: faiss-cpu in /opt/homebrew/lib/python3.10/site-packages (from -r /Users/javayou/.towhee/operators/ann-search/faiss-index/versions/main/requirements.txt (line 1)) (1.7.4)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.10/site-packages (from -r /Users/javayou/.towhee/operators/ann-search/faiss-index/versions/main/requirements.txt (line 2)) (1.24.3)
Traceback (most recent call last):
  File "/Users/javayou/Projects/towhee-demo/demo.py", line 34, in <module>
    DataCollection(p('a cat')).show()
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 149, in __call__
    return graph(inputs)
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 104, in __call__
    return f.result()
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 34, in result
    ret = self._graph.result()
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 87, in result
    raise RuntimeError(errs)
RuntimeError: Node-ann-search/faiss-index-2 runs failed, error msg: '-1', Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 156, in _call
    return True, self._op(*inputs), None
  File "/Users/javayou/.towhee/operators/ann-search/faiss-index/versions/main/faiss_search.py", line 46, in __call__
    meta_data = [self._meta.get(str(i)) for i in ids]
  File "/Users/javayou/.towhee/operators/ann-search/faiss-index/versions/main/faiss_search.py", line 46, in <listcomp>
    meta_data = [self._meta.get(str(i)) for i in ids]
  File "/Users/javayou/.towhee/operators/ann-search/faiss-index/versions/main/faiss_search.py", line 17, in get
    return self._data[i]
KeyError: '-1'
```

**Comment by winter-lau** [comment]
run it again , other error occured:

```
% python3 demo.py
Exception ignored in: <function ToFaiss.__del__ at 0x124641c60>
Traceback (most recent call last):
  File "/Users/javayou/.towhee/operators/ann-insert/faiss-index/versions/main/to_faiss.py", line 57, in __del__
    faiss.write_index(self._index, self._index_file)
AttributeError: 'ToFaiss' object has no attribute '_index'
Traceback (most recent call last):
  File "/Users/javayou/Projects/towhee-demo/demo.py", line 12, in <module>
    .output()
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/pipeline.py", line 116, in output
    run_pipe.preload()
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 140, in preload
    return _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 64, in __init__
    self.initialize()
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 75, in initialize
    raise RuntimeError(node.err_msg)
RuntimeError: Node-ann-insert/faiss-index-3 runs failed, error msg: Create ann-insert/faiss-index-3 operator ann-insert/faiss-index:main with args ('./faiss', 512) and kws None failed, err: 'ToFaiss' object has no attribute '_index', Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
    self._op = self._op_pool.acquire_op(
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 147, in load_operator
    op = factory(function, arg, kws, tag)
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 130, in _load_operator_from_hub
    return self._load_operator_from_path(path, function, arg, kws)
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 118, in _load_operator_from_path
    return self._instance_operator(op, arg, kws) if op is not None else None
  File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 156, in _instance_operator
    return op(*arg, **kws) if kws is not None else op(*arg)
  File "/Users/javayou/.towhee/operators/ann-insert/faiss-index/versions/main/__init__.py", line 4, in faiss_index
    return ToFaiss(*args, **kwargs)
  File "/Users/javayou/.towhee/operators/ann-insert/faiss-index/versions/main/to_faiss.py", line 39, in __init__
    self._index = faiss.read_index(self._index)
AttributeError: 'ToFaiss' object has no attribute '_index'
```

**Comment by junjiejiangjjj** [comment]
![image](https://user-images.githubusercontent.com/14136703/236616018-6ba2d96e-5def-4feb-bacd-ee0a342a1c3f.png)
Please confirm the following code, under the directory are .png images.

**Comment by winter-lau** [comment]
> 

yes, i have download some png images into this path, but the same error occurred.

**Comment by junjiejiangjjj** [comment]
I have updated the demo, please remove the local dir `faiss`, and try it
```python
from towhee import ops, pipe, DataCollection


# create image embeddings and build index
p = (
        pipe.input('file_name')
        .map('file_name', 'img', ops.image_decode.cv2())
        .map('img', 'vec', ops.image_text_embedding.clip(model_name='clip_vit_base_patch32', modality='image'))
        .map('vec', 'vec', ops.towhee.np_normalize())
        .map(('vec', 'file_name'), (), ops.ann_insert.faiss_index('./faiss', 512))
        .output()
    )

for f_name in ['https://raw.githubusercontent.com/towhee-io/towhee/main/assets/dog1.png',
               'https://raw.githubusercontent.com/towhee-io/towhee/main/assets/dog2.png',
               'https://raw.githubusercontent.com/towhee-io/towhee/main/assets/dog3.png']:
    p(f_name)

# Delete the pipeline object, make sure the faiss data is written to disk.
del p


# search image by text
decode = ops.image_decode.cv2('rgb')
p = (
    pipe.input('text')
    .map('text', 'vec', ops.image_text_embedding.clip(model_name='clip_vit_base_patch32', modality='text'))
    .map('vec', 'vec', ops.towhee.np_normalize())
    # faiss op result format:  [[id, score, [file_name], ...]
    .map('vec', 'row', ops.ann_search.faiss_index('./faiss', 3))
    .map('row', 'images', lambda x: [decode(item[2][0]) for item in x])
    .output('text', 'images')
)

DataCollection(p('a cat')).show()
```

**Comment by junjiejiangjjj** [comment]
The faiss used in the demo is only for small-scale local testing. For vector storage in production environments, Milvus (https://github.com/milvus-io/milvus) can be considered.

**Comment by junjiejiangjjj** [comment]
> run it again , other error occured:
> 
> ```
> % python3 demo.py
> Exception ignored in: <function ToFaiss.__del__ at 0x124641c60>
> Traceback (most recent call last):
>   File "/Users/javayou/.towhee/operators/ann-insert/faiss-index/versions/main/to_faiss.py", line 57, in __del__
>     faiss.write_index(self._index, self._index_file)
> AttributeError: 'ToFaiss' object has no attribute '_index'
> Traceback (most recent call last):
>   File "/Users/javayou/Projects/towhee-demo/demo.py", line 12, in <module>
>     .output()
>   File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/pipeline.py", line 116, in output
>     run_pipe.preload()
>   File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 140, in preload
>     return _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool, self._thread_pool)
>   File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 64, in __init__
>     self.initialize()
>   File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 75, in initialize
>     raise RuntimeError(node.err_msg)
> RuntimeError: Node-ann-insert/faiss-index-3 runs failed, error msg: Create ann-insert/faiss-index-3 operator ann-insert/faiss-index:main with args ('./faiss', 512) and kws None failed, err: 'ToFaiss' object has no attribute '_index', Traceback (most recent call last):
>   File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
>     self._op = self._op_pool.acquire_op(
>   File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 99, in acquire_op
>     op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag)
>   File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 147, in load_operator
>     op = factory(function, arg, kws, tag)
>   File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 130, in _load_operator_from_hub
>     return self._load_operator_from_path(path, function, arg, kws)
>   File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 118, in _load_operator_from_path
>     return self._instance_operator(op, arg, kws) if op is not None else None
>   File "/opt/homebrew/lib/python3.10/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 156, in _instance_operator
>     return op(*arg, **kws) if kws is not None else op(*arg)
>   File "/Users/javayou/.towhee/operators/ann-insert/faiss-index/versions/main/__init__.py", line 4, in faiss_index
>     return ToFaiss(*args, **kwargs)
>   File "/Users/javayou/.towhee/operators/ann-insert/faiss-index/versions/main/to_faiss.py", line 39, in __init__
>     self._index = faiss.read_index(self._index)
> AttributeError: 'ToFaiss' object has no attribute '_index'
> ```
I have fixed the error, please delete the dir: ~/.towhee/operators/ann-insert/faiss-index/versions/main/, and Towhee will download the newest code.

**Comment by winter-lau** [comment]
```
% python3 demo2.py
Downloading https://towhee.io/ann-insert/faiss-index/resolve/branch/main/to_faiss.py to /Users/javayou/.towhee/operators/ann-insert/f
<IPython.core.display.HTML object>
```

**Comment by junjiejiangjjj** [comment]
> ```python
> DataCollection(p('a cat')).show()
> ```

`DataCollection(p('a cat')).show()` works in juptyer notebook  
you can use `p('a cat').to_list()` to get the results
