### ISSUE TITLE
[Bug]: Image missing 3 required positional arguments: 'height', 'channel', and 'mode'

### ISSUE THREAD

**Issue by zhangjunqiang** [towhee-io/towhee#2526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Traceback (most recent call last):
  File "/Users/zhangjunqiang/GitHub/image-plagiarism-detect/server/src/operations/upload.py", line 11, in do_upload
    feat = model.resnet50_extract_feat(img_path)
  File "/Users/zhangjunqiang/GitHub/image-plagiarism-detect/server/src/encode.py", line 15, in resnet50_extract_feat
    feat = towhee.glob(img_path) \
  File "/usr/local/anaconda3/envs/image-plagiarism-detect/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 738, in to_list
    return self._iterable if isinstance(self._iterable, list) else list(self)
  File "/usr/local/anaconda3/envs/image-plagiarism-detect/lib/python3.8/site-packages/towhee/functional/data_collection.py", line 366, in inner
    return unary_op(x)
  File "/usr/local/anaconda3/envs/image-plagiarism-detect/lib/python3.8/site-packages/towhee/engine/factory.py", line 91, in __call__
    res = self._op(*arg, **kws)
  File "/usr/local/anaconda3/envs/image-plagiarism-detect/lib/python3.8/site-packages/towhee/engine/operator_registry.py", line 192, in wrapper_call
    return old_call(self, *args, **kws)
  File "/Users/zhangjunqiang/.towhee/operators/towhee/image_decode/main/image_decode.py", line 14, in __call__
    return self._op(image_path)
  File "/usr/local/anaconda3/envs/image-plagiarism-detect/lib/python3.8/site-packages/towhee/engine/factory.py", line 91, in __call__
    res = self._op(*arg, **kws)
  File "/Users/zhangjunqiang/.towhee/operators/image-decode/cv2/main/image_decode_cv2.py", line 72, in __call__
    return Image(bgr_cv_image, 'BGR')
TypeError: __init__() missing 3 required positional arguments: 'height', 'channel', and 'mode'

During handling of the above exception, another exception occurred:

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.6.0
- OS(Ubuntu or CentOS): MacOs 13.3.1 (a) M1
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
It looks like the towhee version is too old, please upgrade to version >= 0.9.0.

**Comment by zhangjunqiang** [comment]
import towhee
from PIL import Image


class Resnet50:
    """
    Say something about the ExampleCalass...

    Args:
        args_0 (`type`):
        ...
    """

    def resnet50_extract_feat(self, img_path):
        feat = towhee.glob(img_path) \
                     .image_decode() \
                     .image_embedding.timm(model_name='resnet50') \
                     .tensor_normalize() \
                     .to_list()
        return feat[0]

**Comment by zhangjunqiang** [comment]
It's the demo code in:
https://github.com/milvus-io/bootcamp/blob/master/solutions/image/reverse_image_search/quick_deploy/server/requirements.txt

**Comment by junjiejiangjjj** [comment]
recommended to use the latest towhee == 1.0.0rc1,  this is examples: https://github.com/towhee-io/examples/tree/main
