### ISSUE TITLE
[Bug]: The website example in eqa-insert Code Example is not efficient

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The website example in eqa-insert Code Example is not efficient.
https://towhee.io/towhee/eqa-insert
![image](https://github.com/towhee-io/towhee/assets/109071306/ff7643a6-5da3-4b7c-a9fb-9cf852a83b7e)

```
>>> p = AutoPipes.pipeline('eqa-insert', config=config)
2023-06-05 16:57:06,803 - 4304520576 - __init__.py-__init__:28 - INFO: eqa-insert not a built-in pipeline
2023-06-05 16:57:08,171 - 4304520576 - connectionpool.py-connectionpool:1003 - DEBUG: Starting new HTTPS connection (1): huggingface.co:443
2023-06-05 16:57:08,827 - 4304520576 - connectionpool.py-connectionpool:456 - DEBUG: https://huggingface.co:443 "HEAD /sentence-transformers/all-MiniLM-L6-v2/resolve/main/config.json HTTP/1.1" 200 0
2023-06-05 16:57:09,766 - 4304520576 - connectionpool.py-connectionpool:456 - DEBUG: https://huggingface.co:443 "HEAD /sentence-transformers/all-MiniLM-L6-v2/resolve/main/tokenizer_config.json HTTP/1.1" 200 0
>>> res = p('https://github.com/towhee-io/towhee/blob/main/README.md')
2023-06-05 16:57:11,744 - 11073204224 - node.py-node:167 - INFO: Begin to run Node-_input
2023-06-05 16:57:11,745 - 11090030592 - node.py-node:167 - INFO: Begin to run Node-text-loader-0
2023-06-05 16:57:11,745 - 11106856960 - node.py-node:167 - INFO: Begin to run Node-text-splitter-1
2023-06-05 16:57:11,745 - 11073204224 - node.py-node:167 - INFO: Begin to run Node-sentence-embedding/transformers-2
2023-06-05 16:57:11,745 - 11123683328 - node.py-node:167 - INFO: Begin to run Node-towhee/np-normalize-3
2023-06-05 16:57:11,746 - 11140509696 - node.py-node:167 - INFO: Begin to run Node-ann-insert/milvus-client-4
2023-06-05 16:57:11,746 - 11157336064 - node.py-node:167 - INFO: Begin to run Node-_output
2023-06-05 16:57:12,344 - 11090030592 - connectionpool.py-connectionpool:1003 - DEBUG: Starting new HTTPS connection (1): github.com:443
2023-06-05 16:57:13,344 - 11090030592 - connectionpool.py-connectionpool:456 - DEBUG: https://github.com:443 "GET /towhee-io/towhee/blob/main/README.md HTTP/1.1" 200 None
2023-06-05 16:57:13,381 - 11090030592 - url.py-url:104 - ERROR: Error fetching or processing https://github.com/towhee-io/towhee/blob/main/README.md, exeption: libmagic is unavailable. Filetype detection on file-like objects requires libmagic. Please install libmagic and try again.
2023-06-05 16:57:13,386 - 11090030592 - node.py-node:142 - INFO: text-loader-0 ends with status: NodeStatus.FAILED
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 159, in __call__
    return self._call(*inputs, profiler=False, tracer=False)[0]
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 177, in _call
    return graph(inputs), [graph.time_profiler] if profiler else None, [graph.data_queues] if tracer else None
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 116, in __call__
    return f.result()
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 34, in result
    ret = self._graph.result()
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 95, in result
    raise RuntimeError(errs)
RuntimeError: Node-text-loader-0 runs failed, error msg: list index out of range, Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 158, in _call
    return True, self._op(*inputs), None
  File "/Users/zilliz/.towhee/operators/towhee/text-loader/versions/main/loader.py", line 12, in __call__
    docs= self._from_url(data_src)
  File "/Users/zilliz/.towhee/operators/towhee/text-loader/versions/main/loader.py", line 31, in _from_url
    doc = loader.load()[0]
IndexError: list index out of range
, Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 171, in process
    self.process_step()
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/_map.py", line 63, in process_step
    assert succ, msg
AssertionError: list index out of range, Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 158, in _call
    return True, self._op(*inputs), None
  File "/Users/zilliz/.towhee/operators/towhee/text-loader/versions/main/loader.py", line 12, in __call__
    docs= self._from_url(data_src)
  File "/Users/zilliz/.towhee/operators/towhee/text-loader/versions/main/loader.py", line 31, in _from_url
    doc = loader.load()[0]
IndexError: list index out of range
```

### Expected Behavior

raise no error

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
https://towhee.io/towhee/text-loader

**Comment by NicoYuan1986** [comment]
Update:
```
2023-06-06 18:06:55,463 - 10962382848 - url.py-url:104 - ERROR: Error fetching or processing https://github.com/towhee-io/towhee/blob/main/README.md, exeption: libmagic is unavailable. Filetype detection on file-like objects requires libmagic. Please install libmagic and try again.
2023-06-06 18:06:55,466 - 10962382848 - node.py-node:142 - INFO: text-loader-0 ends with status: NodeStatus.FAILED
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ <stdin>:1 in <module>                                                                            │
│                                                                                                  │
│ /Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pip │
│ eline.py:159 in __call__                                                                         │
│                                                                                                  │
│   156 │   │   """                                                                                │
│   157 │   │   Output with ordering matching the input `DataQueue`.                               │
│   158 │   │   """                                                                                │
│ ❱ 159 │   │   return self._call(*inputs, profiler=False, tracer=False)[0]                        │
│   160 │                                                                                          │
│   161 │   def batch(self, batch_inputs):                                                         │
│   162 │   │   return self._batch(batch_inputs, profiler=False, tracer=False)[0]                  │
│                                                                                                  │
│ /Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pip │
│ eline.py:177 in _call                                                                            │
│                                                                                                  │
│   174 │   │   time_profiler = TimeProfiler(True) if profiler else TimeProfiler(False)            │
│   175 │   │   graph = _Graph(self._dag_repr.nodes, self._dag_repr.edges, self._operator_pool,    │
│   176 │   │                                                                                      │
│ ❱ 177 │   │   return graph(inputs), [graph.time_profiler] if profiler else None, [graph.data_q   │
│   178 │                                                                                          │
│   179 │   def _batch(self, batch_inputs, profiler: bool, tracer: bool, trace_edges: list = Non   │
│   180 │   │   """                                                                                │
│                                                                                                  │
│ /Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pip │
│ eline.py:116 in __call__                                                                         │
│                                                                                                  │
│   113 │                                                                                          │
│   114 │   def __call__(self, inputs: Union[Tuple, List]):                                        │
│   115 │   │   f = self.async_call(inputs)                                                        │
│ ❱ 116 │   │   return f.result()                                                                  │
│   117 │                                                                                          │
│   118 │   @property                                                                              │
│   119 │   def time_profiler(self):                                                               │
│                                                                                                  │
│ /Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pip │
│ eline.py:34 in result                                                                            │
│                                                                                                  │
│    31 │   │   self._graph = graph                                                                │
│    32 │                                                                                          │
│    33 │   def result(self):                                                                      │
│ ❱  34 │   │   ret = self._graph.result()                                                         │
│    35 │   │   self._graph.release_op()                                                           │
│    36 │   │   del self._graph                                                                    │
│    37 │   │   return ret                                                                         │
│                                                                                                  │
│ /Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pip │
│ eline.py:95 in result                                                                            │
│                                                                                                  │
│    92 │   │   │   │   if node.status == NodeStatus.FAILED:                                       │
│    93 │   │   │   │   │   errs += node.err_msg + '\n'                                            │
│    94 │   │   if errs:                                                                           │
│ ❱  95 │   │   │   raise RuntimeError(errs)                                                       │
│    96 │   │   end_edge_num = self._nodes['_output'].out_edges[0]                                 │
│    97 │   │   res = self._data_queues[end_edge_num]                                              │
│    98 │   │   self.time_profiler.record(Event.pipe_name, Event.pipe_out)                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Node-text-loader-0 runs failed, error msg: list index out of range, Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 158, in _call
    return True, self._op(*inputs), None
  File "/Users/zilliz/.towhee/operators/towhee/text-loader/versions/main/loader.py", line 12, in __call__
    docs= self._from_url(data_src)
  File "/Users/zilliz/.towhee/operators/towhee/text-loader/versions/main/loader.py", line 31, in _from_url
    doc = loader.load()[0]
IndexError: list index out of range
, Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 171, in process
    self.process_step()
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/_map.py", line 63, in process_step
    assert succ, msg
AssertionError: list index out of range, Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 158, in _call
    return True, self._op(*inputs), None
  File "/Users/zilliz/.towhee/operators/towhee/text-loader/versions/main/loader.py", line 12, in __call__
    docs= self._from_url(data_src)
  File "/Users/zilliz/.towhee/operators/towhee/text-loader/versions/main/loader.py", line 31, in _from_url
    doc = loader.load()[0]
IndexError: list index out of range

```

My libmagic version: 1.0

**Comment by junjiejiangjjj** [comment]
try this:
pip uninstall python-magic
pip install python-magic-bin

**Comment by NicoYuan1986** [comment]
Fixed!
