### ISSUE TITLE
[Bug]: Run operator question-answer failed with an Authentication Error: No API key provided

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Run operator question-answer failed with an Authentication Error: No API key provided.
https://towhee.io/prompt/template

![image](https://github.com/towhee-io/towhee/assets/109071306/50a4090e-e4cf-481a-9148-572cab9fede3)

```
>>> 
>>> an1 = p('Tell me something about Towhee', towhee_docs, []).get()[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 159, in __call__
    return self._call(*inputs, profiler=False, tracer=False)[0]
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 177, in _call
    return graph(inputs), [graph.time_profiler] if profiler else None, [graph.data_queues] if tracer else None
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 116, in __call__
    return f.result()
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 34, in result
    ret = self._graph.result()
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/runtime_pipeline.py", line 95, in result
    raise RuntimeError(errs)
RuntimeError: Node-LLM/OpenAI-1 runs failed, error msg: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details., Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 158, in _call
    return True, self._op(*inputs), None
  File "/Users/zilliz/.towhee/operators/LLM/OpenAI/versions/main/openai_chat.py", line 36, in __call__
    response = openai.ChatCompletion.create(
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/openai/api_requestor.py", line 134, in __init__
    self.api_key = key or util.default_api_key()
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
, Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 171, in process
    self.process_step()
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/_map.py", line 63, in process_step
    assert succ, msg
AssertionError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details., Traceback (most recent call last):
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/towhee/runtime/nodes/node.py", line 158, in _call
    return True, self._op(*inputs), None
  File "/Users/zilliz/.towhee/operators/LLM/OpenAI/versions/main/openai_chat.py", line 36, in __call__
    response = openai.ChatCompletion.create(
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/openai/api_requestor.py", line 134, in __init__
    self.api_key = key or util.default_api_key()
  File "/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
```

### Expected Behavior

There is no instruction or example to show where to provide an api-key.
Maybe we can give some Desription or add an instruction `openai.api_key = <YOUR-API-KEY>` in the code.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
You need to set the OpenAI API key in the environment variable,  `export OPENAI_API_KEY={api_key}`

**Comment by NicoYuan1986** [comment]
resolved.
