### ISSUE TITLE
[Bug]: No exception handle for embedding

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> embedding = p("")
ERROR:root:'str' object has no attribute 'read'
```

### Expected Behavior

when input not valid, return useful error message

### Steps To Reproduce

1 setup env and install towhee:

```python
python3 -m venv towhee-test-env
pip install -U pip
pip install towhee
```

2  into python env: python3:

``` python
from towhee import pipeline
p = pipeline('image-embedding')
embedding = p("")
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by binbinlv** [comment]
Now it is fixed with reporting error.

```
>>> embedding = p("")
2021-12-03 15:42:55,819 - 123145547739136 - map_runner.py-map_runner:58 - ERROR: 'str' object has no attribute 'read'
2021-12-03 15:42:55,819 - 123145547739136 - runner_base.py-runner_base:126 - ERROR: preprocessing:0 runs failed, error msg: 'str' object has no attribute 'read'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/__init__.py", line 73, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/pipeline.py", line 91, in __call__
    return graph_ctx.result()
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/graph_context.py", line 75, in result
    raise RuntimeError(op.err_msg)
RuntimeError: preprocessing:0 runs failed, error msg: 'str' object has no attribute 'read'
```
