### ISSUE TITLE
TypeError: constr() got an unexpected keyword argument 'regex'

### ISSUE THREAD

**Issue by gavenpeng** [towhee-io/towhee#2612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when id run the follower code:
```
from towhee import AutoPipes, AutoConfig
# get the built-in sentence_similarity pipeline
config = AutoConfig.load_config('sentence_embedding')
config.model = 'paraphrase-albert-small-v2'
config.device = 0
sentence_embedding = AutoPipes.pipeline('sentence_embedding', config=config)

# generate embedding for one sentence
embedding = sentence_embedding('how are you?').get()
# batch generate embeddings for multi-sentences
embeddings = sentence_embedding.batch(['how are you?', 'how old are you?'])
embeddings = [e.get() for e in embeddings]
```
```
happened the follower error:
/Users/nali/Library/Python/3.8/lib/python/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "towhee.python", line 1, in <module>
    from towhee import AutoPipes, AutoConfig
  File "/Users/nali/Library/Python/3.8/lib/python/site-packages/towhee/__init__.py", line 20, in <module>
    from towhee.runtime import register, pipe, ops, accelerate, AutoConfig, AutoPipes
  File "/Users/nali/Library/Python/3.8/lib/python/site-packages/towhee/runtime/__init__.py", line 17, in <module>
    from .pipeline import Pipeline as pipe
  File "/Users/nali/Library/Python/3.8/lib/python/site-packages/towhee/runtime/pipeline.py", line 18, in <module>
    from towhee.runtime.check_utils import TupleForm
  File "/Users/nali/Library/Python/3.8/lib/python/site-packages/towhee/runtime/check_utils.py", line 36, in <module>
    class TupleForm(BaseModel):
  File "/Users/nali/Library/Python/3.8/lib/python/site-packages/towhee/runtime/check_utils.py", line 38, in TupleForm
    schema_data: Optional[Tuple[constr(regex='^[a-z][a-z0-9_]*$'), ...]]
TypeError: constr() got an unexpected keyword argument 'regex
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
pydantic adjust the interface of `constr`, please reinstall it:
pip install pydantic==1.10.10

**Comment by gavenpeng** [comment]
thanks ,i do pip install pydantic==1.10.10 ,found new problem:

 If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
Successfully built pyyaml
Failed to build safetensors tokenizers
ERROR: Could not build wheels for safetensors, tokenizers, which is required to install pyproject.toml-based projects
2023-07-05 15:56:43,136 - 4306025792 - operator_loader.py-operator_loader:134 - ERROR: Command '['/Library/Developer/CommandLineTools/usr/bin/python3', '-m', 'pip', 'install', '-r', PosixPath('/Users/nali/.towhee/operators/sentence-embedding/transformers/versions/main/requirements.txt')]' returned non-zero exit status 1., Traceback (most recent call last):
  File "/Users/nali/Library/Python/3.8/lib/python/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 131, in _load_operator_from_hub
    path = get_operator(operator=function, tag=tag, latest=latest)
  File "/Users/nali/Library/Python/3.8/lib/python/site-packages/towhee/hub/__init__.py", line 23, in get_operator
    return _CACHE_MANAGER.get_operator(operator, tag, install_reqs, latest)
  File "/Users/nali/Library/Python/3.8/lib/python/site-packages/towhee/hub/cache_manager.py", line 97, in get_operator
    download_operator(author, repo, tag, download_path, install_reqs, latest)
  File "/Users/nali/Library/Python/3.8/lib/python/site-packages/towhee/hub/downloader.py", line 178, in download_operator
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-r', fs.requirements])
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Developer/CommandLineTools/usr/bin/python3', '-m', 'pip', 'install', '-r', PosixPath('/Users/nali/.towhee/operators/sentence-embedding/transformers/versions/main/requirements.txt')]' returned non-zero exit status 1.

2023-07-05 15:56:43,137 - 4306025792 - factory.py-factory:118 - ERROR: Loading operator with error:Load operator failed

**Comment by gavenpeng** [comment]
running build_ext
      running build_rust
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
not find rust compiler,  is need install rust?

**Comment by junjiejiangjjj** [comment]
if your Python env doesn't match the existing packages: https://pypi.org/project/tokenizers/0.13.3/#files, it will build from source code and need Rust compiler

**Comment by xxxmoonquake-dxq** [comment]
请问您最终是怎么解决的，我更新了towhee和pydantic还是没用

**Comment by junjiejiangjjj** [comment]
Downgrade pydantic to a version lower than 2.0
