### ISSUE TITLE
[Bug]: triton/pipeline_client: RuntimeError: no running event loop

### ISSUE THREAD

**Issue by abysshal** [towhee-io/towhee#2714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

按照文档说明，调用 tritonserver 推理时报错：
```
from towhee import triton_client
client = triton_client.Client(url='127.0.0.1:8000')
res = client(text_to_search)
```

报错内容如下：
```
Traceback (most recent call last):
  File "/home/ubuntu/docker/app_search/test2.py", line 2, in <module>
    client = triton_client.Client(url='127.0.0.1:8000')
  File "/home/ubuntu/miniconda3/envs/py39/lib/python3.9/site-packages/towhee/serve/triton/pipeline_client.py", line 56, in __init__
    self._client = aio_httpclient.InferenceServerClient(url)
  File "/home/ubuntu/miniconda3/envs/py39/lib/python3.9/site-packages/tritonclient/http/aio/__init__.py", line 116, in __init__
    self._conn = aiohttp.TCPConnector(ssl=ssl_context, limit=conn_limit)
  File "/home/ubuntu/miniconda3/envs/py39/lib/python3.9/site-packages/aiohttp/connector.py", line 851, in __init__
    super().__init__(
  File "/home/ubuntu/miniconda3/envs/py39/lib/python3.9/site-packages/aiohttp/connector.py", line 258, in __init__
    loop = loop or asyncio.get_running_loop()
RuntimeError: no running event loop
Exception ignored in: <function Client.__del__ at 0x7b970a750430>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/py39/lib/python3.9/site-packages/towhee/serve/triton/pipeline_client.py", line 114, in __del__
    self.close()
  File "/home/ubuntu/miniconda3/envs/py39/lib/python3.9/site-packages/towhee/serve/triton/pipeline_client.py", line 100, in close
    self._loop.run_until_complete(self._client.close())
AttributeError: 'Client' object has no attribute '_client'
```

仅使用 conda 安装了 python==3.9 环境，和 towhee==1.1.3，安装包如下：
```
Successfully installed aiohappyeyeballs-2.4.4 aiohttp-3.11.9 aiosignal-1.3.1 async-timeout-5.0.1 attrs-24.2.0 brotli-1.1.0 frozenlist-1.5.0 gevent-24.11.1 geventhttpclient-2.3.3 greenlet-3.1.1 multidict-6.1.0 numpy-1.26.4 propcache-0.2.1 python-rapidjson-1.20 tritonclient-2.52.0 yarl-1.18.3 zope.event-5.0 zope.interface-7.2
tritonclient[http] installed successfully!
```

### Expected Behavior

能正常连接到 tritonserver 并完成推理任务。

### Steps To Reproduce

```markdown
1. conda create -n py392 python==3.9
2. pip install towhee==1.1.3 towhee.models==1.1.3
3. python test.py (code见上面，就三行)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 1.1.3
- OS(Ubuntu or CentOS): ubuntu 22.04
- CPU/Memory:
- GPU:
- Others: python==3.9
```

**Comment by junjiejiangjjj** [comment]
hi @abysshal , before using triton_client, create an event loop by this code
```python
 try:
        loop = asyncio.get_event_loop()
    except:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

**Comment by abysshal** [comment]
> hi @abysshal , before using triton_client, create an event loop by this code
> 
> ```python
>  try:
>         loop = asyncio.get_event_loop()
>     except:
>         loop = asyncio.new_event_loop()
>         asyncio.set_event_loop(loop)
> ```

感谢回复，我简单快速的测试了一下，仍旧是报相同的错误，测试代码如下：
```
from towhee import triton_client
import asyncio

try:
    loop = asyncio.get_event_loop()
except:
    print('failed to get_event_loop()')
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)

print(loop)
client = triton_client.Client(url='127.0.0.1:8010')
res = client('dog')
print(res)
```

但是你的回复让我了解到仅靠文档里展示的几行示例代码可能是无法直接搞定的，我会学习`asyncio`库，添加更多的上下文环境，尝试搞定 调用tritronserver 推理的这个例子的。

**Comment by junjiejiangjjj** [comment]
Check if the version of this dependent library is correct： aiohttp==3.9.5

**Comment by abysshal** [comment]
> Check if the version of this dependent library is correct： aiohttp==3.9.5

原来默认安装的是 aiohttp==3.11.9版本，当重新安装 3.9.5 版本后，问题解决了。甚至只要三行也能运行了：
```
from towhee import triton_client
client = triton_client.Client(url='127.0.0.1:8000')
res = client(text_to_search)
```
