### ISSUE TITLE
[Bug]:  Embedding failed with pipeline 'shiyu/img_object_embedding_pytorch_yolov5_resnet50' (lack of "seaborn" module)

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> from towhee import pipeline
>>> from PIL import Image
>>> img_path = '/Users/binbin/Towhee_projects/2021825-19039.jpg'
>>> img_path = '/Users/binbin/Towhee_projects/2021825-19039.jpg'
>>> embedding_pipeline = pipeline('shiyu/img_object_embedding_pytorch_yolov5_resnet50')
>>> embedding = embedding_pipeline(img_path)
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to /Users/binbin/.cache/torch/hub/master.zip
No module named 'seaborn'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/__init__.py", line 78, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/pipeline.py", line 111, in __call__
    graph_ctx.outputs.wait_sealed()
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/dataframe/dataframe.py", line 156, in wait_sealed
    self._seal_cv.wait()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
```

### Expected Behavior

Embedding successfully

### Steps To Reproduce

```markdown
from towhee import pipeline
from PIL import Image
img_path = '/Users/binbin/Towhee_projects/2021825-19039.jpg'
embedding_pipeline = pipeline('shiyu/img_object_embedding_pytorch_yolov5_resnet50')
embedding = embedding_pipeline(img_path)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.2.2
- OS(Ubuntu or CentOS): mac
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by shiyu22** [comment]
Hi @binbinlv , you can try to install seaborn by running `python -m pip install seaborn`, [refer to it](https://stackoverflow.com/questions/54116693/modulenotfounderror-no-module-named-seaborn-in-python-ide).

**Comment by binbinlv** [comment]
@shiyu22 when install "seaborn" manually, it works.

Could you please help to handle this module? Thanks.

**Comment by shiyu22** [comment]
I have added seaborn on [requirements.txt](https://hub.towhee.io/shiyu/pytorch_yolov5_coco/src/branch/main/requirements.txt), you can test it again.

**Comment by binbinlv** [comment]
Verified, and fixed.
