### ISSUE TITLE
[Bug]: Embedding is failed for pipeline "'shiyu/img_object_embedding_pytorch_yolov5_resnet50'"

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Embedding is empty for pipeline "'shiyu/img_object_embedding_pytorch_yolov5_resnet50'"
```
>>> from towhee import pipeline
>>> from PIL import Image
>>> img_path = '/Users/binbin/towhee/docs/towhee_logo.png'
>>> embedding_pipeline = pipeline('shiyu/img_object_embedding_pytorch_yolov5_resnet50')
>>> embedding = embedding_pipeline(img_path)
Using cache found in /Users/binbin/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2021-12-1 torch 1.10.0 CPU

Fusing layers...
Model Summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape...
/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
>>>
>>>
>>> embedding
[]
```

### Expected Behavior

Embedding vector is created

### Steps To Reproduce

```markdown
from towhee import pipeline
from PIL import Image
img_path = '/Users/binbin/towhee/docs/towhee_logo.png'
embedding_pipeline = pipeline('shiyu/img_object_embedding_pytorch_yolov5_resnet50')
embedding = embedding_pipeline(img_path)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.2.2
- OS(Ubuntu or CentOS): mac
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by binbinlv** [comment]
Update:

using latest towhee version: 

it reports "RuntimeError: Unkown error".

```
>>> from towhee import pipeline
>>> from PIL import Image
>>> img_path = '/Users/binbin/towhee/docs/towhee_logo.png'
>>> embedding_pipeline = pipeline('shiyu/img_object_embedding_pytorch_yolov5_resnet50')
>>> embedding = embedding_pipeline(img_path)
/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/__init__.py", line 73, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/pipeline.py", line 91, in __call__
    return graph_ctx.result()
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/graph_context.py", line 76, in result
    raise RuntimeError('Unkown error')
RuntimeError: Unkown error
```

**Comment by shiyu22** [comment]
This is an issue of exception handling in the Towhee framework. In the feature, we will add some specific exception types. Now they are all runtime exceptions. In the latter case without results, it will throw NoDataException.

BTW, Towhee will throw some error conditions through exceptions in v1.0. And the users for the pipeline can decide how to deal with the exception after catching the exception.

**Comment by binbinlv** [comment]
OK, and the error reported which is not friendly is actually another issue.

This issue which I means is I want the logo image could be embedded successfully. But through discussion, this model is not supported this logo image, and which is not the pipeline issue. 

And embedding is successfully when replacing a cat image, so close it.

Thanks.
