### ISSUE TITLE
[Bug]: audio pipeline test:"Dependency package error" when input audio path need to generate vectors

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

python version：3.8
towhee version：0.3.1.dev18
pipeline scripts:

```
>>> from towhee import pipeline
>>> embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
>>> embedding = embedding_pipeline('/Users/jingjing/Workspace/audio')

```

error log:
```
Successfully installed absl-py-1.0.0 astunparse-1.6.3 cachetools-4.2.4 flatbuffers-2.0 gast-0.4.0 google-auth-2.3.3 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 grpcio-1.43.0 h5py-3.6.0 importlib-metadata-4.10.0 keras-2.7.0 keras-preprocessing-1.1.2 libclang-12.0.0 llvmlite-0.37.0 markdown-3.3.6 numba-0.54.1 numpy-1.20.3 oauthlib-3.1.1 opt-einsum-3.3.0 protobuf-3.19.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-oauthlib-1.3.0 resampy-0.2.2 rsa-4.8 tensorboard-2.7.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 tensorflow-2.7.0 tensorflow-estimator-2.7.0 tensorflow-hub-0.12.0 tensorflow-io-gcs-filesystem-0.23.1 termcolor-1.1.0 werkzeug-2.0.2 wrapt-1.13.3 zipp-3.6.0
2021-12-24 16:16:50,946 - 123145479544832 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/thread_pool_task_executor.py", line 69, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id,
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/operator_pool.py", line 95, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 71, in load_operator
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jingjing/.towhee/operators/tf_vggish_audioset&towhee$main/tf_vggish_audioset.py", line 17, in <module>
    import resampy
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/resampy/__init__.py", line 7, in <module>
    from .core import *
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/resampy/core.py", line 9, in <module>
    from .interpn import resample_f
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/resampy/interpn.py", line 4, in <module>
    import numba
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/numba/__init__.py", line 198, in <module>
    _ensure_critical_deps()
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/numba/__init__.py", line 138, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.20 or less")
ImportError: Numba needs NumPy 1.20 or less

2021-12-24 16:16:50,946 - 123145479544832 - thread_pool_task_executor.py-thread_pool_task_executor:78 - ERROR: Numba needs NumPy 1.20 or less
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/__init__.py", line 66, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/pipeline.py", line 93, in __call__
    graph_ctx.join()
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/graph_context.py", line 95, in join
    op.join()
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/operator_context.py", line 137, in join
    runner.join()
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/operator_runner/runner_base.py", line 190, in join
    self._end_event.wait()
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by jaelgu** [comment]
The input should be a wav audio path instead of folder. Will update pipeline README in hub.
