### ISSUE TITLE
[Bug]: audio pipeline test:"Error loading audio file"Input audio path, it should report error of input folder

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

python verison:3.8
towhee version:0.3.1.dev18
pipeline:
```
>>> from towhee import pipeline
>>> embedding_pipeline = pipeline('towhee/audio-embedding-clmr')
Downloading audio_embedding_clmr.yaml: 100%|████████████████████████████████████████████████████████████████████████████| 1.45k/1.45k [00:00<00:00, 407kiB/s]
Downloading README.md: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 1.61k/1.61k [00:00<00:00, 388kiB/s]
>>> embedding = embedding_pipeline('/Users/jingjing/Workspace/audio')
```
error log:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.11.2 requires torch==1.10.1, but you have torch 1.9.0 which is incompatible.
Successfully installed cffi-1.15.0 pycparser-2.21 soundfile-0.10.3.post1 torch-1.9.0 torchaudio-0.9.0
formats: can't open input file `./tmp/a_22050.wav': No such file or directory
2021-12-24 16:04:54,975 - 123145479544832 - runner_base.py-runner_base:128 - ERROR: embedding_model:0 runs failed, error msg: Error loading audio file: failed to open file ./tmp/a_22050.wav, Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/operator_runner/runner_base.py", line 154, in _call_op
    outputs = self._op(**inputs)
  File "/Users/jingjing/.towhee/operators/clmr_magnatagatune&towhee$main/clmr_magnatagatune.py", line 62, in __call__
    audio, _ = torchaudio.load(target)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 152, in load
    return torch.ops.torchaudio.sox_io_load_audio_file(
RuntimeError: Error loading audio file: failed to open file ./tmp/a_22050.wav

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/__init__.py", line 66, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/pipeline.py", line 94, in __call__
    return graph_ctx.result()
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/graph_context.py", line 77, in result
    raise OpFailedError(op.err_msg)
towhee.errors.OpFailedError: embedding_model:0 runs failed, error msg: Error loading audio file: failed to open file ./tmp/a_22050.wav, Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/operator_runner/runner_base.py", line 154, in _call_op
    outputs = self._op(**inputs)
  File "/Users/jingjing/.towhee/operators/clmr_magnatagatune&towhee$main/clmr_magnatagatune.py", line 62, in __call__
    audio, _ = torchaudio.load(target)
  File "/Users/jingjing/miniconda3/envs/towhee/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 152, in load
    return torch.ops.torchaudio.sox_io_load_audio_file(
RuntimeError: Error loading audio file: failed to open file ./tmp/a_22050.wav
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by jingkl** [comment]
![Uploading 截屏2021-12-24 下午4.31.24.png…]()

**Comment by jingkl** [comment]
Hopefully, like image pipeline, it will report an error showing the input folder
```
>>> embedding = embedding_pipeline('/Users/binbin/Towhee_projects')
2021-12-24 16:56:13,312 - 123145469521920 - runner_base.py-runner_base:128 - ERROR: preprocessing:0 runs failed, error msg: [Errno 21] Is a directory: '/Users/binbin/Towhee_projects', Traceback (most recent call last):
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/operator_runner/runner_base.py", line 154, in _call_op
    outputs = self._op(**inputs)
  File "/Users/binbin/.towhee/operators/pytorch_transform_operator&towhee$main/pytorch_transform_operator.py", line 48, in __call__
    img_tensor = Image.open(img_tensor)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/PIL/Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/Users/binbin/Towhee_projects'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/__init__.py", line 66, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/pipeline.py", line 94, in __call__
    return graph_ctx.result()
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/graph_context.py", line 77, in result
    raise OpFailedError(op.err_msg)
towhee.errors.OpFailedError: preprocessing:0 runs failed, error msg: [Errno 21] Is a directory: '/Users/binbin/Towhee_projects', Traceback (most recent call last):
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/operator_runner/runner_base.py", line 154, in _call_op
    outputs = self._op(**inputs)
  File "/Users/binbin/.towhee/operators/pytorch_transform_operator&towhee$main/pytorch_transform_operator.py", line 48, in __call__
    img_tensor = Image.open(img_tensor)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/PIL/Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/Users/binbin/Towhee_projects'
```

**Comment by jingkl** [comment]
The error report shows that the file name and the file name of the dataset should be one by one
