### ISSUE TITLE
[Enhancement]: Should be more elegant to handle exceptions

### ISSUE THREAD

**Issue by shanghaikid** [towhee-io/towhee#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

This is not user friendly.  
```
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /Users/ryjiang/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:05<00:00, 18.1MB/s]
Traceback (most recent call last):
  File "index.py", line 9, in <module>
    output = embedding_pipeline('towhee_logo.png')
  File "/usr/local/lib/python3.7/site-packages/towhee/__init__.py", line 73, in __call__
    out_df = self._pipeline(in_df)
  File "/usr/local/lib/python3.7/site-packages/towhee/engine/pipeline.py", line 91, in __call__
    return graph_ctx.result()
  File "/usr/local/lib/python3.7/site-packages/towhee/engine/graph_context.py", line 75, in result
    raise RuntimeError(op.err_msg)
RuntimeError: preprocessing:0 runs failed, error msg: [Errno 2] No such file or directory: 'towhee_logo.png'

```

### Why is this needed?

- Prevents program from crashing if an error occurs
- Better error message could save a lot of time for developers to debug

**Comment by jingkl** [comment]
<img width="1431" alt="截屏2021-12-27 下午2 59 42" src="https://user-images.githubusercontent.com/34296482/147447367-b24b55b9-e426-497c-b030-8d0b94666710.png">

**Comment by fzliu** [comment]
Potential duplicate: #336
