### ISSUE TITLE
[Bug]: Test audio pipeline "towhee/audio-embedding-clmr", no vectors can be generated

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Test scripts：
```
>>> from towhee import pipeline
>>> audio_path='/Users/jingjing/Workspace/audio/arms_strikes.wav'
>>> embedding_pipeline = pipeline('towhee/audio-embedding-clmr')
>>> embedding = embedding_pipeline(audio_path)
```
<img width="1430" alt="截屏2021-12-27 下午7 17 22" src="https://user-images.githubusercontent.com/34296482/147467061-75fe6acf-71a8-4cb9-848a-d1619c8b6575.png">
<img width="1437" alt="截屏2021-12-27 下午7 23 37" src="https://user-images.githubusercontent.com/34296482/147467285-d3ec2921-5cd5-4692-b364-c1f8b5dbee51.png">
<img width="1434" alt="截屏2021-12-27 下午7 23 45" src="https://user-images.githubusercontent.com/34296482/147467294-53561516-d7f6-4076-8187-f941be694158.png">
<img width="1430" alt="截屏2021-12-27 下午7 23 57" src="https://user-images.githubusercontent.com/34296482/147467303-5ea8c491-f862-4051-8e7e-01173365a636.png">
<img width="1420" alt="截屏2021-12-27 下午7 24 05" src="https://user-images.githubusercontent.com/34296482/147467310-9ff0a309-8517-49e0-8eae-605e9a822675.png">

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.3.1dev19
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
@jingkl Just updated README and added `ffmpeg` in requirements.txt. Please test again.

**Comment by jingkl** [comment]
The second test, with ffmpeg already installed, still exploded with the error shown above
<img width="1440" alt="截屏2021-12-27 下午9 13 37" src="https://user-images.githubusercontent.com/34296482/147475150-7c421f42-d587-4a0f-b9f7-27b7f293e1ed.png">
<img width="1439" alt="截屏2021-12-27 下午9 13 23" src="https://user-images.githubusercontent.com/34296482/147475161-8d6aeff3-befe-4d9f-b376-2db83c6982ed.png">
<img width="1438" alt="截屏2021-12-27 下午9 13 13" src="https://user-images.githubusercontent.com/34296482/147475232-828726c8-1860-4a9a-9b44-d77442edf432.png">

**Comment by jingkl** [comment]
the third test：
<img width="1436" alt="截屏2021-12-27 下午9 40 17" src="https://user-images.githubusercontent.com/34296482/147477255-cd0afff1-6b79-4cc1-93bf-26aa9c655ed8.png">

**Comment by jaelgu** [comment]
> the third test： <img alt="截屏2021-12-27 下午9 40 17" width="1436" src="https://user-images.githubusercontent.com/34296482/147477255-cd0afff1-6b79-4cc1-93bf-26aa9c655ed8.png">

Added numpy in requirements.txt

**Comment by binbinlv** [comment]
Same error on python3 env.

python3: 3.8.2

Steps:
1. pip3 install towhee
2. brew install ffmpeg
3. in python3 terminal:
```python3
from towhee import pipeline
embedding_pipeline = pipeline('towhee/audio-embedding-clmr')
embedding = embedding_pipeline(embedding_pipeline("/Users/binbin/Towhee_projects/example_audio/arms_strikes.wav")
```

**Comment by binbinlv** [comment]
And similar error on Ubutu OS.
python3:  3.9.7

```
>>> from towhee import pipeline
>>> embedding_pipeline = pipeline('towhee/audio-embedding-clmr')
Downloading README.md: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.73k/1.73k [00:00<00:00, 764kiB/s]
Downloading audio_embedding_clmr.yaml: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1.45k/1.45k [00:00<00:00, 666kiB/s]
>>>
>>> embedding = embedding_pipeline("/home/zong/binbin/data/example_audio/arms_strikes.wav")
Downloading clmr_magnatagatune.py: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 2.91k/2.91k [00:00<00:00, 5.05MiB/s]
Downloading models/sample_cnn.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 1.88k/1.88k [00:00<00:00, 903kiB/s]
Downloading requirements.txt: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 47.0/47.0 [00:00<00:00, 4.99kiB/s]
Downloading utils/.DS_Store: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.15k/6.15k [00:00<00:00, 257kiB/s]
Downloading __init__.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 592/592 [00:00<00:00, 15.1kiB/s]
Downloading utils/checkpoint.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 1.26k/1.26k [00:00<00:00, 59.8kiB/s]
Downloading models/model.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 555/555 [00:00<00:00, 34.0kiB/s]
Downloading models/__init__.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.00/1.00 [00:00<00:00, 29.9iB/s]
Downloading utils/__init__.py: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.00/1.00 [00:00<00:00, 117iB/s]
Downloading utils/yaml_config_hook.py: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 709/709 [00:00<00:00, 333kiB/s]
Downloading README.md: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.46k/1.46k [00:00<00:00, 665kiB/s]
Downloading checkpoints/clmr_checkpoint_10000.pt: 100%|█████████████████████████████████████████████████████████████████████████████████████| 10.8M/10.8M [00:01<00:00, 8.18MiB/s]
Collecting torchaudio==0.9.0
  Downloading torchaudio-0.9.0-cp39-cp39-manylinux1_x86_64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 1.6 MB/s
Collecting torch==1.9.0
  Downloading torch-1.9.0-cp39-cp39-manylinux1_x86_64.whl (831.4 MB)
     |████████████████████████████████| 831.4 MB 23 kB/s
Collecting soundfile
  Downloading SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
Collecting numpy
  Downloading numpy-1.21.5-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 18.4 MB/s
Collecting typing-extensions
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting cffi>=1.0
  Downloading cffi-1.15.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (444 kB)
     |████████████████████████████████| 444 kB 19.0 MB/s
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 21.3 MB/s
Installing collected packages: typing-extensions, pycparser, torch, cffi, torchaudio, soundfile, numpy
Successfully installed cffi-1.15.0 numpy-1.21.5 pycparser-2.21 soundfile-0.10.3.post1 torch-1.9.0 torchaudio-0.9.0 typing-extensions-4.0.1
2021-12-28 10:07:17,351 - 140411192329984 - runner_base.py-runner_base:128 - ERROR: embedding_model:0 runs failed, error msg: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /pytorch/build/aten/src/ATen/RegisterCPU.cpp:16286 [kernel]
CUDA: registered at /pytorch/build/aten/src/ATen/RegisterCUDA.cpp:20674 [kernel]
QuantizedCPU: registered at /pytorch/build/aten/src/ATen/RegisterQuantizedCPU.cpp:1025 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
ADInplaceOrView: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:60 [backend fallback]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradMLC: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradHPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradNestedTensor: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_2.cpp:9621 [kernel]
Autocast: registered at /pytorch/aten/src/ATen/autocast_mode.cpp:259 [kernel]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:1019 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
, Traceback (most recent call last):
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 154, in _call_op
    outputs = self._op(**inputs)
  File "/home/zong/.towhee/operators/clmr_magnatagatune&towhee$main/clmr_magnatagatune.py", line 70, in __call__
    batch = torch.cat(batch[:-1])
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /pytorch/build/aten/src/ATen/RegisterCPU.cpp:16286 [kernel]
CUDA: registered at /pytorch/build/aten/src/ATen/RegisterCUDA.cpp:20674 [kernel]
QuantizedCPU: registered at /pytorch/build/aten/src/ATen/RegisterQuantizedCPU.cpp:1025 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
ADInplaceOrView: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:60 [backend fallback]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradMLC: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradHPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradNestedTensor: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_2.cpp:9621 [kernel]
Autocast: registered at /pytorch/aten/src/ATen/autocast_mode.cpp:259 [kernel]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:1019 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/towhee/__init__.py", line 69, in __call__
    out_df = self._pipeline(in_df)
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/towhee/engine/pipeline.py", line 94, in __call__
    return graph_ctx.result()
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/towhee/engine/graph_context.py", line 77, in result
    raise OpFailedError(op.err_msg)
towhee.errors.OpFailedError: embedding_model:0 runs failed, error msg: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /pytorch/build/aten/src/ATen/RegisterCPU.cpp:16286 [kernel]
CUDA: registered at /pytorch/build/aten/src/ATen/RegisterCUDA.cpp:20674 [kernel]
QuantizedCPU: registered at /pytorch/build/aten/src/ATen/RegisterQuantizedCPU.cpp:1025 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
ADInplaceOrView: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:60 [backend fallback]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradMLC: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradHPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradNestedTensor: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_2.cpp:9621 [kernel]
Autocast: registered at /pytorch/aten/src/ATen/autocast_mode.cpp:259 [kernel]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:1019 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
, Traceback (most recent call last):
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 154, in _call_op
    outputs = self._op(**inputs)
  File "/home/zong/.towhee/operators/clmr_magnatagatune&towhee$main/clmr_magnatagatune.py", line 70, in __call__
    batch = torch.cat(batch[:-1])
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

CPU: registered at /pytorch/build/aten/src/ATen/RegisterCPU.cpp:16286 [kernel]
CUDA: registered at /pytorch/build/aten/src/ATen/RegisterCUDA.cpp:20674 [kernel]
QuantizedCPU: registered at /pytorch/build/aten/src/ATen/RegisterQuantizedCPU.cpp:1025 [kernel]
BackendSelect: fallthrough registered at /pytorch/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Named: registered at /pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
ADInplaceOrView: fallthrough registered at /pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:60 [backend fallback]
AutogradOther: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradCPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradCUDA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradXLA: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
UNKNOWN_TENSOR_TYPE_ID: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradMLC: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradHPU: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradNestedTensor: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse1: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse2: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
AutogradPrivateUse3: registered at /pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:9928 [autograd kernel]
Tracer: registered at /pytorch/torch/csrc/autograd/generated/TraceType_2.cpp:9621 [kernel]
Autocast: registered at /pytorch/aten/src/ATen/autocast_mode.cpp:259 [kernel]
Batched: registered at /pytorch/aten/src/ATen/BatchingRegistrations.cpp:1019 [backend fallback]
VmapMode: fallthrough registered at /pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
```

**Comment by jingkl** [comment]
Need to add a note in the readme file about the size of the file, testing small audio files did not pass

**Comment by jaelgu** [comment]
> Need to add a note in the readme file about the size of the file, testing small audio files did not pass /assign @jaelgu

done: https://towhee.io/towhee/audio-embedding-clmr
