### ISSUE TITLE
[Bug]: Audio pipeline "towhee/audio-embedding-vggish" reporting not proper error when embedding with not existed file

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When embedding within audio pipeline "towhee/audio-embedding-vggish", it reports:
```
>>> embedding = embedding_pipeline("/Users/binbin/Towhee_projects/example_audio/queen_love_of_my_life.wav")
2021-12-28 10:23:12,160 - 140242476586752 - runner_base.py-runner_base:128 - ERROR: embedding_model:0 runs failed, error msg: Error opening '/Users/binbin/Towhee_projects/example_audio/queen_love_of_my_life.wav': System error., Traceback (most recent call last):
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 154, in _call_op
    outputs = self._op(**inputs)
  File "/home/zong/.towhee/operators/tf_vggish_audioset&towhee$main/tf_vggish_audioset.py", line 43, in __call__
    wav_data, sr = sf.read(filepath, dtype='int16')
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/soundfile.py", line 256, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/Users/binbin/Towhee_projects/example_audio/queen_love_of_my_life.wav': System error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/towhee/__init__.py", line 69, in __call__
    out_df = self._pipeline(in_df)
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/towhee/engine/pipeline.py", line 94, in __call__
    return graph_ctx.result()
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/towhee/engine/graph_context.py", line 77, in result
    raise OpFailedError(op.err_msg)
towhee.errors.OpFailedError: embedding_model:0 runs failed, error msg: Error opening '/Users/binbin/Towhee_projects/example_audio/queen_love_of_my_life.wav': System error., Traceback (most recent call last):
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 154, in _call_op
    outputs = self._op(**inputs)
  File "/home/zong/.towhee/operators/tf_vggish_audioset&towhee$main/tf_vggish_audioset.py", line 43, in __call__
    wav_data, sr = sf.read(filepath, dtype='int16')
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/soundfile.py", line 256, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "/home/zong/binbin/towhee-test-env/lib/python3.9/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/Users/binbin/Towhee_projects/example_audio/queen_love_of_my_life.wav': System error.
```

### Expected Behavior

Reporting like "file not found"

### Steps To Reproduce

```markdown
1. pip install towhee==0.4.0rc1
2. in python3 terminal:

from towhee import pipeline
embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
embedding = embedding_pipeline("/Users/binbin/Towhee_projects/example_audio/arms_strikes.wav")
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.4.0rc1
- OS(Ubuntu or CentOS):Ubuntu
- Python: 3.9.7
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
duplicate #347
