### ISSUE TITLE
[Bug]: Torchvision stated in requirements.txt is too low.

### ISSUE THREAD

**Issue by haorenfsa** [towhee-io/towhee#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error when embedding image with tutorial.

``` python
>>> output = embedding_pipeline('towhee.jpeg')
2021-12-28 14:51:10,457 - 123145613156352 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/site-packages/towhee/engine/thread_pool_task_executor.py", line 69, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id,
  File "/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/site-packages/towhee/engine/operator_pool.py", line 95, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 71, in load_operator
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/zilliz/.towhee/operators/resnet_image_embedding&towhee$main/resnet_image_embedding.py", line 23, in <module>
    from torchvision.transforms import InterpolationMode
ImportError: cannot import name 'InterpolationMode' from 'torchvision.transforms' (/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/site-packages/torchvision/transforms/__init__.py)

2021-12-28 14:51:10,457 - 123145613156352 - thread_pool_task_executor.py-thread_pool_task_executor:78 - ERROR: cannot import name 'InterpolationMode' from 'torchvision.transforms' (/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/site-packages/torchvision/transforms/__init__.py)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/site-packages/towhee/__init__.py", line 69, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/site-packages/towhee/engine/pipeline.py", line 93, in __call__
    graph_ctx.join()
  File "/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/site-packages/towhee/engine/graph_context.py", line 95, in join
    op.join()
  File "/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/site-packages/towhee/engine/operator_context.py", line 137, in join
    runner.join()
  File "/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/site-packages/towhee/engine/operator_runner/runner_base.py", line 190, in join
    self._end_event.wait()
  File "/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/zilliz/opt/miniconda3/envs/run-towhee/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
```

### Expected Behavior

 No error

### Steps To Reproduce

```markdown
1. Preinstall torchvision <=0.8.0 before install towhee
2. `pip install towhee`
3. Follow the official [tutorial](https://docs.towhee.io/get-started/quick-start/#running-your-first-pipeline)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.4.0rc1
- OS(Ubuntu or CentOS): mac
- CPU/Memory:
- GPU:
- Others:
```

### Anything else?

`torchvision.transforms.InterpolationMode` is not added until v0.9.0. We didn't state it in the requirements.txt. There may also be same  problems with with numpy, torch, pandas.

**Comment by haorenfsa** [comment]
I'm also curious about why we removed other dependencies in #308, which seems essential for the tutorial steps to run

**Comment by fzliu** [comment]
These dependencies were added into individual operators; the `requirements.txt` file in the main repo is for Towhee-specific requirements. @shiyu22 @Chiiizzzy can you guys take a look at this?

**Comment by haorenfsa** [comment]
So the problem becomes that the `operator loader` managed to install the requirements of the operator if not install, but fail to update it if it's in lower version.

**Comment by fzliu** [comment]
@shiyu22 I think this may be related to #327. Can you double-check?

**Comment by jaelgu** [comment]
@haorenfsa Can you try with this:
1. manually delete ~/.towhee/operators/resnet_image_embedding&towhee$main
2. re-test

**Comment by haorenfsa** [comment]
> @haorenfsa Can you try with this:
> 
> 1. manually delete ~/.towhee/operators/resnet_image_embedding&towhee$main
> 2. re-test

it works
