### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by ThreadDao** [towhee-io/towhee#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
from towhee import pipeline
img_path = '/home/zong/Pictures/jepsen.jpg'
embedding_pipeline = pipeline('image-embedding')
emb = embedding_pipeline(img_path)
2022-01-05 14:25:39,726 - 140046008624896 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/home/zong/zong/.virtualenvs/Try/lib/python3.6/site-packages/towhee/engine/thread_pool_task_executor.py", line 70, in execute
    runner.op_args)
  File "/home/zong/zong/.virtualenvs/Try/lib/python3.6/site-packages/towhee/engine/operator_pool.py", line 105, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/home/zong/zong/.virtualenvs/Try/lib/python3.6/site-packages/towhee/engine/operator_loader.py", line 82, in load_operator
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zong/.towhee/operators/image_decoder&towhee$main/image_decoder.py", line 5, in <module>
    import cv2
  File "/home/zong/Downloads/pycharm-2020.2.1/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'cv2'
2022-01-05 14:25:39,726 - 140046008624896 - thread_pool_task_executor.py-thread_pool_task_executor:78 - ERROR: No module named 'cv2'
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/zong/zong/.virtualenvs/Try/lib/python3.6/site-packages/towhee/__init__.py", line 71, in __call__
    out_df = self._pipeline(in_df)
  File "/home/zong/zong/.virtualenvs/Try/lib/python3.6/site-packages/towhee/engine/pipeline.py", line 97, in __call__
    graph_ctx.join()
  File "/home/zong/zong/.virtualenvs/Try/lib/python3.6/site-packages/towhee/engine/graph_context.py", line 95, in join
    op.join()
  File "/home/zong/zong/.virtualenvs/Try/lib/python3.6/site-packages/towhee/engine/operator_context.py", line 144, in join
    runner.join()
  File "/home/zong/zong/.virtualenvs/Try/lib/python3.6/site-packages/towhee/engine/operator_runner/runner_base.py", line 196, in join
    self._end_event.wait()
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): ubuntu 18.04
- CPU/Memory:
- GPU:
- Others:
```

**Comment by ThreadDao** [comment]
I remove $home/.towhee/ directory and run it successfully.

**Comment by Chiiizzzy** [comment]
Since you have local operator cache, Towhee won't automatically update your local operator therefore skip installing the dependencies of image-decoder. 

From Towhee 0.5, we will run automatically update while executing pipelines.
