### ISSUE TITLE
[Bug]: Failed to run pieline after the first interruption

### ISSUE THREAD

**Issue by yhmo** [towhee-io/towhee#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

According to the page: https://docs.towhee.io/tutorials/reverse-image-search
1. `pip3 install towhee`
2. 
```
 pip3 install gdown
 gdown "https://drive.google.com/uc?id=1bg1RtUjeZlOfV2BiA2nf7sn5Jec9b-9I"
 unzip -q image_dataset.zip
```
3. start a milvus server
4. `pip3 install pymilvus==2.0.0rc9`
5. run this script:
```
from towhee import pipeline
import numpy as np
import os
from pathlib import Path

embedding_pipeline = pipeline('towhee/image-embedding-resnet50')

dataset_path = './image_dataset/dataset/'
images = []
vectors = []

for img_path in Path(dataset_path).glob('*'):
    vec = embedding_pipeline(str(img_path))
    norm_vec = vec / np.linalg.norm(vec)
    vectors.append(norm_vec.tolist())
    images.append(str(img_path.resolve()))
```

I got the following errors, and the script hangs:
```
(venv) ➜  towhee_test python3 ./test.py  
2022-01-05 14:57:32,183 - 140555422004992 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/thread_pool_task_executor.py", line 70, in execute
    runner.op_args)
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/operator_pool.py", line 105, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/operator_loader.py", line 82, in load_operator
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yhmo/.towhee/operators/image_decoder&towhee$main/image_decoder.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

2022-01-05 14:57:32,184 - 140555405219584 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/thread_pool_task_executor.py", line 70, in execute
    runner.op_args)
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/operator_pool.py", line 105, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/operator_loader.py", line 82, in load_operator
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yhmo/.towhee/operators/resnet_image_embedding&towhee$main/resnet_image_embedding.py", line 16, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

2022-01-05 14:57:32,184 - 140555422004992 - thread_pool_task_executor.py-thread_pool_task_executor:78 - ERROR: No module named 'cv2'
2022-01-05 14:57:32,184 - 140555405219584 - thread_pool_task_executor.py-thread_pool_task_executor:78 - ERROR: No module named 'torch'
Traceback (most recent call last):
  File "./test.py", line 14, in <module>
    vec = embedding_pipeline(str(img_path))
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/__init__.py", line 71, in __call__
    out_df = self._pipeline(in_df)
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/pipeline.py", line 97, in __call__
    graph_ctx.join()
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/graph_context.py", line 95, in join
    op.join()
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/operator_context.py", line 144, in join
    runner.join()
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/operator_runner/runner_base.py", line 196, in join
    self._end_event.wait()
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt

```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by yhmo** [comment]
Then I install the two lib:
```
pip install opencv-python
pip install torch 
```

Run the script again, it pop another error:
```
2022-01-05 15:06:35,807 - 140528362174208 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/thread_pool_task_executor.py", line 70, in execute
    runner.op_args)
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/operator_pool.py", line 105, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/home/yhmo/git-go/towhee_test/venv/lib/python3.6/site-packages/towhee/engine/operator_loader.py", line 82, in load_operator
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yhmo/.towhee/operators/resnet_image_embedding&towhee$main/resnet_image_embedding.py", line 17, in <module>
    import torchvision
ModuleNotFoundError: No module named 'torchvision'

```

**Comment by yhmo** [comment]
Then I install the torchvision:
`pip install torchvision`

Run the script again, it works.

So, the problem is: users don't know which dependency is required, they have to install the dependencies manually, it is not friendly.

**Comment by Chiiizzzy** [comment]
We have provided dependencies installation in the last few versions, could you please try to delete .towhee folder and try again?

**Comment by yhmo** [comment]
My python environment is a new one, I suppose the towhee version is the latest.

All steps:
1. mkdir towhee_test
2. cd towhee_test
3. virtualenv towhee_env
4. source ./towhee_env/bin/activate
5. pip install towhee
6. pip install gdown
7. gdown "https://drive.google.com/uc?id=1bg1RtUjeZlOfV2BiA2nf7sn5Jec9b-9I"
8. unzip -q image_dataset.zip
9. pip install pymilvus==2.0.0rc9
10. python ./test.py

The test.py is the script.

**Comment by yhmo** [comment]
delete ~/.towhee can work.

**Comment by shiyu22** [comment]
Same as #431
