### ISSUE TITLE
[Documentation]:  add proper error handling while start using towhee

### ISSUE THREAD

**Issue by sutcalag** [towhee-io/towhee#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

quick start

### Why is this needed?

Following doc to start using towhee but got below error and cannot get output

$ python3
Python 3.9.5 (default, May  4 2021, 03:36:27) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from towhee import pipeline
>>> embedding_pipeline = pipeline('image-embedding')
>>> output = embedding_pipeline('towhee.jpeg')
print(output)
2022-01-04 18:01:15,881 - 123145493909504 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/engine/thread_pool_task_executor.py", line 69, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id,
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/engine/operator_pool.py", line 95, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 71, in load_operator
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/daniel/.towhee/operators/image_decoder&towhee$main/image_decoder.py", line 10, in <module>
    from towhee.utils import ndarray_utils
ImportError: cannot import name 'ndarray_utils' from 'towhee.utils' (/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/utils/__init__.py)

2022-01-04 18:01:15,881 - 123145493909504 - thread_pool_task_executor.py-thread_pool_task_executor:78 - ERROR: cannot import name 'ndarray_utils' from 'towhee.utils' (/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/utils/__init__.py)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/__init__.py", line 69, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/engine/pipeline.py", line 93, in __call__
    graph_ctx.join()
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/engine/graph_context.py", line 95, in join
    op.join()
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/engine/operator_context.py", line 137, in join
    runner.join()
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 190, in join
    self._end_event.wait()
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
>>> print(output)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'output' is not defined
>>> 2022-01-04 18:01:16,318 - 123145510699008 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/engine/thread_pool_task_executor.py", line 69, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id,
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/engine/operator_pool.py", line 95, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/Users/daniel/Documents/test/towhee/towhee_env/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 71, in load_operator
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/daniel/.towhee/operators/resnet_image_embedding&towhee$main/resnet_image_embedding.py", line 25, in <module>
    from towhee.utils.pil_utils import to_pil
ModuleNotFoundError: No module named 'towhee.utils.pil_utils'

2022-01-04 18:01:16,318 - 123145510699008 - thread_pool_task_executor.py-thread_pool_task_executor:78 - ERROR: No module named 'towhee.utils.pil_utils'

KeyboardInterrupt
>>> from towhee import pipeline
>>> embedding_pipeline = pipeline('towhee/image-embedding-resnet101')
Downloading README.md: 100%|████████████████████████████████████| 1.61k/1.61k [00:00<00:00, 435kiB/s]
Downloading image_embedding_resnet101.yaml: 100%|███████████████| 2.12k/2.12k [00:00<00:00, 630kiB/s]
Downloading .gitignore: 100%|███████████████████████████████████| 3.10k/3.10k [00:00<00:00, 920kiB/s]
Downloading readme_res/pipeline.png: 100%|████████████████████████| 220k/220k [00:00<00:00, 332kiB/s]
>>>

**Comment by czhen-zilliz** [comment]
Same issue when quick start

```
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /Users/czhen/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100%|████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [01:27<00:00, 1.17MB/s]
Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth" to /Users/czhen/.cache/torch/hub/checkpoints/resnet50_a1_0-14fe96d1.pth
 98%|██████████████████████████████████████████████████████████████████████████████████████████▋  | 95.4M/97.7M [01:40<00:02, 993kB/s]
2022-01-06 10:28:31,891 - 123145452941312 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/thread_pool_task_executor.py", line 69, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id,
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/operator_pool.py", line 105, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 89, in load_operator
    return getattr(module, op_cls)(**args)
  File "/Users/czhen/.towhee/operators/resnet_image_embedding&towhee$main/resnet_image_embedding.py", line 42, in __init__
    self.model = module.Model(model_name)
  File "/Users/czhen/.towhee/operators/resnet_image_embedding&towhee$main/pytorch/model.py", line 36, in __init__
    state_dict = torch.hub.load_state_dict_from_url(
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/torch/hub.py", line 557, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/torch/serialization.py", line 794, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 2281041 more bytes. The file might be corrupted.

2022-01-06 10:28:31,891 - 123145452941312 - thread_pool_task_executor.py-thread_pool_task_executor:78 - ERROR: unexpected EOF, expected 2281041 more bytes. The file might be corrupted.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/__init__.py", line 71, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/pipeline.py", line 97, in __call__
    graph_ctx.join()
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/graph_context.py", line 95, in join
    op.join()
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/operator_context.py", line 144, in join
    runner.join()
  File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 196, in join
    self._end_event.wait()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
>>>
```

**Comment by alwayslove2013** [comment]
[run quick start failed]

conda new env (python 3.8)
same error

**Comment by junjiejiangjjj** [comment]
Please check the version of towhee, it senses not v0.4.0

**Comment by Folgerjun** [comment]
same error.  towhee==0.4.0.  Is this resolved?

**Comment by junjiejiangjjj** [comment]
> Same issue when quick start
> 
> ```
> Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /Users/czhen/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
> 100%|████████████████████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [01:27<00:00, 1.17MB/s]
> Downloading: "https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-rsb-weights/resnet50_a1_0-14fe96d1.pth" to /Users/czhen/.cache/torch/hub/checkpoints/resnet50_a1_0-14fe96d1.pth
>  98%|██████████████████████████████████████████████████████████████████████████████████████████▋  | 95.4M/97.7M [01:40<00:02, 993kB/s]
> 2022-01-06 10:28:31,891 - 123145452941312 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/thread_pool_task_executor.py", line 69, in execute
>     op = self._op_pool.acquire_op(runner.hub_op_id,
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/operator_pool.py", line 105, in acquire_op
>     op = self._op_loader.load_operator(hub_op_id, op_args)
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 89, in load_operator
>     return getattr(module, op_cls)(**args)
>   File "/Users/czhen/.towhee/operators/resnet_image_embedding&towhee$main/resnet_image_embedding.py", line 42, in __init__
>     self.model = module.Model(model_name)
>   File "/Users/czhen/.towhee/operators/resnet_image_embedding&towhee$main/pytorch/model.py", line 36, in __init__
>     state_dict = torch.hub.load_state_dict_from_url(
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/torch/hub.py", line 557, in load_state_dict_from_url
>     return torch.load(cached_file, map_location=map_location)
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
>     return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/torch/serialization.py", line 794, in _legacy_load
>     deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
> RuntimeError: unexpected EOF, expected 2281041 more bytes. The file might be corrupted.
> 
> 2022-01-06 10:28:31,891 - 123145452941312 - thread_pool_task_executor.py-thread_pool_task_executor:78 - ERROR: unexpected EOF, expected 2281041 more bytes. The file might be corrupted.
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/__init__.py", line 71, in __call__
>     out_df = self._pipeline(in_df)
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/pipeline.py", line 97, in __call__
>     graph_ctx.join()
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/graph_context.py", line 95, in join
>     op.join()
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/operator_context.py", line 144, in join
>     runner.join()
>   File "/Users/czhen/Documents/workspace/venv/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 196, in join
>     self._end_event.wait()
>   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 574, in wait
>     signaled = self._cond.wait(timeout)
>   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 312, in wait
>     waiter.acquire()
> KeyboardInterrupt
> >>>
> ```

It seems to download pytorch model failed
