### ISSUE TITLE
[Bug]: Failed to run music recognition tutorial

### ISSUE THREAD

**Issue by yhmo** [towhee-io/towhee#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Steps:
1. rm -rf ~/.towhee
2. mkdir AAA
3. cd AAA
4. virtualenv towhee_env
5. source ./towhee_env/bin/activate
6. $ pip3 install gdown
    $ gdown 'https://drive.google.com/uc?id=1SSwEXOnG6c_F2NjcqYTsIM65zVCLpbOr'
    $ unzip -q data.zip

7. pip install towhee
8. pip install numpy
9. run the script:
```
from towhee import pipeline
import numpy as np
import os
from pathlib import Path

embedding_pipeline = pipeline('towhee/audio-embedding-vggish')

import numpy as np
import os
from pathlib import Path

dataset_path = './data/music_dataset'
music_list = [f for f in Path(dataset_path).glob('*')]
vec_sets = []

for audio_path in music_list:
    print(audio_path)
    vecs = embedding_pipeline(str(audio_path))
    norm_vecs = [vec / np.linalg.norm(vec) for vec in vecs[0][0]]
    vec_sets.append(norm_vecs)
```

Get this error and the script hangs:

```
Downloading audio_embedding_vggish.yaml: 100%|█| 1.49k/1.49k [00:00<00:00, 722ki
Downloading README.md: 100%|███████████████| 1.53k/1.53k [00:00<00:00, 917kiB/s]
music_dataset/music_dataset/jazz.wav
Downloading README.md: 100%|██████████████| 1.45k/1.45k [00:00<00:00, 2.21MiB/s]
Downloading requirements.txt: 100%|██████████| 71.0/71.0 [00:00<00:00, 115kiB/s]
Downloading tf_vggish_audioset.py: 100%|██| 2.00k/2.00k [00:00<00:00, 2.88MiB/s]
Downloading model/variables/variables.index: 100%|█| 1.23k/1.23k [00:00<00:00, 1
Downloading __init__.py: 100%|█████████████████| 592/592 [00:00<00:00, 529kiB/s]
Downloading model/saved_model.pb: 100%|██████| 134k/134k [00:01<00:00, 129kiB/s]
Downloading model/variables/variables.data-00000-of-00001: 100%|█| 289M/289M [03
Collecting tensorboard==2.7.0
  Using cached tensorboard-2.7.0-py3-none-any.whl (5.8 MB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.0 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.12.0, 1.12.2, 1.12.3, 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2)
ERROR: No matching distribution found for tensorflow==2.7.0
2022-01-06 11:33:06,503 - 140414984423168 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/engine/thread_pool_task_executor.py", line 70, in execute
    runner.op_args)
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/engine/operator_pool.py", line 105, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/engine/operator_loader.py", line 71, in load_operator
    path = fm.get_operator(function)
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/hub/file_manager.py", line 407, in get_operator
    download_repo(author, repo, branch, str(file_path.parent), install_reqs=install_reqs)
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/hub/hub_tools.py", line 528, in download_repo
    download_files(author, repo, branch, file_list, lfs_files, local_dir, install_reqs)
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/hub/hub_tools.py", line 375, in download_files
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-r', local_dir + req])
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/AAA/towhee_env/bin/python', '-m', 'pip', 'install', '-r', '/home/yhmo/.towhee/operators/tf_vggish_audioset&towhee$main/requirements.txt']' returned non-zero exit status 1.

2022-01-06 11:33:06,504 - 140414984423168 - thread_pool_task_executor.py-thread_pool_task_executor:78 - ERROR: Command '['/tmp/AAA/towhee_env/bin/python', '-m', 'pip', 'install', '-r', '/home/yhmo/.towhee/operators/tf_vggish_audioset&towhee$main/requirements.txt']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "./test.py", line 18, in <module>
    vecs = embedding_pipeline(str(audio_path))
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/__init__.py", line 71, in __call__
    out_df = self._pipeline(in_df)
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/engine/pipeline.py", line 97, in __call__
    graph_ctx.join()
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/engine/graph_context.py", line 95, in join
    op.join()
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/engine/operator_context.py", line 144, in join
    runner.join()
  File "/tmp/AAA/towhee_env/lib/python3.6/site-packages/towhee/engine/operator_runner/runner_base.py", line 196, in join
    self._end_event.wait()
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
@yhmo This pipeline uses tensorflow 2.7.0 which requires python >= 3.7. Lemme check for some other ways to implement it with python3.6
