### ISSUE TITLE
[Bug]: Failed to run Towhee on Conda

### ISSUE THREAD

**Issue by xige-16** [towhee-io/towhee#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> from towhee import pipeline
>>> embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
Downloading audio_embedding_vggish.yaml: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.49k/1.49k [00:00<00:00, 280kiB/s]
Downloading README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.53k/1.53k [00:00<00:00, 582kiB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/__init__.py", line 114, in pipeline
    pipeline_ = Pipeline(str(yaml_path))
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/engine/pipeline.py", line 41, in __init__
    self._graph_repr = GraphRepr.from_yaml(graph_repr)
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/dag/graph_repr.py", line 229, in from_yaml
    return GraphRepr.from_dict(info)
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/dag/graph_repr.py", line 183, in from_dict
    if not BaseRepr.is_valid(info, {'name', 'operators', 'dataframes'}):
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/dag/base_repr.py", line 55, in is_valid
    info_keys = set(info.keys())
AttributeError: 'str' object has no attribute 'keys'
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.4.0
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by xige-16** [comment]
same with image embedding
```
>>> embedding_pipeline = pipeline('towhee/image-embedding-resnet50')
Downloading .gitignore: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.10k/3.10k [00:00<00:00, 1.00MiB/s]
Downloading image_embedding_resnet50.yaml: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.12k/2.12k [00:00<00:00, 668kiB/s]
Downloading README.md: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.61k/1.61k [00:00<00:00, 393kiB/s]
Downloading readme_res/pipeline.png: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 220k/220k [00:00<00:00, 417kiB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/__init__.py", line 114, in pipeline
    pipeline_ = Pipeline(str(yaml_path))
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/engine/pipeline.py", line 41, in __init__
    self._graph_repr = GraphRepr.from_yaml(graph_repr)
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/dag/graph_repr.py", line 229, in from_yaml
    return GraphRepr.from_dict(info)
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/dag/graph_repr.py", line 183, in from_dict
    if not BaseRepr.is_valid(info, {'name', 'operators', 'dataframes'}):
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/dag/base_repr.py", line 55, in is_valid
    info_keys = set(info.keys())
AttributeError: 'str' object has no attribute 'keys'
```

**Comment by xige-16** [comment]
I have install towhee with conda
```
$ conda create -n towhee_env python=3.6  # create a conda environment for Towhee
$ conda activate towhee_env  # activate your newly created conda environment
$ conda install -c towhee-io towhee   # install Towhee via the `towhee-io` channel
```

**Comment by xige-16** [comment]
run image duplication
```
>>> from towhee import pipeline
>>> embedding_pipeline = pipeline('image-encoding')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/__init__.py", line 111, in pipeline
    yaml_path = fm.get_pipeline(task, branch, force_download)
  File "/Users/gexi/miniconda3/envs/towhee_env/lib/python3.6/site-packages/towhee/hub/file_manager.py", line 308, in get_pipeline
    raise ValueError('''Incorrect pipeline format, should be '<author>/<pipeline_repo>'.''')
ValueError: Incorrect pipeline format, should be '<author>/<pipeline_repo>'.
>>> 
```

**Comment by junjiejiangjjj** [comment]
Please checkout the version of towhee, from the logs, it's not v0.4.0.

**Comment by xige-16** [comment]
> Please checkout the version of towhee, from the logs, it's not v0.4.0.

Is there any order to check

**Comment by xige-16** [comment]
> I have install towhee with conda
> 
> ```
> $ conda create -n towhee_env python=3.6  # create a conda environment for Towhee
> $ conda activate towhee_env  # activate your newly created conda environment
> $ conda install -c towhee-io towhee   # install Towhee via the `towhee-io` channel
> ```

I installed it through conda according to the documentation.

**Comment by junjiejiangjjj** [comment]
In conda, we didn't publish 0.4.0, we will fix it soon.

**Comment by junjiejiangjjj** [comment]
> In conda, we didn't publish 0.4.0, we will fix it soon.

Try again.

**Comment by fzliu** [comment]
> > In conda, we didn't publish 0.4.0, we will fix it soon.
> 
> Update towhee and try again.

@xige-16 does this fix your issue?
