### ISSUE TITLE
[Bug]: Fail to exit the process normally after pipeline raise exception 

### ISSUE THREAD

**Issue by czs007** [towhee-io/towhee#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the pipeline runs abnormally, the process cannot be exited correctly, and you must resort to the `ctrl + c` to exit.

### Expected Behavior

Process should exit normally.

### Steps To Reproduce

```markdown
step to reproduce:
first you should uninstall the torchvision package deliberately.
then execute following code in terminal:

>>> eb_pipline = pipeline('image-embedding')
>>> output = eb_pipline('towhee.jpeg')

2022-01-06 21:31:45,708 - 139848891492096 - thread_pool_task_executor.py-thread_pool_task_executor:77 - ERROR: Traceback (most recent call last):
  File "/home/czs/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/thread_pool_task_executor.py", line 69, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id,
  File "/home/czs/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/operator_pool.py", line 105, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args)
  File "/home/czs/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 82, in load_operator
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/czs/.towhee/operators/resnet_image_embedding&towhee$main/resnet_image_embedding.py", line 17, in <module>
    import torchvision
ModuleNotFoundError: No module named 'torchvision'
>>>exit()
// hangs in there
>>> ^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/czs/miniconda3/envs/towhee/lib/python3.8/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/home/czs/miniconda3/envs/towhee/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/czs/miniconda3/envs/towhee/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

The process in still hanged even if you type exit() or input `Ctrl + D`.
You have to use `Ctrl + C` to kill the process.

### Environment

- Towhee version(e.g. v0.1.3 or 8b23a93): 0.4.0
- OS(Ubuntu or CentOS):Ubuntu 18.04
- Python: python 3.8 conda environment
- GPU:
- Others:

**Comment by Chiiizzzy** [comment]
This issue and several similar issues will be fixed once [issue#431](https://github.com/towhee-io/towhee/issues/431) is resolved, therefore closed and remain issue#431 only.
