### ISSUE TITLE
[Bug]: Installation failed on VM

### ISSUE THREAD

**Issue by claireyuw** [towhee-io/towhee#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running `from towhee import pipeline` in VM, it raises “ModuleNotFoundError: No module named 'towhee'”

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory:
- GPU:
- Others:
```

**Comment by fzliu** [comment]
Can you clarify? What VM are you using and how did you install Towhee?

**Comment by claireyuw** [comment]
I chose installation via pip. See below:

```
zichuan@zichuan-Standard-PC-i440FX-PIIX-1996:~$ python3
Python 3.6.9 (default, Dec  8 2021, 21:08:43) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from towhee import pipeline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'towhee'
```

**Comment by fzliu** [comment]
Can you rerun `pip install towhee` and paste the output here?

**Comment by claireyuw** [comment]
```
zichuan@zichuan-Standard-PC-i440FX-PIIX-1996:~$ pip install towhee
Collecting towhee
  Downloading https://files.pythonhosted.org/packages/1a/85/5aca04c56146b1774a0344b447978f7e82b1ee8fef2a3b9d1b535f40f8a0/towhee-0.4.0.tar.gz (3.8MB)
    100% |████████████████████████████████| 3.8MB 247kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BIJzoY/towhee/setup.py", line 27
        def create_towhee_cache(dst: str):
                                   ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BIJzoY/towhee/
```

**Comment by fzliu** [comment]
We don't support Python 2. Try this:

```
$ python3 -m venv towhee_env  # create a virtual environment
$ source towhee_env/bin/activate  # activate your newly created virtual environment
$ pip3 install -U pip  # we recommend updating pip first before installing Towhee
$ pip3 install -U towhee  # install Towhee
```

Then try running a pipeline.
