### ISSUE TITLE
[Bug]: Pipeline “towhee/image-embedding-xcit-tiny-24-p8-384-dist“ crashed when embedding an image

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pipeline “towhee/image-embedding-xcit-tiny-24-p8-384-dist“ crashed when embedding an image
```
>>> embedding = embedding_pipeline(img_path)
正克隆到 '/Users/binbin/.towhee/operators/towhee/image_decoder/main'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 16 (delta 3), reused 0 (delta 0), pack-reused 0
接收对象中: 100% (16/16), 完成.
处理 delta 中: 100% (3/3), 完成.
Requirement already satisfied: opencv-python in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from -r /Users/binbin/.towhee/operators/towhee/image_decoder/main/requirements.txt (line 1)) (4.5.4.60)
Requirement already satisfied: requests in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from -r /Users/binbin/.towhee/operators/towhee/image_decoder/main/requirements.txt (line 2)) (2.26.0)
Requirement already satisfied: numpy in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from -r /Users/binbin/.towhee/operators/towhee/image_decoder/main/requirements.txt (line 3)) (1.19.5)
Requirement already satisfied: certifi>=2017.4.17 in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from requests->-r /Users/binbin/.towhee/operators/towhee/image_decoder/main/requirements.txt (line 2)) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from requests->-r /Users/binbin/.towhee/operators/towhee/image_decoder/main/requirements.txt (line 2)) (1.26.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from requests->-r /Users/binbin/.towhee/operators/towhee/image_decoder/main/requirements.txt (line 2)) (2.0.9)
Requirement already satisfied: idna<4,>=2.5 in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from requests->-r /Users/binbin/.towhee/operators/towhee/image_decoder/main/requirements.txt (line 2)) (3.3)
正克隆到 '/Users/binbin/.towhee/operators/towhee/timm_image_embedding/main'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 11 (delta 3), reused 0 (delta 0), pack-reused 0
接收对象中: 100% (11/11), 完成.
处理 delta 中: 100% (3/3), 完成.
Requirement already satisfied: numpy in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from -r /Users/binbin/.towhee/operators/towhee/timm_image_embedding/main/requirements.txt (line 1)) (1.19.5)
Requirement already satisfied: timm in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from -r /Users/binbin/.towhee/operators/towhee/timm_image_embedding/main/requirements.txt (line 2)) (0.4.12)
Requirement already satisfied: torch>=1.4 in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from timm->-r /Users/binbin/.towhee/operators/towhee/timm_image_embedding/main/requirements.txt (line 2)) (1.9.0)
Requirement already satisfied: torchvision in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from timm->-r /Users/binbin/.towhee/operators/towhee/timm_image_embedding/main/requirements.txt (line 2)) (0.10.0)
Requirement already satisfied: typing-extensions in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from torch>=1.4->timm->-r /Users/binbin/.towhee/operators/towhee/timm_image_embedding/main/requirements.txt (line 2)) (3.7.4.3)
Requirement already satisfied: pillow>=5.3.0 in /Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages (from torchvision->timm->-r /Users/binbin/.towhee/operators/towhee/timm_image_embedding/main/requirements.txt (line 2)) (8.3.1)
2022-02-16 10:40:32,242 - 123145595334656 - thread_pool_task_executor.py-thread_pool_task_executor:75 - ERROR: Traceback (most recent call last):
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/thread_pool_task_executor.py", line 68, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id, runner.op_args, runner.tag)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/operator_pool.py", line 102, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, tag)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 142, in load_operator
    op = factory(function, args, tag)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 118, in load_operator_from_cache
    return self.load_operator_from_path(path, args)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 108, in load_operator_from_path
    return self.instance_operator(op, args) if op is not None else None
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 152, in instance_operator
    return op(**args) if args is not None else op()
  File "/Users/binbin/.towhee/operators/towhee/timm_image_embedding/main/timm_image_embedding.py", line 25, in __init__
    self.model = create_model(model_name, pretrained=True, num_classes=0)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/timm/models/factory.py", line 78, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (xcit_tiny_24_p8_384_dist)

2022-02-16 10:40:32,242 - 123145595334656 - thread_pool_task_executor.py-thread_pool_task_executor:76 - ERROR: Unknown model (xcit_tiny_24_p8_384_dist)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/__init__.py", line 73, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/pipeline.py", line 107, in __call__
    graph_ctx.join()
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/graph_context.py", line 95, in join
    op.join()
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/operator_context.py", line 146, in join
    runner.join()
  File "/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/towhee/engine/operator_runner/runner_base.py", line 218, in join
    self._end_event.wait()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

### Expected Behavior

embedding succssfully

### Steps To Reproduce

```markdown
from towhee import pipeline
img_path = "/Users/binbin/Towhee_projects/2021825-19039.jpg"
embedding_pipeline = pipeline('towhee/image-embedding-xcit-tiny-24-p8-384-dist')
embedding = embedding_pipeline(img_path)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.4.1.dev73
- OS(Ubuntu or CentOS): mac OS
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
it works when upgrades timm to 0.5.4.

So it is required to upgrade timm.

**Comment by binbinlv** [comment]
@filip-halt 
hi, filip, what is the progress of upgrading timm?

**Comment by filip-halt** [comment]
forgot to reply, added a requirments file with the correct version.
