### ISSUE TITLE
[Bug]: Pipeline “towhee/image-embedding-regnety-080“ crashed when embedding image list

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pipeline  towhee/image-embedding-regnety-080 carshed when embedding image list

````
Testing test_embedding_image_list:towhee/image-embedding-regnety-080
2022-02-21 16:34:32,081 - 123145509965824 - thread_pool_task_executor.py-thread_pool_task_executor:75 - ERROR: Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/thread_pool_task_executor.py", line 68, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id, runner.op_args, runner.tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_pool.py", line 102, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 142, in load_operator
    op = factory(function, args, tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 118, in load_operator_from_cache
    return self.load_operator_from_path(path, args)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 108, in load_operator_from_path
    return self.instance_operator(op, args) if op is not None else None
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 152, in instance_operator
    return op(**args) if args is not None else op()
  File "/Users/jingjing/.towhee/operators/towhee/timm_image_embedding/main/timm_image_embedding.py", line 25, in __init__
    self.model = create_model(model_name, pretrained=True, num_classes=0)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/timm/models/factory.py", line 74, in create_model
    model = create_fn(pretrained=pretrained, **kwargs)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/timm/models/regnet.py", line 476, in regnety_080
    return _create_regnet('regnety_080', pretrained, **kwargs)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/timm/models/regnet.py", line 345, in _create_regnet
    return build_model_with_cfg(
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/timm/models/helpers.py", line 465, in build_model_with_cfg
    load_pretrained(
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/timm/models/helpers.py", line 189, in load_pretrained
    state_dict = load_state_dict_from_url(pretrained_url, progress=progress, map_location='cpu')
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/torch/hub.py", line 557, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/torch/serialization.py", line 794, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 2133239 more bytes. The file might be corrupted.

2022-02-21 16:34:32,081 - 123145509965824 - thread_pool_task_executor.py-thread_pool_task_executor:76 - ERROR: unexpected EOF, expected 2133239 more bytes. The file might be corrupted.
Traceback (most recent call last):
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_main.py", line 232, in <module>
    test_caller()
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_main.py", line 223, in test_caller
    image_class_pipeline_runner()
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_main.py", line 109, in image_class_pipeline_runner
    res = methodcaller(func, pipeline_name)(invalid_embedding_obj)
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_image_embedding.py", line 71, in test_embedding_image_list
    embedding = embedding_pipeline(img_list)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/__init__.py", line 73, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/pipeline.py", line 107, in __call__
    graph_ctx.join()
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/graph_context.py", line 95, in join
    op.join()
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_context.py", line 146, in join
    runner.join()
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 218, in join
    self._end_event.wait()
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
````

### Expected Behavior

embedding succssfully

### Steps To Reproduce

```
def test_embedding_image_list(self, pipeline_name):
        """
        target: test embedding with image list
        method:  embedding with image list
        expected: raise exception
        """
        N = 3
        img_list = []
        img = cf.create_image()
        for i in range(N):
            img_list.append(img)
        embedding_pipeline = pipeline(pipeline_name)
        try:
            embedding = embedding_pipeline(img_list)
        except Exception as e:
            print("Raise Exception: %s" % e)

        return True
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.4.1.dev75
- OS(Ubuntu or CentOS): macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
Download torch model failed, delete model in the cache, normally in `~/.cache/torch/hub/checkpoints/`

**Comment by jingkl** [comment]
> ~/.cache/torch/hub/checkpoints/



> Download torch model failed, delete model in the cache, normally in `~/.cache/torch/hub/checkpoints/`

ok，I get it

**Comment by binbinlv** [comment]
I think this solution is a workaround, could we fix this in a better way? Thanks, reopen it for discussion.

**Comment by fzliu** [comment]
Can you close this issue and re-open another one on automatically redownloading failed models?

**Comment by binbinlv** [comment]
@jingkl 
could you help to solve the comments of frank? Thanks.
