### ISSUE TITLE
[Bug]: Pipeline "towhee/image-embedding-convnext-base"crashed when embedding concurrent multi threads

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
2022-02-21 19:26:20,808 - 123145483165696 - thread_pool_task_executor.py-thread_pool_task_executor:75 - ERROR: Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/thread_pool_task_executor.py", line 68, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id, runner.op_args, runner.tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_pool.py", line 102, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 142, in load_operator
    op = factory(function, args, tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 118, in load_operator_from_cache
    return self.load_operator_from_path(path, args)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 108, in load_operator_from_path
    return self.instance_operator(op, args) if op is not None else None
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 152, in instance_operator
    return op(**args) if args is not None else op()
  File "/Users/jingjing/.towhee/operators/towhee/timm_image_embedding/main/timm_image_embedding.py", line 25, in __init__
    self.model = create_model(model_name, pretrained=True, num_classes=0)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/timm/models/factory.py", line 78, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (convnext_base)

2022-02-21 19:26:20,810 - 123145483165696 - thread_pool_task_executor.py-thread_pool_task_executor:76 - ERROR: Unknown model (convnext_base)
Traceback (most recent call last):
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_main.py", line 268, in <module>
    test_caller()
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_main.py", line 259, in test_caller
    image_class_pipeline_runner()
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_main.py", line 156, in image_class_pipeline_runner
    res = methodcaller(func, pipeline_name, embedding_size_each)(valid_embedding_obj)
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_image_embedding.py", line 179, in test_embedding_concurrent_multi_threads
    t.start()
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/threading.py", line 875, in start
    self._started.wait()
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
2022-02-21 19:26:20,827 - 123145568186368 - thread_pool_task_executor.py-thread_pool_task_executor:75 - ERROR: Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/thread_pool_task_executor.py", line 68, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id, runner.op_args, runner.tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_pool.py", line 102, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 142, in load_operator
    op = factory(function, args, tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 118, in load_operator_from_cache
    return self.load_operator_from_path(path, args)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 108, in load_operator_from_path
    return self.instance_operator(op, args) if op is not None else None
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 152, in instance_operator
    return op(**args) if args is not None else op()
  File "/Users/jingjing/.towhee/operators/towhee/timm_image_embedding/main/timm_image_embedding.py", line 25, in __init__
    self.model = create_model(model_name, pretrained=True, num_classes=0)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/timm/models/factory.py", line 78, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (convnext_base)

2022-02-21 19:26:20,828 - 123145568186368 - thread_pool_task_executor.py-thread_pool_task_executor:76 - ERROR: Unknown model (convnext_base)
Exception ignored in: <module 'threading' from '/Users/jingjing/miniconda3/envs/tw/lib/python3.9/threading.py'>
Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/threading.py", line 1411, in _shutdown
    atexit_call()
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/threading.py", line 1029, in join
    self._wait_for_tstate_lock()
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/threading.py", line 1045, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt: 
```

### Expected Behavior

embedding succssfully

### Steps To Reproduce

```markdown
def test_embedding_concurrent_multi_threads(self, pipeline_name, embedding_size):
        """
        target: test embedding for normal case
        method:  embedding with concurrent multi-processes
        expected: return embeddings
        """
        threads_num = 10
        threads = []

        def embedding():
            embedding_pipeline = pipeline(pipeline_name)
            embedding = embedding_pipeline(data_path + "towhee_test_image2.jpg")
            print(embedding.size)
            assert embedding.size == embedding_size

        for i in range(threads_num):
            t = threading.Thread(target=embedding)
            threads.append(t)
            t.start()
            time.sleep(0.2)
        for t in threads:
            t.join()

        return True
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.4.1.dev75
- OS(Ubuntu or CentOS): macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
Which pipeline did you use?

**Comment by jingkl** [comment]
> Which pipeline did you use?

towhee/image-embedding-convnext-base

**Comment by junjiejiangjjj** [comment]
Which version of `timm` is in your env,  it should be >= 0.5.4

**Comment by jingkl** [comment]
> Which version of `timm` is in your env, it should be >= 0.5.4

ok，I test it successful with timm>=0.5.4

**Comment by binbinlv** [comment]
@jingkl 
please verify this issue, and close it if it is fixed, thanks.
