### ISSUE TITLE
[Bug]: Pipeline "towhee/audio-embedding-hubert-asr-large" crashed when embedding an audio

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
Testing test_embedding_more_times:towhee/audio-embedding-hubert-asr-large
Cloning into '/Users/jingjing/.towhee/pipelines/towhee/audio_embedding_hubert_asr_large/main'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 4), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (12/12), done.
Resolving deltas: 100% (4/4), done.
Cloning into '/Users/jingjing/.towhee/operators/towhee/torchaudio_audio_embedding/main'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 14 (delta 5), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (14/14), done.
Resolving deltas: 100% (5/5), done.
Collecting torchaudio>=0.10.2
  Downloading torchaudio-0.10.2-cp38-cp38-macosx_10_9_x86_64.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 1.3 MB/s 
Collecting torch==1.10.2
  Using cached torch-1.10.2-cp38-none-macosx_10_9_x86_64.whl (147.2 MB)
Requirement already satisfied: typing-extensions in /Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages (from torch==1.10.2->torchaudio>=0.10.2->-r /Users/jingjing/.towhee/operators/towhee/torchaudio_audio_embedding/main/requirements.txt (line 1)) (4.1.1)
Installing collected packages: torch, torchaudio
  Attempting uninstall: torch
    Found existing installation: torch 1.9.0
    Uninstalling torch-1.9.0:
      Successfully uninstalled torch-1.9.0
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 0.9.0
    Uninstalling torchaudio-0.9.0:
      Successfully uninstalled torchaudio-0.9.0
Successfully installed torch-1.10.2 torchaudio-0.10.2
2022-02-24 17:30:59,735 - 123145375952896 - thread_pool_task_executor.py-thread_pool_task_executor:75 - ERROR: Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/thread_pool_task_executor.py", line 68, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id, runner.op_args, runner.tag)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_pool.py", line 102, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, tag)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 142, in load_operator
    op = factory(function, args, tag)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 118, in load_operator_from_cache
    return self.load_operator_from_path(path, args)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 108, in load_operator_from_path
    return self.instance_operator(op, args) if op is not None else None
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 152, in instance_operator
    return op(**args) if args is not None else op()
  File "/Users/jingjing/.towhee/operators/towhee/torchaudio_audio_embedding/main/torchaudio_audio_embedding.py", line 17, in __init__
    self._bundle = getattr(torchaudio.pipelines, name)
AttributeError: module 'torchaudio' has no attribute 'pipelines'

2022-02-24 17:30:59,736 - 123145375952896 - thread_pool_task_executor.py-thread_pool_task_executor:76 - ERROR: module 'torchaudio' has no attribute 'pipelines'
Traceback (most recent call last):
  File "test_main.py", line 431, in <module>
    test_caller()
  File "test_main.py", line 424, in test_caller
    audio_class_pipeline_runner()
  File "test_main.py", line 399, in audio_class_pipeline_runner
    res = methodcaller(func, pipeline_name, embedding_size_each)(test_valid_embedding)
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_audio_embedding.py", line 200, in test_embedding_more_times
    embedding = embedding_pipeline(data_path + "towhee_test_audio_1.wav")
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/__init__.py", line 73, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/pipeline.py", line 107, in __call__
    graph_ctx.join()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/graph_context.py", line 99, in join
    op.join()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_context.py", line 146, in join
    runner.join()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_runner/runner_base.py", line 220, in join
    self._end_event.wait()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

### Expected Behavior

embedding successfully

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.4.1dev87
- OS(Ubuntu or CentOS): macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jingkl** [comment]
Already verified, no more problems
