### ISSUE TITLE
[Bug]: Pipeline "towhee/audio-embedding-vggish" crashed when embedding an audio

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
Pipeline "towhee/audio-embedding-vggish" crashed when embedding an audio

```
Testing test_embedding_more_times:towhee/audio-embedding-vggish
Cloning into '/Users/jingjing/.towhee/pipelines/towhee/audio_embedding_vggish/main'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 23 (delta 7), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (23/23), done.
Resolving deltas: 100% (7/7), done.
Cloning into '/Users/jingjing/.towhee/operators/towhee/torch_vggish/main'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 38 (delta 14), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (38/38), 256.15 MiB | 2.18 MiB/s, done.
Resolving deltas: 100% (14/14), done.
Collecting torch==1.9.0
  Using cached torch-1.9.0-cp38-none-macosx_10_9_x86_64.whl (127.9 MB)
Collecting numpy==1.19.5
  Using cached numpy-1.19.5-cp38-cp38-macosx_10_9_x86_64.whl (15.6 MB)
Requirement already satisfied: soundfile in /Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages (from -r /Users/jingjing/.towhee/operators/towhee/torch_vggish/main/requirements.txt (line 3)) (0.10.3.post1)
Collecting resampy
  Using cached resampy-0.2.2-py3-none-any.whl
Requirement already satisfied: typing-extensions in /Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages (from torch==1.9.0->-r /Users/jingjing/.towhee/operators/towhee/torch_vggish/main/requirements.txt (line 1)) (4.1.1)
Requirement already satisfied: cffi>=1.0 in /Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages (from soundfile->-r /Users/jingjing/.towhee/operators/towhee/torch_vggish/main/requirements.txt (line 3)) (1.15.0)
Collecting scipy>=0.13
  Downloading scipy-1.8.0-cp38-cp38-macosx_12_0_universal2.macosx_10_9_x86_64.whl (55.3 MB)
     |████████████████████████████████| 55.3 MB 2.2 MB/s 
Collecting numba>=0.32
  Downloading numba-0.55.1-cp38-cp38-macosx_10_14_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 1.8 MB/s 
Collecting six>=1.3
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: pycparser in /Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages (from cffi>=1.0->soundfile->-r /Users/jingjing/.towhee/operators/towhee/torch_vggish/main/requirements.txt (line 3)) (2.21)
Requirement already satisfied: setuptools in /Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages (from numba>=0.32->resampy->-r /Users/jingjing/.towhee/operators/towhee/torch_vggish/main/requirements.txt (line 4)) (58.0.4)
Collecting llvmlite<0.39,>=0.38.0rc1
  Using cached llvmlite-0.38.0-cp38-cp38-macosx_10_9_x86_64.whl (25.5 MB)
Installing collected packages: numpy, llvmlite, six, scipy, numba, torch, resampy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.2
    Uninstalling numpy-1.22.2:
      Successfully uninstalled numpy-1.22.2
  Attempting uninstall: torch
    Found existing installation: torch 1.10.2
    Uninstalling torch-1.10.2:
      Successfully uninstalled torch-1.10.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.11.3 requires torch==1.10.2, but you have torch 1.9.0 which is incompatible.
torchaudio 0.10.2 requires torch==1.10.2, but you have torch 1.9.0 which is incompatible.
Successfully installed llvmlite-0.38.0 numba-0.55.1 numpy-1.19.5 resampy-0.2.2 scipy-1.8.0 six-1.16.0 torch-1.9.0
2022-02-25 15:38:01,319 - 123145488052224 - thread_pool_task_executor.py-thread_pool_task_executor:75 - ERROR: Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/thread_pool_task_executor.py", line 68, in execute
    op = self._op_pool.acquire_op(runner.hub_op_id, runner.op_args, runner.tag)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_pool.py", line 102, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, tag)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 142, in load_operator
    op = factory(function, args, tag)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 118, in load_operator_from_cache
    return self.load_operator_from_path(path, args)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 108, in load_operator_from_path
    return self.instance_operator(op, args) if op is not None else None
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_loader.py", line 152, in instance_operator
    return op(**args) if args is not None else op()
  File "/Users/jingjing/.towhee/operators/towhee/torch_vggish/main/torch_vggish.py", line 40, in __init__
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/jingjing/.towhee/operators/towhee/torch_vggish/main/pytorch/model.py", line 23, in <module>
    import vggish_input
  File "/Users/jingjing/.towhee/operators/towhee/torch_vggish/main/pytorch/vggish_input.py", line 22, in <module>
    import resampy
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/resampy/__init__.py", line 7, in <module>
    from .core import *
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/resampy/core.py", line 9, in <module>
    from .interpn import resample_f
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/resampy/interpn.py", line 4, in <module>
    import numba
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/numba/__init__.py", line 200, in <module>
    _ensure_critical_deps()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/numba/__init__.py", line 140, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.21 or less")
ImportError: Numba needs NumPy 1.21 or less

2022-02-25 15:38:01,320 - 123145488052224 - thread_pool_task_executor.py-thread_pool_task_executor:76 - ERROR: Numba needs NumPy 1.21 or less
Traceback (most recent call last):
  File "test_main.py", line 434, in <module>
    test_caller()
  File "test_main.py", line 427, in test_caller
    audio_class_pipeline_runner()
  File "test_main.py", line 402, in audio_class_pipeline_runner
    res = methodcaller(func, pipeline_name, embedding_size_each)(test_valid_embedding)
  File "/Users/jingjing/Workspace/towhee/tests/testcases/test_audio_embedding.py", line 201, in test_embedding_more_times
    embedding = embedding_pipeline(data_path + "towhee_test_audio_1.wav")
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/__init__.py", line 73, in __call__
    out_df = self._pipeline(in_df)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/pipeline.py", line 107, in __call__
    graph_ctx.join()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/graph_context.py", line 99, in join
    op.join()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_context.py", line 146, in join
    runner.join()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/site-packages/towhee/engine/operator_runner/runner_base.py", line 220, in join
    self._end_event.wait()
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/jingjing/miniconda3/envs/tow/lib/python3.8/threading.py", line 302, in wait
    waiter.acquire()
KeyboardInterrupt
```

### Expected Behavior

embedding successfully

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.4.1dev87
- OS(Ubuntu or CentOS):macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@jingkl 
please try this again, and close this issue if it is no problem now, thanks.

**Comment by jingkl** [comment]
Retry with no problems
