### ISSUE TITLE
[Bug]:Tried towhee's example and got an  AttributeError: "'function' object has no attribute 'fnmatch'"

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#885]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> import towhee
>>> from towhee.functional import DataCollection
>>> dataset = DataCollection.from_zip('https://towhee.io/towhee/image-dataset/media/branch/main/image_dataset.zip', '*/dataset/*.JPEG').unstream()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jingjing/towhee/towhee/functional/data_collection.py", line 169, in unstream
    return DataCollection.unstream(self._iterable)
  File "/Users/jingjing/towhee/towhee/functional/data_collection.py", line 173, in unstream
    iterable = list(iterable)
  File "/Users/jingjing/towhee/towhee/functional/mixins/data_source.py", line 65, in inner
    path_list = glob.fnmatch.filter(file_list, pattern)
AttributeError: 'function' object has no attribute 'fnmatch'
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):towhee 0.5.1.dev69
- OS(Ubuntu or CentOS): macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jingkl** [comment]
Already verified, fixed
