### ISSUE TITLE
[Bug]: Found towhee's exception handling case reporting an error“Incorrect operator format.”

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> import towhee
>>> from towhee.functional import DataCollection
>>> dc = DataCollection.range(5)
>>> (
...     dc.map(lambda x: x+1)
...       .map(lambda x: x*2)
...       .to_list()
... )
[2, 4, 6, 8, 10]
>>> dc.set_parallel(num_worker=5) \
...     .load_image() \
...     .towhee.resnet_model(model_name='resnet50')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/hparam/hyperparameter.py", line 205, in __call__
    return self._callback(self._path, self._index, *args, **kwds)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 652, in wrapper
    return self.map(op)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 26, in wrapper
    return self.factory(func(self, *arg, **kws))
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 377, in map
    if hasattr(unary_op, 'is_stateful') and unary_op.is_stateful:
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/factory.py", line 109, in is_stateful
    self._op = op(self._name, self._tag, **self._kws)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/factory.py", line 45, in op
    op_obj = loader.load_operator(operator_src, kwargs, tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 142, in load_operator
    op = factory(function, args, tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_loader.py", line 113, in load_operator_from_cache
    path = fm.get_operator(operator=function, tag=tag)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/hub/file_manager.py", line 416, in get_operator
    raise ValueError('''Incorrect operator format, should be '<author>/<operator_repo>'.''')
ValueError: Incorrect operator format, should be '<author>/<operator_repo>'.
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.5.1.dev82
- OS(Ubuntu or CentOS):macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment]
The operator is removed and the document will update to the latest version when the new operator is ready.

An error message is added to improve the user experience.
