### ISSUE TITLE
[Bug]: Try towhee's example with the error "No module named 'sklearn'"

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
>>> from towhee.functional import DataCollection
>>> dc = DataCollection.range(10)
>>> train, test = dc.split_train_test(shuffle=False)
2022-03-31 15:23:03,907 - 4600618496 - sklearn_utils.py-sklearn_utils:21 - ERROR: sklearn not found, you can install via `pip install scikit-learn`.
Traceback (most recent call last):
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/utils/sklearn_utils.py", line 18, in <module>
    from sklearn.metrics import confusion_matrix, accuracy_score, recall_score
ModuleNotFoundError: No module named 'sklearn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/mixins/dataset.py", line 162, in split_train_test
    from towhee.utils import sklearn_utils
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/utils/sklearn_utils.py", line 22, in <module>
    raise ModuleNotFoundError('sklearn not found, you can install via `pip install scikit-learn`.') from e
ModuleNotFoundError: sklearn not found, you can install via `pip install scikit-learn`.
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):towhee==0.5.1.dev103
- OS(Ubuntu or CentOS):macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jingkl** [comment]
> /duplicate #935

The document is not completely revised, right?

**Comment by shiyu22** [comment]
@jingkl Actually it was normal in Towhee to [report this log](https://github.com/towhee-io/towhee/blob/main/towhee/utils/sklearn_utils.py#L22), it shows how to solve it by `pip install scikit-learn`.

Towhee will not integrate these unnecessary packages, because it is too heavy, such as sklearn, ipython and cv2.

**Comment by shiyu22** [comment]
> > /duplicate #935
> 
> The document is not completely revised, right?

You are right, we will add the requirements before using DataColleation in docs.

**Comment by pravee42** [comment]
You can just install `sklearn` manually until they will update they update the module

**Comment by shiyu22** [comment]
#981
